puppetlabs/puppet-runtime

- configs/projects/agent-runtime-5.5.x.rb
Adds a runtime project for puppet-agent's new 5.5.x branch
> (maint) Add project for puppet-agent 5.5.x

- configs/components/rubygem-semantic_puppet.rb
Relates to https://github.com/puppetlabs/puppetserver/pull/1692#issuecomment-387880938
> (PUP-7157) Set specific path for shared gems folder for semantic_puppet

- configs/components/runtime-pe-installer.rb
- configs/projects/pe-installer-runtime.rb
Add the pe-installer-runtime, based off the bolt-runtime.
> (PE-23817) Add pe-installer-runtime

- Gemfile
- configs/platforms/osx-10.12-x86_64.rb
- configs/projects/agent-runtime-5.5.x.rb
WIP: changed project osx-10.12 template to use hombrew in the context of a test user
This is work in progress but would be good if you have a look on it
Related PR's:
https://github.com/puppetlabs/vanagon/pull/587
https://github.com/puppetlabs/puppet-agent/pull/1568
> (PA-1272) Refactor our use of homebrew to not run as root

- configs/platforms/osx-10.13-x86_64.rb
- configs/platforms/osx-10.14-x86_64.rb
- configs/projects/agent-runtime-5.5.x.rb
Reference PR: [puppet-agent/1661](https://github.com/puppetlabs/puppet-agent/pull/1661)
> (PA-2426) Leatherman on OSX

- .gitignore
- Gemfile
This pull request contains two patches:
- Allow `VANAGON_LOCATION` and `PACKAGING_LOCATION` to pull from HTTPS sources in addtion to SSH sources.
- Add support for `Gemfile.local`.
> Improve Gemfile

- configs/components/rubygem-addressable.rb
- configs/components/rubygem-concurrent-ruby.rb
- configs/components/rubygem-cri.rb
- configs/components/rubygem-excon.rb
- configs/components/rubygem-gssapi.rb
- configs/components/rubygem-hiera.rb
- configs/components/rubygem-multipart-post.rb
- configs/components/rubygem-net-http-persistent.rb
- configs/components/rubygem-public_suffix.rb
- configs/components/rubygem-puppet.rb
- configs/components/rubygem-r10k.rb
- configs/components/rubygem-rubyzip.rb
- configs/components/rubygem-unicode-display_width.rb
- configs/components/rubygem-winrm-fs.rb
- generate.rb
Update gems packaged with bolt. Also include a ruby script to help discover gems that could be udpated.
> (BOLT-1360) Update component gems for bolt-runtime

- configs/components/runtime-pdk.rb
https://jenkins-master-prod-1.delivery.puppetlabs.net/view/puppet-runtime/view/pdk-runtime/job/platform_pdk-runtime_runtime-vanagon-packaging_master/97/
> (PDK-1440) Build pdk-runtime for Debian 10

- configs/components/rubygem-addressable.rb
- configs/components/rubygem-aws-partitions.rb
- configs/components/rubygem-aws-sdk-core.rb
- configs/components/rubygem-aws-sdk-ec2.rb
- configs/components/rubygem-facter.rb
- configs/components/rubygem-public_suffix.rb
- configs/components/rubygem-puppet.rb
- configs/components/rubygem-puppet_forge.rb
- configs/components/rubygem-r10k.rb
Keep up to date with latest gem releases for bolt/bolt-server packages.
> Ship updated gem components for bolt/bolt-server runtimes

- configs/components/rubygem-aws-partitions.rb
- configs/components/rubygem-aws-sdk-core.rb
- configs/components/rubygem-aws-sdk-ec2.rb
- configs/components/rubygem-orchestrator_client.rb
- configs/components/rubygem-puppet-resource_api.rb
- configs/components/rubygem-puppet.rb
- configs/components/rubygem-rubyzip.rb
Pull in gem updates for bolt and bolt-server runtimes.
> (packaging) Ship updated bolt gem components

- configs/platforms/solaris-11-i386.rb
- configs/platforms/solaris-11-sparc.rb
This PR remove solarisstudio publisher as it is not used in the Agent Pipeline
> (maint) remove solarisstudio publisher

- azure-pipelines.yml
- Set reasonable upper bounds for various stages in Azure to abort
jobs quickly when Docker misbehaves
> (maint) Add Azure step timeouts

- configs/components/rubygem-aws-partitions.rb
- configs/components/rubygem-aws-sdk-core.rb
- configs/components/rubygem-aws-sdk-ec2.rb
- configs/components/rubygem-hiera.rb
- configs/components/rubygem-puppet.rb
- configs/components/rubygem-r10k.rb
Pull in latest gem components for the bolt and bolt-server runtime projects.
> (packaging) Update bolt and bolt-server components

- configs/components/curl.rb
- configs/components/git.rb
https://jenkins-master-prod-1.delivery.puppetlabs.net/view/PDK/view/master/job/platform_pdk-runtime_runtime-vanagon-packaging_master/
> (PDK-1529) Update git to 2.24.0

- configs/projects/_shared-pe-bolt-server.rb
This commit adds the new bolt dependency to the shared bolt-server runtime project.
> (packaging) Include bolt's new puppet-strings dep bolt-server

- configs/components/puppet-ca-bundle.rb
- configs/components/ruby-2.4.9.rb
- configs/components/ruby-2.5.7.rb
- configs/platforms/ubuntu-14.04-amd64.rb
- configs/platforms/ubuntu-14.04-i386.rb
- configs/projects/_shared-agent-components.rb
- ext/build_defaults.yaml
This reverts commit 801b9f08deff39621b6d4a09be7d4d572be95dfc.
> Revert "(PA-2856) Remove Ubuntu 14.04 from puppet-runtime"

- configs/components/boost.rb
- configs/components/openssl-1.1.1.rb
- configs/components/runtime-agent.rb
- configs/platforms/aix-7.1-ppc.rb
- configs/projects/_shared-agent-settings.rb
- configs/projects/agent-runtime-5.5.x.rb
use openssl 1.1.1 except windows fips
build boost in runtime except sles-15
> (PUP-10166) upgrade openssl version

- configs/components/boost.rb
- configs/components/openssl-1.1.1.rb
- configs/components/runtime-agent.rb
- configs/platforms/aix-7.1-ppc.rb
- configs/projects/_shared-agent-settings.rb
- configs/projects/agent-runtime-5.5.x.rb
This reverts commit 9b925fbe799863e85309d74df74181092cc13394
Downgrading OpenSSL to 1.0.2 requires additional work, reverting runtime is not enough.
This commit: 9b925fbe799863e85309d74df74181092cc13394 broke the puppet agent build.
This is a revert to the revert and the following PR:https://github.com/puppetlabs/puppet-runtime/pull/269 will add libssl 1.0.2 to the puppet agent package to fix the PE Smoke tests.
Tested PE Smoke with the changes in this PR:https://github.com/puppetlabs/puppet-runtime/pull/269 and they passed.
```
/tmp/frankenmodules/pe_acceptance_tests/acceptance/tests/99_final_tests/destructive/mcollective/uninstall/uninstall_mcollective.rb passed in 35.14 seconds
Test Suite: tests @ 2019-12-19 14:46:18 +0000
- Host Configuration Summary -
- Test Case Summary for suite …
```
> Revert "Merge pull request #268 from sarameisburger/maint"

- configs/components/boost.rb
- configs/components/openssl-1.1.1.rb
- configs/components/openssl-lib.rb
- configs/components/runtime-agent.rb
- configs/platforms/aix-7.1-ppc.rb
- configs/projects/_shared-agent-settings.rb
- configs/projects/agent-runtime-5.5.x.rb
besides openssl-1.1.1, deliver also openssl-1.0.2 libs to unblock PE while keeping agent updated
> (maint) openssl 1.0.2 libs

- configs/components/rubygem-thor.rb
This reverts commit e2236fb73e288ca63e3238b294c81031e18a0961, reversing
changes made to 75a1b9e600d7939c176bb5c9f3a6bea2275b94c2.
> Revert "(maint) bump thor to 1.0.1 (#273)"

- configs/components/rubygem-thor.rb
Reverts puppetlabs/puppet-runtime#277
> Revert "Revert "(maint) bump thor to 1.0.1 (#273)""

- configs/components/openssl-1.0.2.rb
- configs/components/openssl-lib.rb
- configs/projects/_shared-agent-settings.rb
- resources/patches/openssl/openssl-enforce-fips-on-fips-mode.patch
- resources/patches/openssl/openssl-low-level-access.patch
if openssl if built with fips options, enforce fips mode by default
> (PA-3025) enforce fips on fips builds

- configs/platforms/aix-7.1-ppc.rb
Running a build right now to see if this fixes the make failures
> (maint) Bump make and add libffi on AIX 7.1

- configs/components/_base-rubygem.rb
- configs/components/pl-ruby-patch.rb
- configs/components/rubygem-ffi.rb
- configs/projects/_shared-agent-components.rb
This should make it easier to add gems with native extensions on cross-compiled platforms
> (maint) Patch rubygems on cross-compiled platforms

- configs/components/boost.rb
- configs/components/runtime-agent.rb
- configs/components/yaml-cpp.rb
- configs/platforms/ubuntu-20.04-amd64.rb
Beside adding new platform, I rewrote the conditions requiring updates to default to OSs not requiring pl-build-tools
> (PA-3130) add support for Ubuntu 20.04

- configs/components/openssl-1.1.1.rb
- resources/patches/openssl/openssl-1.1.1a-revert-7a061312.patch
openssl-1.1.1d was upgraded to openssl-1.1.1f
> (SEC-90) upgrade openssl version

- configs/components/ruby-2.5-augeas.rb
- configs/components/ruby-2.5-selinux.rb
- configs/components/ruby-2.5-stomp.rb
- configs/components/ruby-2.5.8.rb
- configs/projects/agent-runtime-master.rb
- configs/projects/bolt-runtime.rb
- configs/projects/pdk-runtime.rb
- configs/projects/pe-installer-runtime.rb
This PR bumps ruby component to 2.5.8.
> (PA-3176) Bump ruby to 2.5.8

- configs/components/ruby-2.4.10.rb
- configs/projects/agent-runtime-5.5.x.rb
- configs/projects/pdk-runtime.rb
Bumps ruby to 2.4.10 on 5.5.x stream
> (PA-3179) Bump ruby to 2.4.10 on 5.5.x

- configs/projects/client-tools-runtime-johnson.rb
- configs/projects/client-tools-runtime-kearney.rb
- configs/projects/client-tools-runtime-lovejoy.rb
https://github.com/puppetlabs/ci-job-configs/pull/6979
> (maint) No longer build client-tools-runtimes for dead streams

- configs/components/puppet-ca-bundle.json
Once this is merged the automatic tagging job will tag + build runtime then we should be good 👍
> (RE-13318) Update puppet-ca-bundle version to 1.0.9

- configs/components/rubygem-ffi.rb
- configs/components/rubygem-optimist.rb
This updates rubygems used by multiple projects to their latest versions.
@puppetlabs/night-s-watch Need approval for bumping all three gems
@puppetlabs/installer-and-management Need approval for `ffi`
@puppetlabs/pdk Need approval for `ffi`
> (packaging) Bump shared rubygem versions

- configs/platforms/el-8-aarch64.rb
can be merged together with https://github.com/puppetlabs/puppet-runtime/pull/374
> (maint) clean packages provisioned with el-8-aarch64 platform

- configs/projects/_shared-client-tools-runtime.rb
also use vendored openssl on redhat-fips
> (CT-132) bump openssl component to 1.1.1

- configs/components/boost.rb
- configs/components/ruby-2.5.8.rb
- configs/components/ruby-2.7.1.rb
- configs/components/runtime-agent.rb
- configs/platforms/aix-7.1-ppc.rb
- resources/patches/boost/no-O_CLOEXEC-on-aix71.patch
This is intermediary step of AIX6.1 removal on master and main
>  (PA-3435) update platform to build AIX7.1 runtime on master and main 

- configs/projects/client-tools-runtime-2019.8.x.rb
- configs/projects/client-tools-runtime-main.rb
added main project and renamed master to 2019.8.x
should be merged with: https://github.com/puppetlabs/ci-job-configs/pull/7467
> (CT-136) client-tools runtime updates

- configs/components/rubygem-aws-partitions.rb
- configs/components/rubygem-aws-sdk-core.rb
- configs/components/rubygem-aws-sdk-ec2.rb
- configs/components/rubygem-cri.rb
- configs/components/rubygem-erubi.rb
- configs/components/rubygem-facter.rb
- configs/components/rubygem-gssapi.rb
- configs/components/rubygem-molinillo.rb
- configs/components/rubygem-paint.rb
- configs/components/rubygem-puppetfile-resolver.rb
- configs/components/rubygem-yard.rb
Part of https://github.com/puppetlabs/bolt/pull/2496
> (maint) Bump shared rubygems for bolt, pe-bolt-server

- configs/components/git.rb
> (maint) update git 2.31

- configs/platforms/osx-11-x86_64.rb
depends on: https://github.com/puppetlabs/packaging/pull/1101
> (PA-3615) Add OSX 11 Big Sur to puppet-runtime

- configs/components/rubygem-aws-partitions.rb
- configs/components/rubygem-aws-sdk-core.rb
- configs/components/rubygem-aws-sdk-ec2.rb
- configs/components/rubygem-bindata.rb
- configs/components/rubygem-cri.rb
- configs/components/rubygem-facter.rb
- configs/components/rubygem-puppet-strings.rb
- configs/components/rubygem-puppet.rb
- configs/components/rubygem-r10k.rb
- configs/projects/bolt-runtime.rb
This bumps Bolt's rubygem components to their latest versions.
> (maint) Bump Bolt rubygem components

- tasks/vanagon_component_diff.rake
- Exclude empty platforms from output and fix args passing
- Add disclaimer message before output
> (maint) vanagon:component_diff script updates

- configs/components/rubygem-bcrypt_pbkdf.rb
- configs/components/rubygem-concurrent-ruby.rb
- configs/components/rubygem-hiera-eyaml.rb
- configs/components/rubygem-multi_json.rb
Bump gem dependency versions to their latest resolved version for gems
that are shared among multiple projects.
> (maint) Bump shared gem dependencies

- configs/components/ruby-2.7-augeas.rb
- configs/components/ruby-2.7-selinux.rb
- configs/components/ruby-2.7-stomp.rb
- configs/components/ruby-2.7.5.rb
- configs/projects/agent-runtime-main.rb
- configs/projects/bolt-runtime.rb
- configs/projects/pdk-runtime.rb
- configs/projects/pe-installer-runtime-main.rb
- resources/patches/ruby_27/windows_configure.patch
This PR bumps Ruby component to 2.7.4.
> (PA-4130) Bump ruby to 2.7.5

- configs/components/rubygem-mini_portile2.rb
- configs/components/rubygem-nokogiri.rb
- configs/components/rubygem-racc.rb
- configs/projects/_shared-agent-components.rb
Vendoring nokogiri gem on OSx improves the performance when reading services.
> (PUP-11332) Add nokogiri gem to puppet-runtime

- Gemfile
Updating packaging gem constraint for RHEL-9
> (maint) [PA-4180] update RHEL-9 packaging

- configs/components/_base-ruby-augeas.rb
- configs/components/_base-ruby.rb
- configs/components/augeas.rb
- configs/components/boost.rb
- configs/components/libxml2.rb
- configs/components/libxslt.rb
- configs/components/ruby-2.5.9.rb
- configs/components/ruby-2.7.6.rb
- configs/components/yaml-cpp.rb
I got hit with [a Rubocop PR failure](https://github.com/puppetlabs/pxp-agent-vanagon/runs/6396061627?check_suite_focus=true) in pxp-agent-vanagon and wanted to update my earlier work in https://github.com/puppetlabs/puppet-runtime/pull/537
> (maint) Update macOS 12 M1 changes to single quote

- configs/components/rubygem-nokogiri.rb
For the second time this month there is a security patch for Nokogiri.
> (PA-4489) Bump nokogiri

- configs/components/puppet-ca-bundle.rb
Previously, we used a long regex to determine which agent platforms
we would build a cert store containing external ca roots for. However,
the allowlist regex is rarely updated and is significantly out of date.
To prevent the list becoming out of date this patch updates us to
conditionally build the keystore when java is present intead.
> (PA-4440) Build java cert store whenever java is available

- configs/components/rubygem-orchestrator_client.rb
Pull in bugfix for pcp timeout.
> (BOLT-1583) Bump orchestrator_client gem

- configs/components/curl.rb
Also fixed some white space issues on lines 38 and 39.
> (PA-4472) Bump curl to 7.83.1

- configs/components/openssl-1.1.1.rb
A few medium level security fixes
> (PA-4551) Bump openssl from 1.1.1n to 1.1.1q

- configs/components/ruby-2.7.6.rb
testing with generic builder https://jenkins-platform.delivery.puppetlabs.net/view/vanagon-generic-builder/job/platform_vanagon-generic-builder_vanagon-generic-builder-init_generic-builder/1500
> patch rbinstall on macos

- configs/components/libicu.rb
libicu's runConfigureICU script doesn't support cross-compiling, so pass the
necessary options directly to `./configure`. Note we have to compile libicu
twice, for the current build and intended host as described in[1].
[1] https://unicode-org.github.io/icu/userguide/icu4c/build.html
> (CT-212) Cross-compile libicu for macOS arm64

- configs/projects/client-tools-runtime-2021.7.x.rb
'main' will now be for PE 2023
> (PE-34432) Create client-tools-runtime-2021.7.x

- configs/components/augeas.rb
- configs/components/readline.rb
- configs/platforms/osx-10.15-x86_64.rb
- configs/platforms/osx-11-arm64.rb
- configs/platforms/osx-11-x86_64.rb
- configs/platforms/osx-12-arm64.rb
- configs/platforms/osx-12-x86_64.rb
- configs/projects/_shared-agent-components.rb
- configs/projects/bolt-runtime.rb
- configs/projects/pdk-runtime.rb
configure shipped with augeas does not link with libtool properly on big sur.
> (PUP-11625) fix augeas support on osx big sur

- configs/projects/agent-runtime-7.x.rb
With this the diff between main and 7.x runtime is minimal.
> (maint) Bring patch over from main to 7.x runtime

- configs/components/ruby-shadow.rb
- resources/patches/ruby_32/ruby-shadow-taint.patch
This pulls in the patch submitted to upstream for both files.
> (PA-4843) Apply shadow/shadow.c patch too

- configs/platforms/osx-11-arm64.rb
- configs/platforms/osx-11-x86_64.rb
- configs/platforms/osx-12-arm64.rb
- configs/platforms/osx-12-x86_64.rb
See VANAGON-214
Updates osx-\*-\*.rb platform configs to inherit from vanagon except for [osx-10.15-x86_64](https://github.com/puppetlabs/puppet-runtime/blob/master/configs/platforms/osx-10.15-x86_64.rb) which already inherited.
This shows the diff between agent-runtime-main with the last released vanagon versus this PR with https://github.com/puppetlabs/vanagon/pull/789
```diff 
140a141
>         "export HOMEBREW_NO_ANALYTICS=1",
150a152
>         "createhomedir -c -u test",
152d153
<         "sudo chown -R test:admin /Users/test/",
349a351
>         "export HOMEBREW_NO_ANALYTICS=1",
359a362
>         "createhomedir -c -u test",
361d363
<         "sudo chown -R test:admin /Users/test/",
577a580
>         "export HOMEBREW_NO_ANALYTICS=1",
587a591
>         "createhomedir -c -u test", …
```
> (maint) Inherit macOS platform defaults from vanagon

- configs/platforms/aix-7.1-ppc.rb
Passed in https://jenkins-platform.delivery.puppetlabs.net/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/BUILD_TARGET=aix-7.1-ppc,SLAVE_LABEL=k8s-worker/1940/
> (maint) Install AIX yum.sh from artifactory

- configs/components/openssl-3.0.rb
Small update to the configure flags used with openssl 3.
> (PA-5409) Update Configure flags for openssl3

- configs/platforms/osx-13-x86_64.rb
Added platform for macos13 intel.
> (PA-4592) added macos-13-x86_64 platform

- configs/components/rubygem-ffi.rb
This PR sets the PKG_CONFIG_PATH for the rubygem-ffi component.
> (PA-5640) Fix up ffi gem

- configs/components/curl.rb
- resources/patches/curl/CVE-2023-27535.patch
- resources/patches/curl/CVE-2023-28319.patch
- resources/patches/curl/CVE-2023-32001.patch
Added 3 medium security pataches:
1. https://curl.se/docs/CVE-2023-32001.html
2. https://curl.se/docs/CVE-2023-28319.html
3. https://curl.se/docs/CVE-2023-27535.html
> (PA-5700) Added 3 medium severity patches

- configs/components/rubygem-sys-filesystem.rb
Bump sys-filesystem to the latest available version to apply fix https://github.com/djberg96/sys-filesystem/commit/0b531529b2be1ae2c6f66dc6a18aea094a2bc064
> (FACT-3175) Bump sys-filesystem to 1.4.4

- configs/components/rubygem-addressable.rb
- configs/components/rubygem-aws-partitions.rb
- configs/components/rubygem-aws-sdk-core.rb
- configs/components/rubygem-aws-sdk-ec2.rb
- configs/components/rubygem-aws-sigv4.rb
- configs/components/rubygem-connection_pool.rb
- configs/components/rubygem-facter.rb
- configs/components/rubygem-hiera.rb
- configs/components/rubygem-json-schema.rb
- configs/components/rubygem-net-http-persistent.rb
- configs/components/rubygem-puppet-resource_api.rb
- configs/components/rubygem-puppet-strings.rb
- configs/components/rubygem-puppet.rb
- configs/components/rubygem-r10k.rb
- configs/components/rubygem-rexml.rb
- configs/components/rubygem-thor.rb
- configs/components/rubygem-unicode-display_width.rb
- configs/components/rubygem-webrick.rb
- configs/components/rubygem-yard.rb
- configs/projects/bolt-runtime.rb
- configs/projects/pe-bolt-server-runtime-2021.7.x.rb
This commit updates the gems shipped with bolt to latest versions.
> (maint) Update bolt dependencies

- configs/platforms/el-9-x86_64.rb
Not sure what this does but looks to be something particular to your images.
> Make temp fix local to P

- configs/components/curl.rb
- resources/patches/curl/CVE-2023-38546.patch
Commit from curl for reference:
https://github.com/curl/curl/commit/61275672b46d9abb32857404
> (PA-5861) Added CVE-2023-38546 patch for curl(Ref from curl 7.81.0-1ubuntu1.14 source package in Ubuntu)

- configs/platforms/amazon-2023-aarch64.rb
- configs/platforms/amazon-2023-x86_64.rb
Added platform for amazon-linux-2023 x86_64 & aarch64
> [PA-5567] : Added platform for amazon-linux-2023 x86_64 & aarch64

- configs/components/openssl-1.1.1.rb
> (PA-5925) added rpath for openssl 1.1.1

- configs/components/openssl-1.1.1.rb
rectified the compiler option.
> (PA-5925) rectified option in openssl1.1.1

- .github/workflows/jira.yml
This reverts commit e9cec0f327cfa3f164265b04e0f9511e345c011c, reversing changes made to 73ba872de328f6f2fa8877561c7ddcb37e302291.
> Revert "Merge pull request #764 from joshcooper/label_pulls"

- configs/components/_base-ruby-selinux.rb
- configs/platforms/debian-12-amd64.rb
[vanagon-generic-builder agent-runtime-main](https://jenkins-platform.delivery.puppetlabs.net/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/2550/)
[vanagon-generic-builder agent-runtime-7.x](https://jenkins-platform.delivery.puppetlabs.net/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/2552/)
>  (PA-5550) debian 12 x86_64 platform support

- configs/platforms/debian-12-aarch64.rb
- configs/platforms/debian-12-armhf.rb
[vanagon-generic-builder agent-runtime-main](https://jenkins-platform.delivery.puppetlabs.net/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/2549/)
[vanagon-generic-builder agent-runtime-7.x](https://jenkins-platform.delivery.puppetlabs.net/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/2551/)
> (PA-5751) debian 12 arm platform support

- configs/components/openssl-3.0.rb
- resources/patches/openssl/CVE-2024-2511.patch
https://www.openssl.org/news/secadv/20240408.txt
https://github.com/openssl/openssl/commit/b52867a9
> (PA-6378) Address a low-severity vulnerability, CVE-2024-2511

- configs/components/augeas.rb
latest versions are not available on download.augeas.net
> fix augeas pkg.url

- configs/components/rubygem-childprocess.rb
Pin can be moved as PR against gem has been merged and released.
> (CAT-1643) Update childprocess pin

- configs/components/_base-ruby-augeas.rb
- resources/patches/augeas/ruby-augeas-0.5.0-patch_c_extension.patch
- resources/patches/augeas/ruby-augeas-0.5.0-patch_remove_unused_parameter.patch
Reverts puppetlabs/puppet-runtime#905
PEZ is failing on both streams hence reverting
> Revert "(PA-6900) Update ruby-augeas to 0.6.0"

- configs/components/libxml2.rb
- configs/components/libxslt.rb
agent-runtime-main:https://jenkins-platform.delivery.puppetlabs.net/view/vanagon-generic-builder/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/3286/
https://jenkins-platform.delivery.puppetlabs.net/view/vanagon-generic-builder/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/3285/
agent-runtime-7.x: https://jenkins-platform.delivery.puppetlabs.net/view/vanagon-generic-builder/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/3287/
> (PA-6973) Upgrade libxml2 and libxslt

- configs/components/rubygem-aws-partitions.rb
- configs/components/rubygem-aws-sdk-core.rb
- configs/components/rubygem-aws-sdk-ec2.rb
- configs/components/rubygem-aws-sigv4.rb
- configs/components/rubygem-facter.rb
- configs/components/rubygem-faraday_middleware.rb
- configs/components/rubygem-getoptlong.rb
- configs/components/rubygem-highline.rb
- configs/components/rubygem-json-schema.rb
- configs/components/rubygem-minitar.rb
- configs/components/rubygem-net-http-persistent.rb
- configs/components/rubygem-nori.rb
- configs/components/rubygem-pathspec.rb
- configs/components/rubygem-public_suffix.rb
- configs/components/rubygem-rexml.rb
- configs/components/rubygem-unicode-display_width.rb
- configs/components/rubygem-winrm.rb
Updated Ruby gems necessary for Bolt + Ruby3 (same as #902 but created a new pr with clean commits)
> Updated components necessary for Bolt + Ruby3

- configs/components/rubygem-puppet.rb
- configs/projects/bolt-runtime.rb
- configs/projects/pe-bolt-server-runtime-2023.8.x.rb
- configs/projects/pe-bolt-server-runtime-main.rb
- configs/projects/pe-installer-runtime-2023.8.x.rb
- configs/projects/pe-installer-runtime-main.rb
Reverts puppetlabs/puppet-runtime#924
> Revert "Update rubygem-puppet to 8.10.0"
