- configs/components/curl.rb
ported from https://github.com/puppetlabs/pdk-vanagon/pull/93
> (maint) Update to curl 7.57.0

- configs/components/base-ruby.rb
- configs/components/ruby-2.1.9.rb
- configs/components/ruby-2.4.3.rb
- configs/components/rubygem-win32-eventlog.rb
- configs/platforms/cumulus-2.2-amd64.rb
- configs/platforms/eos-4-i386.rb
- configs/platforms/redhat-fips-7-x86_64.rb
- configs/projects/agent-runtime-1.10.x.rb
- configs/projects/agent-runtime-5.3.x.rb
- configs/projects/agent-runtime-master.rb
- configs/projects/base-agent-runtime.rb
There are two commits here:
- Add cumulus, arista, and redhat-fips platforms in support of the agent runtime ([here's an example build](http://jenkins-release.delivery.puppetlabs.net/job/vanagon_generic_job/1378/)), and
- Fix the ruby path for pdk ([example build](http://jenkins-release.delivery.puppetlabs.net/job/vanagon_generic_job/1377/console))- puppet-agent uses the prefix as the ruby installation directory, but pdk uses the `:ruby_dir` setting - this updates the agent runtime to use the prefix directory unless `:ruby_dir` is explicitly set, and uses `:ruby_dir` as the ruby installation directory generally.
> Add three new platforms, fix ruby location for pdk

- configs/components/base-ruby.rb
AIX applications default to a static maximum heap size of 256MB.
This was causing heap exhaustion in the ruby interpreter when
attempting to add an artifactory source for rubygems.
Upping the heap limit allows Ruby to complete the operation
successfully.
> (PA-1822) Set ruby maximum heap size to 2GB

- configs/components/curl.rb
Updates curl to 7.58.0 - this was a super simple update in the agent, but [here are some example runtime builds with this new version](http://jenkins-release.delivery.puppetlabs.net/job/vanagon_generic_job/1402/) if anyone's curious.
> (maint) Update curl to version 7.58.0

- configs/components/rubygem-gettext-setup.rb
gettext-setup was recently bumped to version 0.30 in puppet-agent - [here's an example build with this version in the runtime](http://jenkins-release.delivery.puppetlabs.net/job/vanagon_generic_job/1403/).
> (maint) Update rubygem-gettext-setup to v0.30

- configs/components/runtime-pdk.rb
Simplest fix for 1.4.1 release blocker that I can see.
> (FIXUP) Place zlib1.dll in the correct location for PDK Ruby

- configs/components/augeas.rb
- configs/components/ruby-selinux.rb
- configs/projects/agent-runtime-1.10.x.rb
- configs/projects/agent-runtime-5.3.x.rb
- configs/projects/agent-runtime-master.rb
- resources/files/ruby-selinux/libselinux-1.33.4.pc
- resources/patches/augeas/augeas-1.10.1-gnulib-pthread-in-use.patch
- resources/patches/augeas/augeas-1.4.0-osx-stub-needed-readline-functions.patch
- resources/patches/augeas/augeas-1.4.0-src-pathx.c-parse_name-correctly-handle-trailing-ws.patch
- resources/patches/augeas/augeas-1.4.0-sudoers-negated-command-alias.patch
Branches of puppet-agent now variously use three different versions of augeas - 1.4.0, 1.8.1, and 1.10.1. This PR adds support for all three versions (pdk uses version 1.8.1, which is currently the only version of augeas available in puppet-runtime).
Augeas presents a bit of a problem in terms of how to handle multiple possible versions; `ruby-augeas` depends on having _some_ version of augeas, but it doesn't matter which one. Attempting to successfully include a `build_requires 'augeas'` line in the `ruby-augeas` component thus becomes tricky when there are multiple possible augeas versions. If we added separate, version-specific augeas components (e.g. `augeas-1.4.0.rb`), it seems like we'd need to either:
- carry some information about the augeas version into the ruby-augeas component …
> (maint) Allow for multiple augeas versions

- configs/components/rubygem-fast_gettext.rb
- configs/projects/agent-runtime-1.10.x.rb
puppet-agent 1.10.x uses version 1.1.0 of the fast-gettext rubygem - all other projects use version 1.1.2. This PR adds an optional `rubygem_fast_gettext_version` setting that projects can use to select a version explicitly; 1.1.2 is used by default.
> (maint) Add fast-gettext 1.1.0

- configs/components/rubygem-ffi.rb
- configs/projects/agent-runtime-1.10.x.rb
puppet-agent's 1.10.x branch uses version 1.9.14 of rubygem-ffi; All other branches (and PDK) use the existing 1.9.18 version. This PR adds version 1.9.14, and a `rubygem_ffi_version` setting that projects can use to select a version explicitly. If `rubygem_ffi_version` is empty, version 1.9.18 will be used by default.
> (maint) Add rubygem-ffi version 1.9.18

- configs/components/ruby-2.4.3.rb
- resources/patches/ruby_243/rubygems_add_puppet_vendor_dir.patch
Ported from puppet-agent; Affects ruby 2.4.3 only - [here's the original commit](https://github.com/puppetlabs/puppet-agent/commit/7d87bab1352db02705cbfce561038ad34521fe48)
> (PA-1888) Add custom vendor dir for shared rubygems

- configs/platforms/fedora-f25-i386.rb
- configs/platforms/fedora-f25-x86_64.rb
This reverts commit 598e4ace834ce369d7a370a1549295783aca2f50.
Fedora 25 hasn't been removed from the agent yet, so this removal was premature - we can reapply it later once the removal process is finished there.
> Revert "(maint) Remove Fedora 25 platforms"

- configs/components/curl.rb
Test build of these changes can be found here: 
http://jenkins-release.delivery.puppetlabs.net/job/vanagon_generic_job/1429/
> (maint) Update curl to 7.59.0

- configs/components/rubygem-multi_json.rb
- configs/projects/agent-runtime-5.5.x.rb
- configs/projects/agent-runtime-master.rb
Ported from puppet-agent; used in 5.5.x and master agent projects only. [The addition to puppet-agent is here](https://github.com/puppetlabs/puppet-agent/commit/783204701cd0ddc7db52cd08a064e6bde16918ec) - the `:ruby_vendordir` setting in that commit is preserved in the runtime via `inherit_settings` for now, but it's something we'll need to double-check when the directions of settings inheritance is reversed in the near future.
> (PA-1888) Add multi_json rubygem

- configs/components/ruby-2.1.9.rb
- resources/files/ruby_243/rbconfig/rbconfig-aarch64-redhat-linux.rb
- resources/files/ruby_243/rbconfig/rbconfig-arm-linux-gnueabihf.rb
- resources/files/ruby_243/rbconfig/rbconfig-i386-pc-solaris2.10.rb
- resources/files/ruby_243/rbconfig/rbconfig-i386-pc-solaris2.11.rb
- resources/files/ruby_243/rbconfig/rbconfig-i686-w64-mingw32.rb
- resources/files/ruby_243/rbconfig/rbconfig-powerpc-ibm-aix6.1.0.0.rb
- resources/files/ruby_243/rbconfig/rbconfig-powerpc-ibm-aix7.1.0.0.rb
- resources/files/ruby_243/rbconfig/rbconfig-powerpc64le-linux-gnu.rb
- resources/files/ruby_243/rbconfig/rbconfig-powerpc64le-suse-linux.rb
- resources/files/ruby_243/rbconfig/rbconfig-ppc64le-redhat-linux.rb
- resources/files/ruby_243/rbconfig/rbconfig-s390x-linux-gnu.rb
- resources/files/ruby_243/rbconfig/rbconfig-sparc-sun-solaris2.10.rb
- resources/files/ruby_243/rbconfig/rbconfig-sparc-sun-solaris2.11.rb
- resources/files/ruby_243/rbconfig/rbconfig-x86_64-w64-mingw32.rb
- resources/patches/ruby_219/Remove-O_CLOEXEC-check-for-AIX-builds.patch
Two commits to resolve errors I made in porting ruby configs from puppet-agent:
- Add a missing AIX patch (seems to only affect AIX 7.n)
- Updated rbconfigs for ruby 2.4.3
These files were copied directly from puppet-agent. I ran some agent acceptance tests on a build using these commits and [everything seems to be in order](https://jenkins-master-prod-1.delivery.puppetlabs.net/job/platform_puppet-agent-extra_puppet-agent-integration-suite_adhoc-ad_hoc/104/) (barring a transient which a reload fixed).
> (PA-1888) Ruby fixes

- configs/projects/agent-runtime-1.10.x.rb
- configs/projects/agent-runtime-5.3.x.rb
- configs/projects/agent-runtime-5.5.x.rb
- configs/projects/agent-runtime-master.rb
- configs/projects/base-agent-runtime.rb
Previously, the puppet-agent runtime projects inherited their settings from puppet-agent using vanagon's `inherit_settings` feature - builds of the runtimes would clone puppet-agent to gather settings from that project. This PR ports relevant settings from the agent to puppet-runtime so that `inherit_settings` is no longer necessary here.
Once the changes in this PR are merged, the plan is to apply a corresponding change to puppet-agent, so that settings aren't duplicated across both projects; Instead, puppet-agent will use inherit_settings to gather settings from puppet-runtime, applying anything else it needs (wix settings, for example) afterward.
> (PA-1833) Rely on local puppet-agent settings instead of `inherit_settings`

- configs/components/base-ruby.rb
- configs/components/curl.rb
- configs/components/puppet-ca-bundle.rb
- configs/projects/agent-runtime-1.10.x.rb
- configs/projects/agent-runtime-5.3.x.rb
- configs/projects/agent-runtime-5.5.x.rb
- configs/projects/agent-runtime-master.rb
- configs/projects/base-agent-runtime.rb
The redhat FIPS platform available in the agent's 5.5.x and master branches requires the use of the system openssl package - this PR modifies the puppet-agent runtimes to use the system openssl when the `:system_openssl` setting is turned on.
I'm blocking this PR for now since it builds on changes in #26.
> (PA-1888) Allow use of system openssl for puppet-agent runtimes

- Gemfile
Vanagon 0.14.3 was too old to understand the redhat 7 FIPS platform - this doesn't matter in CI, since `VANAGON_LOCATION` is set to a newer version there, but locally we must update the Gemfile
> (packaging) Update vanagon to version 0.15.5

- README.md
Here are some minimal instructions on building runtimes - much of this content is copied from the puppet-agent repo.
> (maint) Update README with build instructions

- configs/components/openssl.rb
- configs/projects/agent-runtime-1.10.x.rb
- configs/projects/base-agent-runtime.rb
- configs/projects/pdk-runtime.rb
When adding puppet-agent runtime projects, there was an attempt to use the same openssl configure flags for all projects, which caused integration failures; This commit restores the original configurations
for all projects.
For reference, here are the previous configurations for each project - this PR is intended to restore the configure options used below:
- [puppet-agent master](https://github.com/puppetlabs/puppet-agent/blob/master/configs/components/openssl.rb#L100), [puppet-agent 5.5.x](https://github.com/puppetlabs/puppet-agent/blob/5.5.x/configs/components/openssl.rb#L100), and [puppet-agent 5.3.x](https://github.com/puppetlabs/puppet-agent/blob/c43e3f6b34b32d7dca2f2a337e34e6974a83a10b/configs/components/openssl.rb#L100), which are all the same
- [puppet-agent …
> (maint) Separate openssl flags between runtimes

- configs/components/curl.rb
PDK doesn't need the curl binaries, so they were being removed as part of the install step for the curl component. It turns out that although puppet-agent doesn't rely directly on the curl binaries, they're an important part of some workflows!
I've built some agent and pdk tarballs locally using this branch and verified that curl is present in the agent versions and absent in the pdk one (there are no acceptance tests for this).
> (PA-1951) Restore curl binaries in agent runtimes

- configs/platforms/redhatfips-7-x86_64.rb
- configs/projects/base-agent-runtime.rb
Dashes in platform names cause trouble down the line when it comes time
to add the platform to pe_repo, so make this platform name 'redhatfips'.
> (PA-1958) Rename redhat-fips platform to redhatfips

- configs/projects/agent-runtime-1.10.x.rb
- configs/projects/agent-runtime-5.3.x.rb
- configs/projects/agent-runtime-5.5.x.rb
- configs/projects/base-agent-runtime.rb
Since this gem is no longer used at runtime, it should be removed as a
dependency.
> (PA-1886) Remove gettext-setup gem

- configs/projects/agent-runtime-1.10.x.rb
- configs/projects/agent-runtime-5.3.x.rb
- configs/projects/agent-runtime-5.5.x.rb
Builds of rubygems rely on a runtime project setting, which (for agent
projects) isn't set until the base agent project is evaluated. This
commit moves the inclusion of gettext-setup to after this point.
> (PA-1886) Fix ordering of components in agent projects

- configs/components/runtime-bolt.rb
Copying runtime files failed on 32-bit systems because the directory
doesn't exist. Use the right directory.
> (BOLT-427) Fix for 32-bit systems

- configs/components/rubygem-hiera-eyaml.rb
- configs/components/rubygem-highline.rb
- configs/components/rubygem-trollop.rb
- configs/projects/agent-runtime-5.5.x.rb
- configs/projects/agent-runtime-master.rb
This commit also adds highline and trollop, both of which are
dependencies of hiera-eyaml.
> (PA-1925) Add hiera-eyaml rubygem

- configs/components/rubygem-hocon.rb
- configs/projects/agent-runtime-5.5.x.rb
- configs/projects/agent-runtime-master.rb
- configs/projects/base-agent-runtime.rb
This moves the hocon gem to the shared vendor dir, where it can be picked up by the resource_api gem.
It also makes sure that older versions of the agent do not try to set the shared gem vendor directory path, so that gem components don't have to check the agent version to know where they should be installed.
>  (maint) Migrate Hocon gem to shared vendor dir

- configs/projects/_shared-agent-components.rb
- configs/projects/_shared-agent-settings.rb
- configs/projects/agent-runtime-1.10.x.rb
- configs/projects/agent-runtime-5.3.x.rb
- configs/projects/agent-runtime-5.5.x.rb
- configs/projects/agent-runtime-master.rb
Managing special cases for agent runtimes while sharing a single common
base project provided too many opportunities for error in the order of
inclusion for settings and components. This commit separates the shared
configuration into two separate files - one each for settings and
components - so that settings can be customized in agent projects before
loading the shared components.
Fixes the gem home for rubygem-hocon, which wasn't correctly set on
5.5.x and master due to this problem.
> (PA-1983) Separate shared agent components & settings

- configs/components/_base-ruby.rb
- configs/components/augeas.rb
- configs/platforms/solaris-10-i386.rb
- configs/platforms/solaris-10-sparc.rb
While opencsw.org's mirror service is unavailable, use alternate
mirror for Solaris 10 dependency packages.
> (maint) Use alternate mirror for Solaris 10 builds

- configs/components/openssl.rb
- configs/platforms/ubuntu-18.04-amd64.rb
Adds a platform configuration for Ubuntu 18.04, bionic beaver. I also pared down the cases where pl-binutils is required for linux platforms in openssl, since it's not really necessary for newer platforms like this one (we're trying not to have to ship a pl-binutils for 18.04). Will unblock pending green builds on affected platforms.
> (PA-1874) Add Ubuntu 18.04 platform definition

- configs/projects/_shared-agent-components.rb
- configs/projects/agent-runtime-1.10.x.rb
- configs/projects/agent-runtime-5.3.x.rb
- configs/projects/agent-runtime-5.5.x.rb
We are deprecating mcollective from the puppet-agent for Platform
6. This includes deprecating ruby-stomp, because mcollective is the
only agent component that depends on it. Thus, work in this commit
removes ruby-stomp as a shared agent component, only declaring it as
a component in the 1.10.x, 5.3.x, and 5.5.x agent branches.
> (PA-1918) Remove ruby-stomp as a component from agent-runtime-master

- configs/platforms/solaris-10-i386.rb
- configs/platforms/solaris-10-sparc.rb
It looks like the GA Tech secondary mirrors have gone offline.
Switching back to the primaries.
> (maint) switch solaris to primary opencsw mirrors

- configs/components/rubygem-httpclient.rb
- configs/projects/agent-runtime-master.rb
This commit adds the HTTPClient gem, version 2.8.3, for use with the new
Puppet REST client.
> (PA-2018) Add httpclient gem

- configs/platforms/solaris-10-i386.rb
- configs/platforms/solaris-10-sparc.rb
Solaris10 uses the Vanagon provision_with capability to run a moderately
complex shell fragment to provision things. The issue is that if given a
series of shell commands to execute, only the exit status of the last command
run is noticed when determining success.
We have had issues with the mirror server for Solaris10 dropping off the
net, causing build fails. This change provides the ability to fail when
pkgutil fails to find the mirror, which means the build will fail much faster.
> (maint) notice when pkgutil can't find a source mirror

- Gemfile
- configs/projects/_shared-agent-settings.rb
- configs/projects/bolt-runtime.rb
- configs/projects/pdk-runtime.rb
Writes a yaml file containing the settings used during a build (plus a sha1sum for that file) to the output directory alongside other artifacts.
This is intended to make building downstream projects locally with development builds of puppet-runtime easier. It depends on https://github.com/puppetlabs/vanagon/pull/566, so I'm marking this `do not merge` for now.
> (PA-1995) Publish yaml settings on build for all projects

- configs/projects/bolt-runtime.rb
This is now a dependency of the vendored puppet in bolt, so we need to
explicitly pull it in.
> (maint) Add semantic_puppet to bolt-runtime

- configs/projects/agent-runtime-1.10.x.rb
The FFI gem was pinned due to some compatibility issues in intervening
versions. Since the latest version appears to work in newer agent
releases, we are unpinning it here in 1.10.x
> (maint) Unpin FFI gem in Agent 1.10.x

- configs/components/rubygem-net-ssh.rb
- configs/components/rubygem-semantic_puppet.rb
- configs/projects/agent-runtime-1.10.x.rb
- configs/projects/agent-runtime-5.3.x.rb
- configs/projects/agent-runtime-5.5.x.rb
Fixes a few regressions in gem versions for some branches of puppet-agent:
- `rubygem-semantic_puppet` 0.1.2 should be in puppet-agent 1.10.x, 5.3.x, and 5.5.x -- this matches the versions for the 1.10.12, 5.3.6, and and 5.5.1 agent releases. The updated 1.0.2 version is retained for all other projects.
- `rubygem-net-ssh` 4.1.0 should be in puppet-agent 1.10.x and 5.5.x -- this matches the version for the 1.10.12 and 5.5.1 agent releases. The updated 4.2.0 version is retained for all other projects.
> (PA 2069) Restore the option to use semantic_puppet 0.1.2 and net-ssh 4.1.0

- configs/components/rubygem-ffi.rb
Also removes alternate versions, since agent 1.10.x no longer needs an
older release.
> (PA-2068) Update rubygem-ffi to latest version

- configs/platforms/fedora-26-x86_64.rb
- configs/platforms/fedora-27-x86_64.rb
- configs/projects/agent-runtime-1.10.x.rb
- configs/projects/agent-runtime-5.3.x.rb
- configs/projects/agent-runtime-5.5.x.rb
CPR-391 has updated repositories consuming runtime projects so that they
no longer require the `f` prefix on Fedora platform names, but only in
master branches. This change adds new platform definitions for Fedora 26
and 27 without the prefix, but retains the old definitions, since
earlier branches of puppet-agent still require them.
> (CPR-391) Add alternate Fedora 26, 27 platforms

- configs/projects/agent-runtime-5.5.x.rb
We won't be keeping the `f` prefix for the fedora 28 platform in
puppet-agent 5.5.x -- this restricts the workaround in that project to
Fedora 26 and 27 only.
> (CPR-391) Remove fedora `f` for agent runtime 5.5.x

- Gemfile
This update contains a [bugfix](https://github.com/puppetlabs/vanagon/pull/572) for `publish_yaml_settings`
> (maint) Update default vanagon version

- configs/components/_base-ruby-augeas.rb
- configs/components/_base-ruby.rb
- configs/components/augeas.rb
- configs/components/boost.rb
- configs/components/libedit.rb
- configs/components/openssl.rb
- configs/components/ruby-2.4.4.rb
- configs/components/runtime-agent.rb
- configs/components/yaml-cpp.rb
- configs/platforms/aix-6.1-ppc.rb
- configs/platforms/aix-7.1-ppc.rb
- configs/projects/_shared-agent-components.rb
- configs/projects/_shared-agent-settings.rb
- configs/projects/agent-runtime-master.rb
- resources/patches/boost/0001-fix-build-for-solaris.patch
- resources/patches/boost/Fix-bootstrap-build-for-solaris-10.patch
- resources/patches/boost/boost-aarch64-flags.patch
- resources/patches/boost/no-fionbio.patch
- resources/patches/boost/solaris-10-boost-build.patch
- resources/patches/boost/solaris-aix-boost-filesystem-unique-path.patch
Changes to support builds on AIX:
- AIX builds now fetch from artifactory, not OSMIRROR
- AIX builds now only specify build requirements in the platform file
> (PA-2055) Add vendored yaml-cpp and boost

- configs/projects/bolt-runtime.rb
Bolt started shipping R10k, which requires several extra gems.
gettext-setup is the only one that's a common dependency here so far.
> (BOLT-720) Include common R10k dependency for bolt-runtime

- Gemfile
Pin to latest gem release of packaging rather than following the 1.0.x
dev branch.
> (maint) Only use gem releases of packaging

- configs/components/_base-ruby-augeas.rb
- configs/components/_base-ruby.rb
- configs/components/augeas.rb
- configs/components/boost.rb
- configs/components/libedit.rb
- configs/components/openssl.rb
- configs/components/ruby-2.4.4.rb
- configs/components/runtime-agent.rb
- configs/components/yaml-cpp.rb
- configs/platforms/aix-6.1-ppc.rb
- configs/platforms/aix-7.1-ppc.rb
- configs/projects/_shared-agent-components.rb
- configs/projects/_shared-agent-settings.rb
- configs/projects/agent-runtime-master.rb
- notes/README.md
- notes/macos/boost.md
- notes/solaris/linker-for-boost.md
- resources/files/boost/macos_rpath_install_names.erb
- resources/patches/boost/0001-fix-build-for-solaris.patch
- resources/patches/boost/Fix-bootstrap-build-for-solaris-10.patch
- resources/patches/boost/boost-aarch64-flags.patch
- resources/patches/boost/force-SONAME-option-for-solaris.patch
- resources/patches/boost/no-fionbio.patch
- resources/patches/boost/solaris-10-boost-build.patch
- resources/patches/boost/solaris-aix-boost-filesystem-unique-path.patch
- resources/patches/boost/windows-thread-declare-do_try_join_until-as-inline.patch
This commit 'reverts the revert' of the original vendored yaml-cpp/boost and updates the windows build of boost to (hopefully) correctly work with Leatherman.
> (PA-2055) Re-add boost/yaml-cpp, fix windows builds of boost

- configs/projects/_shared-agent-settings.rb
These don't contain anything useful and can easily break build systems consuming the runtime tarballs.
> (maint) Exclude logdir and piddir from agent tarballs

- resources/files/ruby_244/rbconfig/rbconfig-244-s390x-linux-gnu.rb
Prior to this commit, running any `puppet foo` subcommand on s390x would fail with
`/opt/puppetlabs/puppet/lib/ruby/2.4.0/s390x-linux/rbconfig.rb:7:in <module:RbConfig>:
ruby lib version (2.4.4) doesn't match executable version (2.4.4) (RuntimeError)`
This fixes the one-character typo and makes the version string match.
> (PA-2126) Fix typo in ruby version string

- configs/components/libicu.rb
- configs/components/runtime-client-tools.rb
- configs/projects/_shared-client-tools-runtime.rb
- configs/projects/client-tools-runtime-irving.rb
- resources/files/libicu/curr_reslocal.mk
- resources/files/libicu/lang_reslocal.mk
- resources/files/libicu/locales_reslocal.mk
- resources/files/libicu/region_reslocal.mk
- resources/files/libicu/unit_reslocal.mk
- resources/files/libicu/zone_reslocal.mk
Adds the pe-client-tools-runtime, for use in future PE releases.
> (PE-24779) Add pe-client-tools-runtime

- configs/components/runtime-agent.rb
- configs/platforms/sles-15-x86_64.rb
This platform uses the default OS distro toolchain and does not rely on
pl-build-tools, the runtime-agent component is a no-op.
> (BUILD-156) Add runtime support for sles-15-x86_64

- configs/projects/agent-runtime-master.rb
This platform uses the default OS distro toolchain and does not rely on
pl-build-tools.
> (BUILD-156) Add agent-runtime-master support for sles-15-x86_64

- configs/projects/_shared-agent-settings.rb
- configs/projects/agent-runtime-1.10.x.rb
- configs/projects/agent-runtime-5.3.x.rb
- configs/projects/agent-runtime-5.5.x.rb
These changes support https://github.com/puppetlabs/puppet-agent/pull/1517 -- a full description of the pathing updates in this PR can be found in the corresponding puppet-specifications PR [here](https://github.com/puppetlabs/puppet-specifications/pull/123), but in short, install paths are changed as follows:
- The base of the ruby installation has moved from `C:\Program Files\Puppet Labs\Puppet\sys\ruby` to `C:\Program Files\Puppet Labs\Puppet\puppet`
- Tools (like `elevate.exe`) have similarly moved from `C:\Program Files\Puppet Labs\Puppet\sys\tools` to `C:\Program Files\Puppet Labs\Puppet\puppet\bin`
- The agent components facter, hiera, and pxp-agent no longer have their own dedicated install locations at `C:\Program Files\Puppet Labs\Puppet\<component-name>`; they are installed to …
> (PA-1923) Update Windows agent install paths to more closely match equivalent *nix paths

- configs/components/openssl-1.0.2.rb
- configs/components/openssl-1.1.0.rb
- configs/components/runtime-agent.rb
(Changes to regexes around PPC plaforms erroneously altered the libdir
for OpenSSL builds on ubuntu-16.04-ppc64el and the runtime script)
These changes seem to rectify the `inspect` diffs between the working and non-working tags while preserving the new changes -- I'll run this through the agent pipeline for all ppc platforms before requesting a merge, though.
> (maint) Fix OpenSSL and runtime scripts for Ubuntu 16.04 on power

- configs/platforms/el-7-ppc64.rb
Add a note to the platform config for community-supported OS platforms.
> (maint) Mark platforms which are community-supported

- configs/components/augeas.rb
- configs/projects/_shared-agent-components.rb
- configs/projects/pdk-runtime.rb
We were previously not building the ruby selinux bindings on the redhatfips
platform. We should do that.
> (PA-2243) Add redhatfips to the list of platforms for selinux

- configs/components/curl.rb
I've updated the version for curl, and tested locally on several OSes, but would need help on how to test all the combinations of runtime version vs platforms.
I know that I can add comments like "Jenkins please ...", but is this the correct way in testing all combinations?
> PA-2124 Updated curl version to 7.61.1

- configs/components/rubygem-net-ssh.rb
- configs/projects/bolt-runtime.rb
Upgrading primarily to enable ed25519 support in packaging.
> (BOLT-380) Update net-ssh to 5.0.2 for bolt-runtime

- configs/components/_base-ruby-selinux.rb
- configs/components/boost.rb
- configs/components/ruby-2.4.5.rb
- configs/components/runtime-agent.rb
- configs/components/yaml-cpp.rb
- configs/platforms/el-8-x86_64.rb
- configs/projects/_shared-agent-settings.rb
- configs/projects/agent-runtime-5.5.x.rb
This needs to be tested alongside puppet-agent.
Waiting for the release of beaker-hostgenerator containing redhat-8.
> (PA-2325) Add Redhat 8 to puppet-runtime

- configs/platforms/osx-10.10-x86_64.rb
- configs/platforms/osx-10.11-x86_64.rb
- configs/platforms/osx-10.14-x86_64.rb
- configs/projects/agent-runtime-5.5.x.rb
Reverts puppetlabs/puppet-runtime#128
CI for puppet-agent 1.10.x depends on macOS 10.10 and 10.11, and we haven't committed to removing it there. We'll need to keep these platforms in this repo until the puppet-agent 1.10.x branch is retired.
> Revert "(PA-2334) do not use root for homebrew on OSX"

- configs/platforms/osx-10.13-x86_64.rb
- configs/platforms/osx-10.14-x86_64.rb
- configs/projects/agent-runtime-5.5.x.rb
This reverts commit 1b752d605dc8021c931fc956997a136d6e338db7, reversing
changes made to 933c99524d929361b5a88b86de19a9146de1042d.
The changes to the projects and platforms here are fine, but the removal
of OS X 10.10 and 10.11 should happen separately or not at all.
I'm going to run a few tests on all the macOS platforms to make sure everything's still okay before I remove the do not merge label.
> Revert "Merge pull request #131 from puppetlabs/revert-128-master"

- configs/components/augeas.rb
- configs/projects/agent-runtime-5.5.x.rb
- resources/patches/augeas/augeas-1.11.0-gnulib-pthread-in-use.patch
> PA-2364 bump augeas to 1.11.0

- configs/components/runtime-bolt.rb
As part of the work packaging and shipping puppet-bolt for fedora we use build tools that exist in the newer distros.
> (BOLT-978) Dont use pl-build-tools for bolt-runtime on fedora 29

- configs/projects/agent-runtime-6.0.x.rb
Suite was passing for 5.5.x
I've run the adhoc pipeline here and everything seems ok(except ubuntu14.04 which i removed becasue artifactory issues)
https://jenkins-master-prod-1.delivery.puppetlabs.net/view/Adhoc/job/platform_puppet-agent-extra_puppet-agent-integration-suite_adhoc-ad_hoc/528/
> (PA-2364) bump augeas to 1.11.0 for agent-runtime-6.0.x

- configs/components/rubygem-net-ssh.rb
- configs/projects/bolt-runtime.rb
Upgrading to support using ecdsa keys with bolt.
> (BOLT-920) Update net-ssh to 5.1.0 for bolt-runtime

- configs/components/rubygem-minitar.rb
- configs/projects/bolt-runtime.rb
Bolt shares a dependency with puppet-runtime on the minitar gem. In order to build pe-bolt-server we were also adding the newer version in the bolt-vanagon project. This resulted in puppet-bolt and pe-bolt-server packages having different minitar versions. This commit allows us to specify the latest minitar version in bolt-runtime without affecting other projects that may use the older gem.
> (maint) Bump minitar version for bolt runtime

- configs/projects/agent-runtime-master.rb
5.5.x pipline was passing
run the adhoc for master and everything seems to be ok besides some ubuntu artifactory issues
https://jenkins-master-prod-1.delivery.puppetlabs.net/view/Adhoc/job/platform_puppet-agent-extra_puppet-agent-integration-suite_adhoc-ad_hoc/529/
> (PA-2364) bump augeas to 1.11.0 for agent-runtime-master

- configs/components/ruby-2.4.5.rb
- configs/components/ruby-2.5.3.rb
- resources/patches/ruby_245/cve-2019-8320_to_8325_r2.4.patch
- resources/patches/ruby_253/cve-2019-8320_to_8325_r2.5.patch
agent-runtime-5.5.x: http://builds.delivery.puppetlabs.net/puppet-runtime/cff354e70c1225093341a0f23285613f04fb09c5/artifacts/?C=M&O=D
agent-runtime-6.0.x: http://builds.delivery.puppetlabs.net/puppet-runtime/7b45b7528fb03132b2c7e5b3e5158659e07639ec/artifacts/?C=M&O=D
PA ad-hoc: https://jenkins-master-prod-1.delivery.puppetlabs.net/view/Adhoc/job/platform_puppet-agent-extra_puppet-agent-integration-suite_adhoc-ad_hoc/564/
built locally bolt-runtime and pdk-runtime.
> (maint) Mar 2019 CVE patch to ruby 2.4.5 and 2.5.3

- configs/components/rubygem-net-ssh.rb
- configs/projects/bolt-runtime.rb
Upgrading to pull in updates that will improve host-key-check option for bolt.
> (BOLT-495) Update net-ssh to 5.2.0

- configs/components/runtime-bolt.rb
Do not use pl-build-tools to build bolt-runtime on el-8 platforms.
> (RE-12163) Use native build tools for el-8 bolt-runtime

- configs/components/runtime-pe-installer.rb
Update libdir path to /usr/lib64 on el-8 in pe-installer runtime
> PE-26080 Update directory path for el-8 in pe-installer runtime

- configs/platforms/cisco-wrlinux-5-x86_64.rb
- configs/platforms/cisco-wrlinux-7-x86_64.rb
This PR fixes the intermediate build failures for wrlinux-5.
Removing pl-gcc should not impact our build process because it gets installed as a dependency for pl-cmake.
> (maint) remove pl-gcc from wrlinux-5 & 7

- configs/platforms/cisco-wrlinux-7-x86_64.rb
It seems like pl-cmake for wrlinux-7 does not have a dependency on pl-gcc. 
This PR re-enables pl-gcc for wrlinux-7
> (maint) enable pl-gcc on wrlinux-7

- configs/projects/agent-runtime-6.0.x.rb
The original PR ( https://github.com/puppetlabs/puppet-runtime/pull/154 )to replace trollop missed removing the dependency from puppet-agent6.x. This removes it.
> (BOLT-1026) Replace trollop with optimist for hiera-eyaml 0.3.x

- configs/projects/bolt-runtime.rb
Including selinux will help support using bolt's puppet on localhost instead of relying on agent.
> (BOLT-1244) Include SELinux in bolt-runtime

- configs/projects/_shared-agent-components.rb
- configs/projects/agent-runtime-1.10.x.rb
According to PA-1129 / PUP-5756 we dont need this gem anymore. This commit removes it from shared agent components and only adds it to 1.10.x runtime.
> (maint) Remove win32-eventlog from modern agents

- configs/components/openssl-1.0.2.rb
This will address some CVE fixes. See
https://www.openssl.org/news/vulnerabilities.html.
> (RE-12368) Update OpenSSL 1.0.2 to OpenSSL 1.0.2r

- configs/components/rubygem-winrm.rb
- WinRM gem 2.3.2 is necessary to enable Kerberos. Earlier versions of
the gem contained a bug with decrypting Kerberos payloads that would
result in decryption failures / corruptions about 10% of the time.
10% of the time is enough to make Kerberos completely unusable.
See https://github.com/WinRb/WinRM/pull/302 for more info
Artifact is already published in Artifactory at:
https://artifactory.delivery.puppetlabs.net/artifactory/webapp/#/artifacts/browse/tree/General/rubygems__remote-cache/gems/winrm-2.3.2.gem
> (BOLT-126) Upgrade winrm gem to 2.3.2

- configs/projects/_shared-pe-bolt-server.rb
- configs/projects/pe-bolt-server-runtime-2019.1.x.rb
- configs/projects/pe-bolt-server-runtime-2019.2.x.rb
Extracts configuration from the 2019.0.x pe-bolt-server project that is
shared between all pe-bolt-server branches and moves it to a shared
_pe_bolt_server_shared component; Reuses that shared configuration in
two new projects for PE 2019.1.x (kearney) and 2019.2.x (lovejoy).
> (ORCH-2296) Create pe-bolt-server 2019.{1,2}.x projects

- configs/projects/bolt-runtime.rb
The PR to transition the gems included in bolt-vanagon to bolt-runtime missed optionally including these gems on non-windows platforms.
> (ORCH-2296) Include net-ssh optional dependencies for *nix

- configs/components/ruby-2.4.5.rb
- configs/components/ruby-2.5.3.rb
- resources/patches/ruby_245/windows_nocodepage_utf8_fallback_r2.4.patch
- resources/patches/ruby_253/windows_nocodepage_utf8_fallback_r2.5.patch
This is to deal specifically with setting the Region to Arabic which
sets the codepage to 720. This codepage isn't recognises by Ruby which
causes it to fail during initialisation when setting up LOCALE.
So patch Ruby for Windows Only to Fallback to UTF for THIS ERROR ONLY.
This also applies to any other languages that use a codepage not
recognised by Ruby.
> (PA-2191) winruby UTF8 Fallback for no CodePage

- configs/projects/client-tools-runtime-lovejoy.rb
The lovejoy runtime is currently the same as for kearney.
> (CT-64) Build a pe-client-tools runtime for lovejoy

- configs/components/git.rb
- configs/components/runtime-pdk.rb
Only a couple of minor changes needed to get pdk-runtime building on RHEL 8
* Remove dh-autoreconf from the git build dependencies
* Don't use pl-build-tools
> (PDK-1358) Build pdk-runtime for el-8-x86_64

- configs/components/curl.rb
See https://curl.haxx.se/changes.html for a full list of addressed
items in 7.65.1.
> (ct-66) Update curl to 7.65.1 to address CVEs

- configs/components/_base-ruby-selinux.rb
- configs/components/boost.rb
- configs/components/ruby-2.4.5.rb
- configs/components/runtime-agent.rb
- configs/components/runtime-bolt.rb
- configs/components/yaml-cpp.rb
- configs/platforms/fedora-30-x86_64.rb
- configs/projects/agent-runtime-5.5.x.rb
This commit adds support for Fedora 30 (without pl-build-tools)
> (PA-2677) Add Fedora 30 (amd64) to puppet-runtime

- configs/projects/pdk-runtime.rb
There is currently no reason to cap the puppet version for Ruby 2.5.x, we might as well let packaging resolve it to the latest. This setting is only used in the downstream `pdk-vanagon` repo.
> (MAINT) Remove PDK restriction on latest puppet for Ruby 2.5

- configs/components/rubygem-deep_merge.rb
- configs/components/rubygem-gettext.rb
- configs/components/rubygem-public_suffix.rb
- configs/components/rubygem-puppet-resource_api.rb
- configs/components/rubygem-puppet.rb
- configs/components/rubygem-ruby_smb.rb
- configs/projects/_shared-pe-bolt-server.rb
- configs/projects/bolt-runtime.rb
Update gems that ship with bolt system packages. The most important update in this commit is the the latest puppet_resource-api which contains important bug fixes for supporting device modules.
> (maint) Update gems that ship with bolt

- configs/projects/_shared-agent-settings.rb
on new systemd based systems following warning is thrown when the system boots:
``` 
[/usr/lib/tmpfiles.d/puppet-agent.conf:1] Line references path below legacy directory /var/run/, updating /var/run/puppetlabs → /run/puppetlabs; please update the tmpfiles.d/ drop-in file accordingly.
```
This PR updates the piddir to be /run if the directory exists.
more info here: https://github.com/systemd/systemd/commit/a2d1fb882c4308bc10362d971f333c5031d60069
> (PA-2479) use /run for pid if exists

- configs/projects/_shared-agent-settings.rb
Reverts puppetlabs/puppet-runtime#189
Reverting this to further investigate the impact.
> Revert "(PA-2479) use /run for pid if exists"

- configs/projects/pe-installer-runtime.rb
This commit updates the net-ssh gem dependency in pe-installer-runtime
from 4.2.0 to the more current 5.2.0. This change is motivated in
particular by the fact that this version update should allow the
installer's Bolt installation to respect known_hosts files as expected.
> (maint) Update net-ssh dependency in pe-installer-runtime

- configs/projects/pe-installer-runtime.rb
This commit updates the dependencies for pe-installer-runtime, so that
net-ssh is able to properly handle the new default format for private
keys shipped in the version of OpenSSH that comes as the default on el8
platforms. This is (again, unfortunately) for our version of Bolt, which
isn't installed as a package and as such does not come with some of the
handy dependencies that should be present.
> (maint) Update net-ssh dependencies for pe-installer-runtime

- configs/components/rubygem-aws-eventstream.rb
- configs/components/rubygem-aws-partitions.rb
- configs/components/rubygem-aws-sdk-core.rb
- configs/components/rubygem-aws-sdk-ec2.rb
- configs/components/rubygem-aws-sigv4.rb
- configs/components/rubygem-jmespath.rb
- configs/projects/_shared-pe-bolt-server.rb
- configs/projects/bolt-runtime.rb
We now depend on the aws-sdk-ec2 gem, as of
https://github.com/puppetlabs/bolt/pull/1073, which requires adding it
and it's dependencies to the bolt-runtime and pe-bolt-server-runtime
> (maint) Add aws-sdk-ec2 gem to bolt projects

- configs/components/runtime-pdk.rb
Changes this conditional so that we don't have to change it again for future fedora or rhel releases
https://jenkins-master-prod-1.delivery.puppetlabs.net/view/puppet-runtime/view/pdk-runtime/job/platform_pdk-runtime_runtime-vanagon-packaging_master/BUILD_TARGET=fedora-30-x86_64,SLAVE_LABEL=worker/95/console
> (PDK-1397) Build pdk-runtime on fedora 30

- configs/components/puppet-ca-bundle.rb
Platform additions for: el8, debian 10 and ubuntu 18
> (PA-2775) puppet-cacerts Java keystore platform additions

- configs/platforms/ubuntu-18.04-amd64.rb
This adds open jdk 11 that is needed to use java ca ceterificates using keytool
> (maint) Added openjdk 11 for ubuntu 18.04

- azure-pipelines.yml
- Don't rely on defaults for Lint-Dockerfile as they will be removed.
Instead, specify all explicitly.
This further standardizes the YAML
> (maint) Specify all Docker lints as data for Azure

- configs/components/ruby-2.4.5.rb
- configs/components/ruby-2.5.3.rb
- resources/patches/ruby_245/net_http_eof_14972.patch
- resources/patches/ruby_253/net_http_eof_14972.patch
Net::HTTP has a bug where it will silently ignore EOF if it downloads
fewer than <Content-Length> bytes[1]. Patch ruby 2.4 and 2.5 on all
platforms. This is the same as the upstream PR[2].
[1] https://bugs.ruby-lang.org/issues/14972
[2] https://github.com/ruby/ruby/pull/2074
> (PA-2849) Raise EOFError if less than Content-Length bytes downloaded

- configs/components/_base-ruby-augeas.rb
ruby-augeas has a filename mismatch between what it's looking for in Artifactory and the actual filename that it pulls from upstream (actual filename has .tgz extension, it's trying to pull .tar.gz from Artifactory, but it doesn't exist)
```
Attempting to fetch from mirror URL "https://artifactory.delivery.puppetlabs.net/artifactory/generic/buildsources/ruby-augeas-0.5.0.tar.gz"
--
Downloading file 'ruby-augeas-0.5.0.tar.gz' from url 'https://artifactory.delivery.puppetlabs.net/artifactory/generic/buildsources/ruby-augeas-0.5.0.tar.gz'
Unable to retrieve mirror URL "https://artifactory.delivery.puppetlabs.net/artifactory/generic/buildsources/ruby-augeas-0.5.0.tar.gz"
Attempting to fetch from canonical URL "http://download.augeas.net/ruby/ruby-augeas-0.5.0.tgz"
Downloading file …
```
> (PA-2860) Fix ruby-augeas Artifactory mirror URL

- configs/projects/pe-installer-runtime.rb
This pr links FIPS boxes to use system openssl in contrast to the binaries that ship with puppet.
> (PE-26585) Add logic for using correct openssl for FIPS

- configs/components/rubygem-minitar.rb
- configs/projects/_shared-pe-bolt-server.rb
- configs/projects/bolt-runtime.rb
We can use the new options hash in minitar 0.9 to set `fsync=false`which should speed things up for folks
> (PUP-10013) Update minitar to 0.9

- configs/components/rubygem-gettext-setup.rb
This commit updates the `gettext_setup` gem which is shared by multiple runtime projects.
> (packaging) Update gettext_setup gem across shared runtimes

- docker/Makefile
- Need a bundle update to be able to pull the pupperware spec_helper
(this primarily impacts local dev)
> (maint) Make sure Docker test bundle is fresh

- configs/components/rubygem-thor.rb
- configs/projects/agent-runtime-master.rb
Thor gem is require by facter-ng.
> (FACT-2027) Added thor as a dependency for agent-runtime

- configs/projects/_shared-client-tools-runtime.rb
FIPS packages are required to use the system openssl package for SSL
operations, so this commit removes the vendored version in the client-tools
FIPS package
> (PE-27431) Do not build openssl on fips for client tools runtime

- configs/components/rubygem-hocon.rb
https://github.com/puppetlabs/ruby-hocon/pull/115
removed spec shipping for hocon gem so this
workaround is not needed anymore.
> (maint) remove spec deletion on hocon gem install

- configs/components/_base-ruby-selinux.rb
- configs/components/augeas.rb
- configs/components/boost.rb
- configs/components/curl.rb
- configs/components/ruby-2.4.9.rb
- configs/components/ruby-2.5.7.rb
- configs/components/yaml-cpp.rb
- configs/projects/_shared-agent-settings.rb
Harden Linux ELF binaries by compiling with PIE (Position Independent Executables) support, stack canary and full RELRO.
We only do this on platforms that use their default OS toolchain since pl-gcc versions are too old to support these flags.
Dependent on https://github.com/puppetlabs/vanagon/pull/629.
(something similar will need to be done for puppet-agent as well)
> (PA-2986) Update GCC compiler/linker flags

- configs/components/rubygem-hocon.rb
- This release adds support for specifying lists with environment
variables, which was necessary to support parameterizing the
whitelist from bolt-server.conf in the Bolt docker container
The pe-bolt-vanagon repo relies on loading the puppet-runtime
configuration and hence uses this component definition for the
hocon inclusion
Changelog for the diff between 1.2.6 and 1.3.0: https://github.com/puppetlabs/ruby-hocon/compare/1.2.6...1.3.0
> (maint) bump hocon gem to 1.3.0

- configs/components/_base-ruby-selinux.rb
- configs/components/augeas.rb
- configs/components/boost.rb
- configs/components/ruby-2.4.9.rb
- configs/components/ruby-2.5.7.rb
- configs/components/runtime-agent.rb
- configs/components/runtime-bolt.rb
- configs/components/yaml-cpp.rb
- configs/platforms/fedora-31-x86_64.rb
- configs/projects/_shared-agent-settings.rb
- configs/projects/agent-runtime-5.5.x.rb
Also adjusts the various regexes that are used to configure things like
pl-gcc vs gcc and extracted the Fedora matching into a more verbose
check that should require less ongoing maintenance.
Tested by building `pdk-runtime`, `bolt-runtime`, and
`agent-runtime-5.5.x`.
> (PDK-1546) Add Fedora 31 to platform configs

- configs/platforms/solaris-11-i386.rb
- configs/platforms/solaris-11-sparc.rb
This reverts commit 88e270dd04d1db9dfc5fa062cc84f29781bd46c2 as
solarisstudio publisher is already removed in vmpooler image
> Revert "(maint) remove solarisstudio publisher"

- configs/components/rubygem-aws-partitions.rb
- configs/components/rubygem-aws-sdk-core.rb
- configs/components/rubygem-aws-sdk-ec2.rb
- configs/components/rubygem-hiera-eyaml.rb
- configs/components/rubygem-puppet.rb
- configs/components/rubygem-rubyzip.rb
- configs/components/rubygem-winrm-fs.rb
This commit updates the gems shipped with bolt/bolt-server. Notably it pulls in puppet6.11.0 which will be minimum puppet version for bolt gem moving forward.
> (packaging) Update bolt/bolt-server component gems

- configs/components/rubygem-gettext.rb
- configs/components/rubygem-text.rb
```diff
--- a.txt	2019-11-20 15:35:07.000000000 +0200
+++ b.txt	2019-11-20 15:35:15.000000000 +0200
@@ -2198,7 +2198,7 @@
"conflicts": [
],
-    "environment": "GEM_HOME=/opt/puppetlabs/puppet/lib/ruby/vendor_gems RUBYLIB=/opt/puppetlabs/puppet/lib/ruby/vendor_ruby:$(RUBYLIB)",
+    "environment": "GEM_HOME=/opt/puppetlabs/puppet/lib/ruby/gems/2.4.0 RUBYLIB=/opt/puppetlabs/puppet/lib/ruby/vendor_ruby:$(RUBYLIB)",
"sources": [
],
@@ -2468,7 +2468,7 @@
"conflicts": [
],
-    "environment": "GEM_HOME=/opt/puppetlabs/puppet/lib/ruby/vendor_gems RUBYLIB=/opt/puppetlabs/puppet/lib/ruby/vendor_ruby:$(RUBYLIB)",
+    "environment": "GEM_HOME=/opt/puppetlabs/puppet/lib/ruby/gems/2.4.0 RUBYLIB=/opt/puppetlabs/puppet/lib/ruby/vendor_ruby:$(RUBYLIB)",
"sources": [
],
```
> (PA-3005) move gettext and text to shared gem home

- configs/components/_base-ruby-selinux.rb
- configs/platforms/debian-10-amd64.rb
- configs/platforms/debian-8-amd64.rb
- configs/platforms/debian-8-i386.rb
- configs/platforms/debian-9-amd64.rb
- configs/platforms/debian-9-i386.rb
- configs/platforms/ubuntu-16.04-amd64.rb
- configs/platforms/ubuntu-16.04-i386.rb
- configs/platforms/ubuntu-16.04-ppc64el.rb
- configs/platforms/ubuntu-18.04-amd64.rb
- configs/projects/_shared-agent-components.rb
Since selinux is also available on Debian and Ubuntu, we can build the `ruby-selinux` component for these platforms as well.
To build the selinux library we need the SELinux development headers (`libselinux1-dev`) and `swig`, which is a build dependency.
The extra added/removed lines are from me ordering the platform package names in alphabetical order.
> (PA-2985) Build ruby-selinux for Debian and Ubuntu

- configs/components/rubygem-puppet-strings.rb
- configs/components/rubygem-rgen.rb
- configs/components/rubygem-yard.rb
- configs/projects/bolt-runtime.rb
These are needed for `bolt plan show`.
> Add puppet-strings and its dependencies to bolt-runtime

- Gemfile
- configs/components/rubygem-ffi.rb
- configs/platforms/solaris-10-i386.rb
- configs/platforms/solaris-10-sparc.rb
- configs/platforms/solaris-11-i386.rb
- configs/platforms/solaris-11-sparc.rb
- configs/projects/_shared-agent-components.rb
Add support for building the FFI gem on cross-compiled Solaris platforms (i386/x86_64 to sparc).
This can be achieved by monkey-patching rubygems and using a custom rbconfig to bypass version checks. This is necessary because in cross-compile situations we install gems with the system ruby which is usually an older version.
I tested this by building the runtime, then building the agent with this runtime, then explicitly requiring `ffi` in a `irb` session on `solaris-(10|11)-sparc`.
~~Also in scope of this PR would be to add support for x86 Solaris which I haven't tackled yet, but should be trivial.~~ Support for x86 was added.
Supersedes https://github.com/puppetlabs/puppet-runtime/pull/251.
> (FACT-1946) Build ffi gem on Solaris

- docker/puppet-runtime/Dockerfile
- Disable wget progress bar
- Reduce Dockerfile build steps to 12, and move steps that can't be cached later in the Dockerfile
> (maint) Improve Dockerfile organization / build caching

- configs/components/rubygem-CFPropertyList.rb
- configs/projects/_shared-agent-components.rb
CFProperty List gem will be installer by puppet-runtime, and CFProperty List
component will be removed from puppet-agent.
> (PA-2780) CFProperty List gem in wrong directory

- configs/projects/_shared-client-tools-runtime.rb
This reverts commit 9cdc6b387e651cef73fc98e87476ebabe329d5d3, reversing
changes made to 71291eefead882d17fb6b57860b785dd5db8353f. Openssl 1.1.1 is not compatible with some dependencies in the puppet-code rust project.
> Revert "Merge pull request #265 from sarameisburger/maint"

- configs/components/boost.rb
- configs/components/openssl-1.1.1.rb
- configs/components/runtime-agent.rb
- configs/platforms/aix-7.1-ppc.rb
- configs/projects/_shared-agent-settings.rb
- configs/projects/agent-runtime-5.5.x.rb
This reverts commit ~888cce2f06326b40f5895d7b46c819689e1500d5.~ 71291eefead882d17fb6b57860b785dd5db8353f
the openssl update has caused some issues in PE smoke tests and we need to pull it out until we can figure out how to fix it/the best path forward
/cc @ciprianbadescu @mihaibuzgau @shrug @joshcooper @melissa
> Revert "(PUP-10166) upgrade openssl version"

- configs/components/openssl-1.1.1.rb
- configs/projects/agent-runtime-5.5.x.rb
Because the newly added component openssl-lib was not included in all the projects, vanagon tried to install it using the default package manager:
```
09:31:18 Executing 'yum install --assumeyes openssl-lib ' on 'root@unfunny-root.delivery.puppetlabs.net'
09:31:18 Warning: Permanently added 'unfunny-root.delivery.puppetlabs.net,10.16.119.196' (ECDSA) to the list of known hosts.
09:31:18 Loaded plugins: fastestmirror
09:31:18 Loading mirror speeds from cached hostfile
09:31:18 No package openssl-lib available.
```
This PR confines openssl-lib only to the puppet-agent-5.5.x runtime
> (maint) provide openssl-lib only for 5.5.x agent

- configs/components/_base-ruby-selinux.rb
- configs/platforms/el-8-x86_64.rb
Until now we were using a really old version of `selinuxswig_ruby.i,selinuxswig.i` for rubyselinux.
This causes the following exception on CentOS8 by requiring selinux:
```
[root@royal-labour ~]# /opt/puppetlabs/puppet/bin/ruby -e 'require "selinux"'
Traceback (most recent call last):
2: from -e:1:in `<main>'
1: from /opt/puppetlabs/puppet/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/opt/puppetlabs/puppet/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/2.5.0/x86_64-linux/selinux.so: undefined symbol: rpm_execcon - /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/2.5.0/x86_64-linux/selinux.so (LoadError)
```
This PR updates the Ruby selinuxswig to the lastest available for newer platforms while leaving the …
> (PA-3067) use 2.9 selinux for non-pl-build-tools platforms

- configs/components/_base-ruby-selinux.rb
- resources/patches/ruby-selinux/selinux-29-function.patch
libselinux(-devel) was upgraded in our EL mirrors (from 2.8 to 2.9),
which made a new function appear: `security_reject_unknown`.
When requiring the `selinux` library with an older version of
libselinux, the following error appears:
```
undefined symbol: security_reject_unknown - ... selinux.so (LoadError)
```
To ensure our Ruby bindings work with older versions of libselinux, we
omit exporting the newer function to the Ruby library.
> (maint) Ignore symbol not in libselinux 2.9

- configs/projects/client-tools-runtime-master.rb
- configs/projects/pe-bolt-server-runtime-master.rb
This commit adds two new projects: client-tools-runtime-master and
pe-bolt-server-runtime-master.
These new projects will support the new master branch strategy for PE
> (PE-28158) Add client-tools/bolt-server master projects

- configs/components/ruby-2.1.9.rb
- resources/patches/ruby_219/cve-2019-15845.patch
- resources/patches/ruby_219/cve-2019-16201.patch
- resources/patches/ruby_219/cve-2019-16254.patch
- resources/patches/ruby_219/cve-2019-16255.patch
Four CVEs were announced in October affecting Ruby 2.1
(https://www.ruby-lang.org/en/security/). This takes the patches from
the Debian Jessie source package for ruby 2.1.5-2+deb8u8.
> (maint) Patch ruby 2.1.9 to address Oct 2019 CVEs

- configs/components/openssl-1.1.1-fips.rb
as on 5.5.x we still deliver openssl-lib-1.0.2, we need to make sure they
are compiled before openssl-1.1.1-fips
> (maint) add dependency to openssl-lib-1.0.2

- configs/components/rubygem-ffi.rb
- configs/platforms/solaris-10-sparc.rb
- configs/platforms/solaris-11-sparc.rb
Apparently we don't need `libffi` when building the `ffi` gem. The gem will also build `libffi` for us which makes things simpler in the long run.
We still need to patch rubygems to think we're on the destination architecture.
Still testing this...
> (maint) Fix rubygem-ffi on cross compiled builds

- configs/components/ruby-2.5.7.rb
- resources/patches/ruby_25/windows_env_block_size_limit.patch
Apply ruby/ruby@490fbc4 (which is only in ruby 2.7 and higher) to fix an issue with large environment blocks on Windows.
> (PA-3113) Patch ruby to allow large environments on Windows

- configs/components/runtime-pe-bolt-server.rb
- configs/projects/pe-bolt-server-runtime-2019.0.x.rb
- configs/projects/pe-bolt-server-runtime-2019.2.x.rb
This commit updates bolt-server to update repodata from artifactory instead of enterprise.d.p.n.
> (maint) Download build repo from artifactory for bolt-server-runtime

- configs/components/rubygem-facter.rb
> (maint) Bump facter to 4.0.13 for bolt, pe-bolt-server

- configs/components/rubygem-aws-partitions.rb
- configs/components/rubygem-aws-sdk-core.rb
- configs/components/rubygem-aws-sdk-ec2.rb
- configs/components/rubygem-aws-sigv4.rb
- configs/components/rubygem-bindata.rb
- configs/components/rubygem-cri.rb
- configs/components/rubygem-facter.rb
- configs/components/rubygem-faraday_middleware.rb
- configs/components/rubygem-puppet-resource_api.rb
- configs/components/rubygem-puppet-strings.rb
- configs/components/rubygem-puppet.rb
- configs/components/rubygem-puppet_forge.rb
- configs/components/rubygem-r10k.rb
- configs/components/rubygem-rubyzip.rb
- configs/components/rubygem-unicode-display_width.rb
This updates the version of gem dependencies of Bolt to their latest
versions. This PR is limited to gems that are only included in the Bolt
and pe-bolt-server packages.
> (packaging) Update Bolt package component gems

- configs/components/rubygem-bcrypt_pbkdf.rb
- configs/components/rubygem-ffi.rb
- configs/components/rubygem-gettext-setup.rb
- configs/components/rubygem-locale.rb
- configs/components/rubygem-multi_json.rb
This updates rubygem component versions to their latest for gems that
are shared across multiple projects.
Specifically the @puppetlabs/installer-and-management team includes:
bcrypt_pbkdf
ffi
gettext-setup
locale
multi_json
The puppet-agent package includes:
concurrent-ruby
ffi
gettext-setup
locale
multi_json
The @puppetlabs/pdk package includes:
ffi
gettext-setup
> (packaging) Bump shared rubygem component versions to latest

- configs/platforms/ubuntu-20.04-amd64.rb
this is needed since `apt-get install devscripts` updated libc to a version that is not compatible
with the version installed by default om vmpooler images.
To overcome this:
- `devscripts` package in no longer upgraded (since is already installed)
- `libc6` marked as hold to detect early packages trying to update it
This workaround should be removed when image is updated with released iso version
> (maint) remove devscripts update

- configs/components/_base-ruby.rb
Update the gsub on ruby version to handle multiple digits
z version
```
>> "2.4.10".gsub(/(\d)\.(\d)\.(\d)/, '\1.\2') #=> "2.40"
>> "2.4.10".gsub(/(\d)\.(\d)\.(\d+)/, '\1.\2') #=> "2.4"
>> "2.4.1".gsub(/(\d)\.(\d)\.(\d+)/, '\1.\2') #=> "2.4"
```
> (PA-3179) fix ruby download url

- configs/components/openssl-1.1.1.rb
Fixes segmentation fault in SSL_check_chain (CVE-2020-1967)
> (PA-3186) Bump OpenSSL to 1.1.1g

- configs/components/rubygem-net-ssh.rb
- configs/projects/_shared-pe-bolt-server.rb
- configs/projects/bolt-runtime.rb
The net-ssh gem release 6.0.2 which includes several improvements
relevant to Bolt, including support for the OpenSSH
`StrictHostKeyChecking` option, performance improvements, and
curve25519sha256 key support.
> (maint) Bump net-ssh gem to 6.0.2 for Bolt

- configs/components/rubygem-x25519.rb
- configs/projects/_shared-pe-bolt-server.rb
- configs/projects/bolt-runtime.rb
This adds the `x25519` gem as a dependency in Bolt packaging. The gem
is needed by `net-ssh` to support the `curve25519-sha256` kex algorithm.
Part of puppetlabs/bolt#733
> (packaging) Add x25519 gem to bolt-runtime, shared-pe-bolt-server

- configs/components/rubygem-x25519.rb
- configs/projects/_shared-pe-bolt-server.rb
- configs/projects/bolt-runtime.rb
Reverts puppetlabs/puppet-runtime#330
`x25519` fails to build native extensions on several platforms, including el6, debian 8, ubuntu 1604, and windows. This reverts the update to the bolt-runtime and shared-pe-bolt-server projects so we can make the appropriate changes.
> Revert "(packaging) Add x25519 gem to bolt-runtime, shared-pe-bolt-server"

- configs/components/openssl-1.0.2.rb
- configs/components/openssl-1.1.1.rb
- configs/components/openssl-lib.rb
Using the platform el-8-aarch64 openssl build target was being
incorrectly specified as linux-x86_64. Use the correct
openssl linux-aarch64 instead.
> Use linux-aarch64 openssl target on aarch64

- configs/components/openssl-1.1.1-fips.rb
- resources/patches/openssl/openssl-1.1.1-fips-patch-openssl-cnf.patch
- resources/patches/openssl/openssl-1.1.1-fips-spec-file.patch
As OpenSSL 1.1.1-fips is backported from RHEL8 to RHEL7-fips, openssl.cnf
also needs to be adapted, since on RHEL8 openssl expects backends configuration
to be generated by `update-crypto-policies`, while this tool is not available on RHEL7
With this change, the openssl algorithms configuration is done by evp_setting fips_mode.
> (PA-3223) OpenSSL 1.1.1-fips config update

- configs/components/rubygem-x25519.rb
- configs/projects/bolt-runtime.rb
This adds the `x25519` gem dependency to bolt packaging, except on
Windows platforms, 32-bit platforms, and el6.
> (maint) Add x25519 gem dependency to bolt-runtime

- configs/components/rubygem-x25519.rb
- configs/projects/bolt-runtime.rb
Reverts puppetlabs/puppet-runtime#333
This gem has fundamental issues that cause it to crash on unsupported architectures / CPUs. Because of it's unreliability, we should not ship this with Bolt.
> Revert "(maint) Add x25519 gem dependency to bolt-runtime"

- configs/components/runtime-bolt.rb
> (packaging) Build bolt-runtime on Ubuntu 20.04 without pl-build-tools

- .travis.yml
- azure-pipelines.yml
- docker/Makefile
- docker/puppet-runtime/Dockerfile
- Switches Travis to Ubuntu 20.04 builder that has Docker 19.03 pre-installed, so that removes ~30s of setup time from builds
- Enable Docker buildkit (for this project it's mostly an improvement for local caching)
- Buildkit in Travis doesn't seem to work right pulling CentOS with the `--pull` switch for `docker build`, so manually download the image prior to building (based on https://github.com/puppetlabs/puppet-agent/pull/1906 / https://github.com/puppetlabs/puppet-agent/pull/1907)
- Separate out Travis operations so that logs have timings for lint, build and test
> (maint) Enable Docker buildkit linux

- configs/components/rubygem-facter.rb
> (packaging) Bump facter to 4.0.21 for bolt, pe-bolt-server

- configs/components/rubygem-hocon.rb
This fixes corruption to internal state that happened when using the hocon gem
concurrently in multiple threads.
> (HC-105) bump hocon gem to 1.3.1

- configs/components/openssl-1.1.1-fips.rb
- resources/patches/openssl/openssl-1.1.1-fips-remove-env-check.patch
- resources/patches/openssl/openssl-1.1.1-fips-spec-file.patch
OPENSSL_FIPS env variable was used inside openssl 1.0.2 application
to throw error if openssl was not compiled in fips mode.
After move to openssl 1.1.0/1.1.1 branch (that is not supporting FIPS mode)
the check was change to dirrectly throw error if OPENSSL_FIPS is set.
After this commit, the check is removed for redhat7 vendored openssl fips
> (PA-3250) remove env check for OPENSSL_FIPS

- configs/components/rubygem-puppet.rb
This commit pulls in 6.16.0 to accomidate improvements to PAL api used by bolt for apply.
> (packaging) Update puppet to 6.16.0 for bolt/bolt-server

- configs/components/ruby-2.1.9.rb
Ruby 2.1.x does not search in subfolders for pem files.
This PR updated the location of `COMODO_RSA_Certification_Authority.pem` to the root ssl ruby folder.
> (maint) Update COMODO CA for Ruby 2.1.x

- configs/platforms/sles-15-x86_64.rb
- configs/projects/agent-runtime-5.5.x.rb
- configs/projects/agent-runtime-master.rb
Successfully built both 5.5.x and master runtimes on SLES 15.
> (PA-3006) Vendor boost and yaml-cpp on SLES 15

- configs/components/rubygem-paint.rb
- configs/projects/bolt-runtime.rb
This adds the paint rubygem that's a new dependency for Bolt to support
rainbow formatted output - see puppetlabs/bolt#1911.
> (maint) Add paint gem for rainbow output format

- configs/components/curl.rb
green master-agent runtime build:
> (PA-3266) bump curl to 7.71.0

- configs/components/rubygem-aws-eventstream.rb
- configs/components/rubygem-aws-partitions.rb
- configs/components/rubygem-aws-sdk-core.rb
- configs/components/rubygem-aws-sdk-ec2.rb
- configs/components/rubygem-aws-sigv4.rb
- configs/components/rubygem-connection_pool.rb
- configs/components/rubygem-facter.rb
- configs/components/rubygem-net-http-persistent.rb
- configs/components/rubygem-net-ssh.rb
- configs/components/rubygem-public_suffix.rb
- configs/components/rubygem-puppet-resource_api.rb
- configs/components/rubygem-r10k.rb
- configs/components/rubygem-yard.rb
- configs/projects/_shared-pe-bolt-server.rb
- configs/projects/bolt-runtime.rb
This updates gems used only by Bolt and PE Bolt Server packages to their
latest versions.
> (packaging) Bump Bolt dependencies to latest versions

- configs/projects/_shared-agent-components.rb
This commit should fix the following error on Puppet 5.5.x/Solaris 10:
```
10:14:48       Error: Failed to load Solaris implementation of the Puppet::Util::AtFork handler. Child process contract management will be unavailable, which means that agent runs executed by the puppet agent service will be killed when they attempt to restart the service.
```
> (PA-3265) add ffi component on Solaris 10

- configs/components/rubygem-ffi.rb
FFI 1.13 forced the minimum required ruby version to ~> 2.3
In order to be able to install the gem using pl-ruby(2.1.9)
we need to remove the required ruby version check
> (maint) Fix ffi install on cross-compiled

- Gemfile
- configs/components/runtime-pdk.rb
> (MAINT) Update pdk-runtime config for Ubuntu 20.04

- configs/components/rubygem-ffi.rb
We accidentally bumped ffi for Windows when merging https://github.com/puppetlabs/puppet-runtime/pull/362.
I think we only want this for the `agent-runtime-main` project, where we ship Ruby 2.7, which does not work with older versions of FFI.
> (maint) Pin back ffi on Windows

- configs/projects/_shared-agent-components.rb
- configs/projects/agent-runtime-5.5.x.rb
- configs/projects/agent-runtime-master.rb
Since the `win32-dir`,`win32-process`,`win32-security`,`win32-service` gems will no longer be used in Puppet 7, this commit moves them from the puppet runtime shared agent components to the specific branches that will continue using (5.5.x and 6.x) to avoid unnecessary packaging.
Depends on [PUP-7445](https://github.com/puppetlabs/puppet/pull/8204), [PUP-5758](https://github.com/puppetlabs/puppet/pull/8194) and [PUP-6184](https://github.com/puppetlabs/puppet/pull/8258).
> (PUP-10590) Remove win32 gems from puppet-agent dependency

- configs/components/rubygem-ffi.rb
- configs/platforms/solaris-11-sparc.rb
Previously we've been using the system libffi to build the ffi gem on Solaris 11 SPARC.
This caused all FFI calls to fail with the following message:
`[BUG] Bus Error at 0x033e66d3`
It appears that we can fix this by forcing a static build of the ffi gem native extension. To accomplish this we do the following:
- avoid installing libffi/libffi_dev during the provisioning step
- force compilation to use the GNU ld linker (the simplest way to accomplish this is to temporarily move the Solaris linker somewhere else)
- append a couple of paths to LDFLAGS so ld knows where to find system libraries
> (PA-3362) Fix ffi gem compilation on Solaris 11 SPARC

- configs/projects/agent-runtime-main.rb
Starting from Puppet 7, the httpclient gem is no longer used.
This removes the gem from the Puppet Agent main AIO
> (PA-3352) remove httpclient gem from runtime main

- configs/components/rubygem-puppet.rb
Bumps the puppet rubygem to latest 6.18.0
> (maint) Bump puppet rubygem to 6.18.0

- configs/components/boost.rb
- configs/projects/_shared-client-tools-runtime.rb
- resources/files/boost/macos_rpath_install_names.sh
passing build: https://jenkins-master-prod-1.delivery.puppetlabs.net/view/vanagon-generic-builder/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/947/
can be merged together with: https://github.com/puppetlabs/puppet-runtime/pull/376
> (CT-131) add boost to client tools runtime

- configs/components/boost.rb
- configs/projects/_shared-client-tools-runtime.rb
After adding boost component in client-tools-runtime, on el-8 boost
builds with icu backend, leading to changes of libraries to be linked
in all client tools C++ components
With this commit icu backend is disabled in order to keep the components
unchanged
> (CT-131) disable icu usage in client-tools-runtime

- configs/projects/_shared-pe-bolt-server.rb
In order to stop putting agent gems on the GEM_PATH for bolt-server, stop sharing multi_json gem.
> (PE-29990) Ship multi_json with pe-bolt-server packages

- configs/components/augeas.rb
- resources/patches/augeas/augeas-1.12.0-allow-ad-groups-in-sudoers.patch
Original commit description:
Before this commit, `/etc/sudoers` files containing AD users or groups
could not be parsed with the sudoers lens because it was containing `\\`
in said users/groups name. Running `visudo -c` shows that a sudoers file
containing these is valid so this case was added in the affected regex.
Augeas PR: https://github.com/hercules-team/augeas/pull/696
> (PA-3433) Patch augeas to allow AD groups in sudoers

- configs/platforms/aix-7.1-ppc.rb
The yum install script we download from ftp.software.ibm.com is using
command line FTP client with expect. The ftp client is in FTP active
mode by default and started to fail(timeout) in our environment.
After this commit we will patch the yum install shell script to
use FTP passive mode.
> (maint) update yum install script to use ftp passive mode

- configs/components/rubygem-puppet.rb
This commit updates the puppet gem shipped in various runtimes to version
6.19.1.
> (PE-30632) Update puppet gem version

- configs/components/openssl-1.1.1.rb
- resources/patches/openssl/openssl-1.1.1i-remove-aes-ctr-drbg-performance-improvement.patch
Performance optimisation introduced https://github.com/openssl/openssl/commit/53eb05bdf00d7237e3b12976c2ac38d68206eb13 by and https://github.com/openssl/openssl/commit/e6a80cbad28ee748830815634917efe96948f2f3
leads to crash on Solaris 10 i386 on https://github.com/openssl/openssl/blob/90cebd1b216e0a160fcfd8e0eddca47dad47c183/crypto/rand/drbg_ctr.c#L253
> (PA-3513) revert openssl performance improvement on Solaris 10 i386

- configs/platforms/aix-7.1-ppc.rb
This reverts commit 85cb880cc6a324a1bf55c427d79260bee119c7f9.
The change to ftp passive mode was added to upstream script
> Revert "(maint) update yum install script to use ftp passive mode"

- configs/components/rubygem-aws-partitions.rb
- configs/components/rubygem-aws-sdk-core.rb
- configs/components/rubygem-aws-sdk-ec2.rb
- configs/components/rubygem-erubi.rb
- configs/components/rubygem-facter.rb
- configs/components/rubygem-molinillo.rb
- configs/components/rubygem-paint.rb
- configs/components/rubygem-puppetfile-resolver.rb
Reverts puppetlabs/puppet-runtime#405
Puppetfile Resolver has a minimum ruby version of 2.5.3, which requires us to use an updated CI environment in Jenkins that uses Bundler 2.2.1, which may be incompatible for downstream projects (see #2460). We're reverting this change for now to get a bug fix out, and will update after the holiday break.
> Revert "(maint) Bump shared rubygems for bolt, pe-bolt-server"

- configs/components/rubygem-orchestrator_client.rb
This updates the orchestrator_client-ruby gem to 0.5.1 to include the
new read-timeout configuration option.
Opening this as we need to get this updated before releasing Bolt, and I don't want that to be gated on #411 .
> Pull in orchestrator_client-ruby 0.5.1

- configs/components/rubygem-puppet.rb
Update the Puppet gem to 6.20.0 for Bolt and PE Bolt usage.
> (maint) Pull in Puppet 6.20.0 for Bolt

- configs/components/curl.rb
The curl command is currently compiled without the `--with-ca-path` flag.
This breaks the ability to configure SSL trust for downloading files using curl separately from SSL trust for the Puppet server/agent
applications.
When we configure and build curl, we should pass the `--with-ca-path /opt/puppetlabs/puppet/ssl/certs` flag.
Curl does not provide a way to see the CApath, but overriding the CAfile should print both flags.
Prior to this commit:
```sh-session
> /opt/puppetlabs/puppet/bin/curl --cacert a https://google.com
curl: (77) error setting certificate verify locations:
CAfile: a
CApath: none
```
With this commit:
```sh-session
> /opt/puppetlabs/puppet/bin/curl --cacert a https://google.com
curl: (77) error setting certificate verify locations:
CAfile: a
CApath: …
```
> (PA-3541) Compile curl with CA path

- configs/components/rubygem-aws-partitions.rb
- configs/components/rubygem-aws-sdk-core.rb
- configs/components/rubygem-aws-sdk-ec2.rb
- configs/components/rubygem-facter.rb
- configs/components/rubygem-faraday.rb
- configs/components/rubygem-net-http-persistent.rb
- configs/components/rubygem-puppet-strings.rb
- configs/components/rubygem-rubyntlm.rb
- configs/components/rubygem-winrm.rb
This bumps the versions for Bolt's gem dependencies that aren't shared
with other projects to their latest possible version based on the
current Bolt Gemfile.lock.
> (maint) Bump Bolt non-shared dependencies

- configs/projects/bolt-runtime.rb
This updates the version of Ruby packaged with Bolt from 2.5 to 2.7 as
part of the Bolt 3.0 release.
> (GH-2548) Update Bolt's ruby to 2.7

- configs/projects/bolt-runtime.rb
This updates the bolt-runtime to use the `--no-document` option
when installing gems instead of the defunct `--no-rdoc` and `--no-ri`
options.
> (maint) Update bolt-runtime to use --no-document

- configs/projects/bolt-runtime.rb
This adds the rubygem-scanf component to bolt-runtime.
> (maint) Add rubygem-scanf component to bolt-runtime

- configs/components/augeas.rb
- resources/patches/augeas/augeas-1.12.0-allow-hyphen-postgresql-lens.patch
Pull a patch from upstream that allows for hyphen '-' in values that don't require quotes for the postgresql lens.
https://github.com/hercules-team/augeas/commit/ce9e687588235f1ccc10edda429158b93338dd9b
> (PA-3406) Patch augeas postgresql lens

- DEVELOPERS.md
- configs/components/_base-rubygem-compiled.rb
- configs/components/_base-rubygem-native-extension.rb
- configs/components/rubygem-bootsnap.rb
- configs/components/rubygem-msgpack.rb
- configs/platforms/windows-2012r2-x64.rb
- configs/projects/bolt-runtime.rb
Needed for https://github.com/puppetlabs/bolt/pull/2291
> (packaging) Add bootsnap dependency to bolt-runtime

- configs/platforms/windows-2012r2-x64.rb
During testing https://github.com/puppetlabs/puppet-runtime/pull/384 the public chocolate repo source was added, but I did not remove it before merging. This removes the public repo to ensure the correct sources are used.
> (maint) Remove public chocolate source

- configs/components/openssl-1.1.1.rb
- configs/platforms/debian-10-armhf.rb
- configs/projects/_shared-agent-settings.rb
- resources/files/runtime/runtime.sh
I wanted Raspberry Pi agents to be modern. This change allows the
puppet-runtime to build on debian-10-armhf on a direct compile (not cross)
because modern arm systems aren't totally terrible in terms of speed.
> Add debian-10-armhf build

- configs/components/openssl-1.0.2.rb
- resources/patches/openssl/CVE-2020-1968.patch
Patch compiled from http://launchpadlibrarian.net/497794798/openssl1.0_1.0.2n-1ubuntu5.3_1.0.2n-1ubuntu5.4.diff.gz
> (SEC-191) Patch OpenSSL 1.0.2 for CVE-2020-1968

- configs/projects/pe-bolt-server-runtime-2019.8.x.rb
This commit updates the pe-bolt-server runtime defition to use '2019.8'
instead of 'master' for the 2019.8 builds so that builds pull from the correct
repo locations instead of the deprecated 'master' locations
> (maint) Use correct pe_version for pe-bolt-server

- Gemfile
- configs/components/ruby-2.4.10.rb
- configs/components/ruby-2.5.9.rb
- configs/components/ruby-2.7.3.rb
- configs/platforms/windows-2019-x64.rb
- resources/patches/ruby_27/ruby-faster-load_27.patch
- (PA-3526) Patch Ruby 2.7.2 Avoid realpath in require
> (PA-3526) Ruby 2.7.2 performance patches

- configs/components/rubygem-aws-partitions.rb
- configs/components/rubygem-aws-sdk-core.rb
- configs/components/rubygem-aws-sdk-ec2.rb
- configs/components/rubygem-bindata.rb
- configs/components/rubygem-connection_pool.rb
- configs/components/rubygem-hiera.rb
- configs/components/rubygem-jwt.rb
- configs/components/rubygem-puppet.rb
- configs/projects/bolt-runtime.rb
This adds a new clause to allow projects to pull in Puppet 7.6.1 if they
have the version specified in the project file, and bumps dependencies
that are unique to Bolt and PE Bolt server. Shared dependency bumps are
in a separate PR for review by teams that need them.
Built and installed for ubuntu-20.04
> (maint) Bump Bolt and PE Bolt server dependencies

- configs/components/ruby-2.7.3.rb
I don't believe `site_ruby` is ever used, such as when installing a gem using the `puppet_gem` provider. So this eliminates 3 of the 8 directories from our agent ruby's $LOAD_PATH when running from puppet-agent packages:
```
"/opt/puppetlabs/puppet/lib/ruby/site_ruby/2.7.0",
"/opt/puppetlabs/puppet/lib/ruby/site_ruby/2.7.0/x86_64-linux",
"/opt/puppetlabs/puppet/lib/ruby/site_ruby",
```
On Windows, we're left with:
```
C:\>ruby -e "require 'pp'; pp $:"
["C:/Program Files/Puppet Labs/Puppet/puppet/lib",
"C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/vendor_ruby/2.7.0",
"C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/vendor_ruby/2.7.0/x64-msvcrt",
"C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/vendor_ruby",
"C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/2.7.0", …
```
> (PA-3744) Build without site_ruby

- configs/components/ruby-2.7.3.rb
When installing our compiled ruby we still use some of the code from the local ruby installation on cross-compiled platforms. On el-7-aarch64 ruby 2.0 expects sitedir to point to a valid path. It's not used for anything so just make it point to vendordir as well.
We might get hit with this again if we backport the sitedir removal on 6.x, as we have more cross-compiled platforms there... but until then this workaround should do.
Related to https://github.com/puppetlabs/puppet-runtime/pull/448
> (PA-3744) Fix siteruby removal on el-7-aarch64

- configs/components/rubygem-concurrent-ruby.rb
- configs/components/rubygem-hiera-eyaml.rb
- configs/components/rubygem-highline.rb
- configs/components/rubygem-thor.rb
This pulls in the latest versions of dependencies Bolt shares with the
Puppet Agent projects.
CC @puppetlabs/night-s-watch for approval
> (maint) Bump Bolt shared dependencies

- configs/components/ruby-2.7.3.rb
We are temporary reverting site_ruby change since it might create a regression (e. g. if people are using `site_ruby` directory for ruby script or libraries) and there is no easy work-around.
> (PA-3744) Revert "build without site_ruby"

- configs/platforms/fedora-34-x86_64.rb
Link to passing run for Fedora 34 :
https://jenkins-master-prod-1.delivery.puppetlabs.net/view/vanagon-generic-builder/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/BUILD_TARGET=fedora-34-x86_64,SLAVE_LABEL=worker/1108/
> (PA-3603) Add Fedora 34 x86_64 to puppet-runtime

- configs/platforms/el-8-x86_64.rb
RedHat recently updated their repos and the cmake version pulled is
newer (3.18.2). This uses a libarchive method that is not available on
3.3.2 which is the one that comes with the box.
cmake: symbol lookup error: cmake: undefined symbol: archive_write_add_filter_zstd
This can either be fixed by updating the libarchive package to 3.3.3, or
by pinning cmake to the previous working version (3.11.4). Pin cmake for
now.
> (maint) pin cmake-3.11.4 on el-8-x86_64

- configs/platforms/el-8-aarch64.rb
- configs/platforms/el-8-ppc64le.rb
- configs/platforms/el-8-x86_64.rb
https://github.com/puppetlabs/puppet-runtime/pull/455 locked `cmake` to 3.11.4 to overcome an issue with `libarchive 3.3.2`. 
The issue was fixed in `libarchive 3.3.1` https://bugs.centos.org/view.php?id=18212
> (maint) install `libarchive` on el-8

- configs/components/rubygem-aws-partitions.rb
- configs/components/rubygem-aws-sdk-core.rb
- configs/components/rubygem-aws-sdk-ec2.rb
- configs/components/rubygem-facter.rb
- configs/components/rubygem-orchestrator_client.rb
- configs/components/rubygem-puppet-resource_api.rb
- configs/components/rubygem-r10k.rb
This updates gem dependency versions that are only used in Bolt
projects. Specifically this is to pull in orchestrator_client-ruby to
pick up a fix for the `URI.escape` warning.
> (maint) Update Bolt-specific gem dependencies

- configs/components/rubygem-puppet.rb
Take up API changes for ace server to use v4 catalog endpoint more efficently.
> (PE-31686) Ship puppet 6.23.0 with bolt/ace server

- configs/components/rubygem-sys-filesystem.rb
- resources/patches/rubygem-sys-filesystem/linux-statvfs.patch
The commit https://github.com/djberg96/sys-filesystem/commit/4024d9569cc11841f605bb9f5e74e42c32f2082e causes crash on 32 bits Linux, we should use statvfs64 only on 64 bits Linux
Change also proposed upstream: https://github.com/djberg96/sys-filesystem/pull/56
> (maint) patch sys-filesystem gem

- configs/components/rubygem-ffi.rb
- configs/projects/_shared-pe-bolt-server.rb
- configs/projects/bolt-runtime.rb
This adds a new optional project setting `rubygem_ffi_version` that can
be set to '1.13.1' to continue using FFI 1.13.1 for projects where
upgrading to 15 breaks. We're expecting to be able to unpin the gem in
Bolt's gemspec and revert this change, but need a working build while
that's tested.
> (maint) Pin FFI to 1.13.1 for the Bolt runtime

- configs/components/rubygem-ffi.rb
- configs/projects/_shared-pe-bolt-server.rb
- configs/projects/bolt-runtime.rb
Reverts puppetlabs/puppet-runtime#473
> Revert "(maint) Pin FFI to 1.13.1 for the Bolt runtime"

- configs/projects/pdk-runtime.rb
Complete run: https://jenkins-platform.delivery.puppetlabs.net/view/puppet-runtime/view/pdk-runtime/job/platform_pdk-runtime_runtime-vanagon-packaging_main/29/ 
The finalised package testing is carried out within the PDK pipeline. See: 
- https://github.com/puppetlabs/pdk-vanagon/pull/293
> (PDK-1120) Make ruby 2.5 defacto in PDK

- configs/platforms/ubuntu-18.04-aarch64.rb
Normally we'd need to wait for a vanagon release in order to merge this, but our internal pipelines already run with `main`, so it shouldn't matter :shrug:.
> (VANAGON-171) Use vanagon defaults for Ubuntu 18.04 aarch64

- .github/workflows/comment_on_pr.yaml
- .github/workflows/component_diff_check.yaml
- Gemfile
- Rakefile
- tasks/vanagon_component_diff.rake
This currently runs only with `puppet-runtime` as project but with all available platforms (retrieved from `configs/platforms`). Comment example can be seen [here](https://github.com/luchihoratiu/puppet-runtime/pull/2#issuecomment-904591632) with changes done in a3c136d201cb60654e2fbdcf258dcea7a85867dc.
> (PA-3883) Add GitHub Actions workflow that shows component diff

- configs/components/openssl-1.0.2.rb
- configs/components/openssl-1.1.1-fips.rb
- resources/patches/openssl/CVE-2020-1971.patch
- resources/patches/openssl/CVE-2021-23839.patch
- resources/patches/openssl/CVE-2021-23840.patch
- resources/patches/openssl/CVE-2021-23841.patch
- resources/patches/openssl/CVE-2021-3712.patch
- resources/patches/openssl/openssl-1.1.1-fips-edk2-build.patch
- resources/patches/openssl/openssl-1.1.1-fips-post-rand.patch
- resources/patches/openssl/openssl-1.1.1-fips-spec-file.patch
- resources/patches/openssl/openssl-1.1.1l-ec-group-new-from-ecparameters.patch
- resources/patches/openssl/openssl-1.1.1l-sm2-plaintext.patch
Bump the openssl-fips package to the 1.1.1k-4 version provided by CentOS, and also integrate the two CVE patches that went into the 1.1.1l release (CVE-2021-3712 and CVE-2021-3711).
Patch the following CVEs for openssl 1.0.2:
- CVE-2020-1971
- CVE-2021-23839
- CVE-2021-23840
- CVE-2021-23841
- CVE-2021-3712
> (PA-3974) Bump openssl-fips to 1.1.1k-4 and patch openssl 1.0.2

- configs/components/rubygem-addressable.rb
- configs/components/rubygem-aws-partitions.rb
- configs/components/rubygem-aws-sdk-core.rb
- configs/components/rubygem-aws-sdk-ec2.rb
- configs/components/rubygem-aws-sigv4.rb
- configs/components/rubygem-bootsnap.rb
- configs/components/rubygem-facter.rb
- configs/components/rubygem-molinillo.rb
- configs/components/rubygem-puppet-strings.rb
- configs/components/rubygem-puppet.rb
- configs/components/rubygem-r10k.rb
- configs/components/rubygem-rubyzip.rb
- configs/projects/bolt-runtime.rb
Updates gem versions to their latest resolved versions for dependencies
of Bolt and pe-bolt-server.
Verified this builds + runs for both Bolt and pe-bolt-server packages.
> (maint) Update Bolt dependency gems

- configs/platforms/aix-7.1-ppc.rb
IBM recently updated their AIX Toolbox gcc packages, including the
absolute path of libgcc_s.a (from lib/gcc/powerpc-ibm-aix6.1.0.0 to
lib/gcc/powerpc-ibm-aix7.1.0.0).
The absolute path is pointed to by the symlink at
/opt/freeware/lib/libgcc_s.a which is handled by the libgcc-8-1 package,
which doesn't update the link from 6.1.0.0 to 7.1.0.0.
This causes any binary that depends on libgcc_s.a (yum, gcc) to fail.
As a quick workaround, manually overwrite the symlink to point to the
correct library.
> (maint) Fix gcc installation from AIX Toolbox

- configs/platforms/redhatfips-8-x86_64.rb
- tasks/vanagon_component_diff.rake
I was able to build both `agent-runtime-6.x` and `agent-runtime-main` for RedHat 8 FIPS with these changes.
> (PA-3769) Add RedHat 8 FIPS platform

- configs/components/ruby-2.7.3.rb
Commit 552f10e7 eliminated a seemingly unnecessary call to
`rb_realpath_internal`, which primarily benefits Windows due to its slow
`rb_check_realpath_emulate`[1].
However, when ruby parses a file, it generates an instruction sequence[2] and
stores the realpath in it[3]. Later any calls to `require_relative` are
performed relative to `rb_current_realfilepath`[4] which is implemented by
looking at the realpath for the previous control frame's instruction
sequence[5].
So the patch meant it's possible for a file to be double-required. Once using
its real path, and if another file (B) is loaded via a symlink and B tries to
`require_relative A`. If A happens to be Puppet::FileSystem::Uniquefile, then
puppet will fail to load.
This commit reverts the patch for non-Windows platforms, but …
> (PA-4037) Only apply patch on Windows

- configs/components/rubygem-puppet.rb
- configs/projects/_shared-pe-bolt-server.rb
This updates the PE Bolt server runtime projects to set a pre-release
version of the Puppet 6.x series gem, and additionally updates the
Puppet rubygem component definition to use Artifactory when pulling in
the pre-release version instead of rubygems, since the gem won't be
published there.
This is in order to pull in changes are loading scripts in modules in
Puppet that are required for testing work in Orchestrator around loading
scripts. For now we plan to pin to this gem version since it should have
all of the changes we need, and doesn't need to be updated with new
changes.
Once Puppet 6.25 is availabe these changes can be removed.
> (PE-32928) Ship PE Bolt Server with pre-release Puppet gem

- .github/workflows/snyk_scan.yaml
This PR adds the snyk scan GitHub action from:
https://github.com/puppetlabs/security-snyk-vanagon-action
The skipProjects and skipPlatforms sections are set based on the last set of artifacts built to make the process faster.
This action will:
- fail on PRs to main that have vulnerabilities but not license issues
- add snyk monitoring to the current state (add to the web console)
Note that this is set to only run on pushes to master since this is a public repo (and why the previous PR was deleted, apologies) and we don't want to run on untrusted PRs. In the future I would like this to be run on `pull_request_target` where a label has been applied (ensuring that someone has viewed the PR for malicious intent first)
Finally, `SNYK_PE_TOKEN` has been set as an org secret but has not been …
> Add snyk scanning [skip-ci]

- configs/components/rubygem-puppet.rb
- configs/projects/_shared-pe-bolt-server.rb
- configs/projects/pe-bolt-server-runtime-2019.8.x.rb
- configs/projects/pe-bolt-server-runtime-main.rb
This updates the pe-bolt-server project to continue to use Puppet 6 gem
in the 2019.8.x stream, and adopt Puppet 7 in the main stream.
This also bumps the Puppet version for 2019.8.x to 6.25
> (PE-31696) Use Puppet 7 gem for pe-bolt-server main

- configs/components/ruby-2.5.9.rb
- resources/patches/ruby_25/date-parsing-method-regexp-dos-cve-2021-41817.patch
ruby/date#master commit: https://github.com/ruby/date/commit/3959accef8da5c128f8a8e2fd54e932a4fb253b0
ruby/ruby commit: https://github.com/ruby/ruby/commit/489c8cebf575741d62effd0d212f1319beff3c40
GitHub Advisory DB: https://github.com/advisories/GHSA-qg54-694p-wgpp
The commit from the master branch does not apply cleanly to 2.5.9, but the issue was fixed on multiple versions of the date gem, the oldest one being 2.0.1, which I was able to apply on the Ruby 2.5.9 source: https://github.com/ruby/date/commit/4f9b8e946ba98f0a1774f8e677baa4a45637ebb3
vanagon-generic-builder: https://jenkins-platform.delivery.puppetlabs.net/view/vanagon-generic-builder/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/1218/
> (PA-4131) Patch CVE in date gem for Ruby 2.5.9

- configs/projects/bolt-runtime.rb
- configs/projects/pe-installer-runtime-2019.8.x.rb
Addresses a licensing issue with Ruby gems specific to Windows that use the Artistic 2.0 license by preventing them from building on non-Windows platforms.
> (PA-4187) Limits Windows gems to only build on Win

- configs/components/openssl-1.1.1.rb
Building OpenSSL docs takes about 5 minutes on a raspberry pi and that
seems like something really isn't needed. This commit excludes the
building of docs on armhf architecture since they are slower builders.
⚠️ I would seriously consider doing this on all builds, but 🤷 .
FWIW, this saves about 20% of the time in the runtime build on a pi.
> (maint) Don't build OpenSSL docs for Raspberry pi (armhf)

- configs/projects/agent-runtime-main.rb
This commit alters the project file for agent-runtime to make boost and
yaml-cpp optional using the `NO_PXP_AGENT` env variable which was
already available and honored in the puppet-agent itself.
If `NO_PXP_AGENT` is defined, the project will skip boost and yaml-cpp
since facter does not need those anymore.
> (maint) Make boost and yaml-cpp optional

- configs/platforms/osx-12-x86_64.rb
Blocked on https://github.com/puppetlabs/vanagon/pull/742 and https://github.com/puppetlabs/vanagon/pull/739
> (PA-4220) Adds macOS 12 Monterey support

- configs/platforms/redhatfips-8-x86_64.rb
- configs/projects/_shared-client-tools-runtime.rb
The openssl-1.1.1 package needed as a build dep for curl was conflicting with krb5-devel. This specifically uses openssl-1.1.1k on redhatfips8, which plays nicely with krb5-devel.
> (PE-33126) Fix for building client-tools-runtime on redhatfips-8-x86_64

- configs/components/runtime-pe-installer.rb
- configs/projects/agent-runtime-6.x.rb
- configs/projects/agent-runtime-main.rb
- configs/projects/pe-installer-runtime-2019.8.x.rb
- configs/projects/pe-installer-runtime-main.rb
The pe-installer-runtime needs to include the same gems that agent-runtime includes, since we are running plans via the Bolt provided by pe-installer, and if one of those plans depends on a gem vendored by Puppet, it should be able to rely on it being there as well. Additionally, this removes code for handling Windows and OSX builds for pe-installer-runtime, since we don't build for those platforms, and modifies the component pulling in pl-build-tools so specifically apply to platforms that need it, rather than everything except el8.
In the future, we can probably do away with pe-installer-runtime entirely and use the plain puppet-runtime. But for now, we'll continue to use it to minimize the number of changes happening at once.
> (PE-33733) Include gems in installer-runtime that are present in agent-runtime

- configs/components/runtime-pe-installer.rb
- configs/projects/agent-runtime-6.x.rb
- configs/projects/agent-runtime-main.rb
- configs/projects/pe-installer-runtime-2019.8.x.rb
- configs/projects/pe-installer-runtime-main.rb
Reverts puppetlabs/puppet-runtime#528
Needs openssl changes for fips, and remove ruby-selinux stuff for certain platforms, most likely.
> Revert "(PE-33733) Include gems in installer-runtime that are present in agent-runtime"

- configs/components/runtime-pe-installer.rb
- configs/projects/agent-runtime-6.x.rb
- configs/projects/agent-runtime-main.rb
- configs/projects/pe-installer-runtime-2019.8.x.rb
- configs/projects/pe-installer-runtime-main.rb
Take 2 of https://github.com/puppetlabs/puppet-runtime/pull/528.  This removes selinux from the project definition, since it's already in the shared agent components, and adds the openssl fix that was also needed for client-tools-runtime.
> (PE-33733) Include gems in installer-runtime that are present in agent-runtime, take 2

- configs/projects/pe-installer-runtime-2019.8.x.rb
- configs/projects/pe-installer-runtime-main.rb
Because defining the version of net-ssh happened after we pulled in the shared agent components, it ended up using the default of 4.2 rather than our desired 5.2. This moves the setting above where we pull in the shared components.
> (PE-33792) Define net-ssh version before pulling in shared components

- configs/components/_base-ruby-augeas.rb
- configs/components/_base-ruby.rb
- configs/components/augeas.rb
- configs/components/boost.rb
- configs/components/curl.rb
- configs/components/libxml2.rb
- configs/components/libxslt.rb
- configs/components/ruby-2.5.9.rb
- configs/components/ruby-2.7.6.rb
- configs/components/yaml-cpp.rb
- configs/platforms/osx-12-arm64.rb
Adds support for building agent-runtime-main and agent-runtime-6.x
packages for macOS 12 Monterey ARM64 (m1) via cross-compilation on
an x86-64 host.
Built both runtimes successfully manually on vmpooler machines with `vanagon build`
> (PA-4460) Adds macOS 12 Monterey M1/ARM64 platform

- configs/components/rubygem-faraday-em_http.rb
- configs/components/rubygem-faraday-em_synchrony.rb
- configs/components/rubygem-faraday-excon.rb
- configs/components/rubygem-faraday-httpclient.rb
- configs/components/rubygem-faraday-multipart.rb
- configs/components/rubygem-faraday-net_http.rb
- configs/components/rubygem-faraday-net_http_persistent.rb
- configs/components/rubygem-faraday-patron.rb
- configs/components/rubygem-faraday-rack.rb
- configs/components/rubygem-faraday-retry.rb
- configs/components/rubygem-faraday.rb
- configs/components/rubygem-faraday_middleware.rb
- configs/components/rubygem-multipart-post.rb
- configs/components/rubygem-orchestrator_client.rb
- configs/components/rubygem-puppet_forge.rb
- configs/components/rubygem-ruby2_keywords.rb
- configs/projects/_shared-pe-bolt-server.rb
- configs/projects/bolt-runtime.rb
This bumps faraday for the bolt and pe-bolt-server projects to the 1.x
series. It also adds several dependencies for the 1.x series as gem
components in both projects.
---
Successfully built runtimes & packages for bolt, pe-bolt-server-main, and pe-bolt-server-2019.8.x, and also successfully ran acceptance tests for both pe-bolt-server packages. 👍
> (BOLT-1587) Bump faraday for bolt, pe-bolt-server

- configs/components/puppet-ca-bundle.rb
It's no longer necessary to call `make keystore` since the `puppet-cacerts` java keystore is already pregenerated and copied during the previous `make install` step.
> (PA-4440) puppet-ca-bundle now always installs a keystore as part of the install target

- configs/components/rubygem-webrick.rb
- configs/projects/_shared-pe-bolt-server.rb
- configs/projects/bolt-runtime.rb
This adds webrick 1.7.0 to bolt and pe-bolt-server, which is required by
puppet-strings >= 2.9.0
> (maint) Add webrick to bolt, pe-bolt-server

- configs/projects/_shared-client-tools-runtime.rb
As with https://github.com/puppetlabs/puppet-runtime/commit/0ecaddf3a04014929fa07e85bf8b538958492e2c, Clang  does not
support the older Core2 CPU architecture. For the cross-compilation,
we will skip over optimizing for that unavailable architecture.
This commit also adds cross-compile options as we are currently
building M1 packages on x86 Macs.
> (maint) Cross-compilation options for Mac M1

- configs/components/ruby-2.7.6.rb
Ruby's configure script incorrectly selects the 'ucontext' coroutine
implementation instead of 'amd64' when the target architecture is 'aarch64'.
This resulted in a crash when using coroutines (or fibers). The crash could be
triggered using:
(lldb) target create "/opt/puppetlabs/puppet/bin/ruby"
Current executable set to '/opt/puppetlabs/puppet/bin/ruby' (arm64).
(lldb) settings set -- target.run-args  "-e" "Fiber.new {}.resume"
(lldb) run
Process 698 launched: '/opt/puppetlabs/puppet/bin/ruby' (arm64)
Process 698 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x101b620)
frame #0: 0x00000001007753f4 libruby.2.7.dylib`coroutine_trampoline + 12
libruby.2.7.dylib`coroutine_trampoline:
->  0x1007753f4 <+12>: ldr    x0, [x1, #0x370] …
> (PUP-11592) Use arm64 coroutines when cross compiling for M1

- configs/components/rubygem-ffi.rb
The component logic for downloading ffi for different platforms is complicated... In a routine update some of the checksums were not updated correctly. It appears this is not the first time this has happended. This commit updates the expected sha for 1.15.5
> (PE-34232) Fix expected sha for ffi

- configs/components/rubygem-ffi.rb
The wrong sha sums were collected from rubygems previously. This commit updates them for the expected architectures. This commit also adds a comment note to hopefully prevent this in the future.
> (PE-34232) FFI for windows

- configs/components/rubygem-concurrent-ruby.rb
Partially reverts 107e5fe057673c39d9eefcfcf673307fbf0335c3 as we 1.1.10
requires ruby >= 2.2 and we still rely on ruby 2.1.9 in pl-build-tools.
Will need to revisit next week.
> (maint) Revert concurrent-ruby bump

- configs/components/augeas.rb
- configs/projects/agent-runtime-6.x.rb
- configs/projects/agent-runtime-main.rb
The location for augeas' tarball has changed. The previous versions are still hosted
where we expect, but going forward we'll need to grab them from the Augeas Github repo.
This adds a bit more complexity in the augeas component, once all projects are on 1.13.0
we should be able to simplfy things.
> (PA-4494) Update agent runtime's augeas to 1.13.0

- configs/components/openssl-1.1.1-fips.rb
FIPS OpenSSL hasn't been updated to patch a vulnerability with c_rehash.
This PR sets the c_rehash binary as unexecutable by default.
> (PA-4621) Set c_rehash as unexecutable for fips

- configs/components/augeas.rb
- configs/projects/agent-runtime-6.x.rb
- configs/projects/agent-runtime-main.rb
Reverts puppetlabs/puppet-runtime#568
Seeing failures with building this for macos, sles, and solaris. Going to revert this and fix it up.
> Revert "(PA-4494) Update agent runtime's augeas to 1.13.0"

- configs/components/_base-ruby.rb
When building `agent-runtime-6.x` on macOS 11 & 12 M1, we now install ruby@2.5 from our `homebrew-puppet` tap.
Note these changes would affect pdk-runtime too, but we don't currently support pdk on M1 (as it still relies on ruby@2.4 which was disabled a long time ago).
~~Blocked on https://github.com/puppetlabs/homebrew-puppet/pull/357~~
> (PA-4620) Install ruby@2.5 from our homebrew-puppet tap

- configs/components/openssl-1.1.1-fips.rb
Runtimes for projects other than agent-runtime-* use a different install prefix,
e.g. client-tools uses /opt/puppetlabs/client-tools, so use settings[:prefix] to
resolve the path.
> (PA-4621) Use project `:prefix` to resolve the path

- configs/projects/pe-bolt-server-runtime-2021.7.x.rb
- configs/projects/pe-installer-runtime-2021.7.x.rb
Add new bolt-server-runtime and installer-runtime project files for
2021.7.x branch
> PE-34443,PE-34439 Add projects for 2021.7.x branch

- configs/components/augeas.rb
- configs/platforms/osx-10.15-x86_64.rb
- configs/platforms/osx-11-arm64.rb
- configs/platforms/osx-11-x86_64.rb
- configs/platforms/osx-12-arm64.rb
- configs/platforms/osx-12-x86_64.rb
- configs/projects/_shared-agent-settings.rb
- configs/projects/agent-runtime-6.x.rb
- configs/projects/agent-runtime-main.rb
- resources/patches/augeas/augeas-1.13.0-patch_security_context-t_out.patch
This PR bumps Augeas for all platforms except for Solaris. The readline that is bundled
with Solaris is pretty old and Augeas has a function call that is not defined by readline on
Solaris.
So we are choosing not to bump Augeas for Solaris but for every other platform we can bump it.
On OSX we also need to install readline.
> (PA-4494) Bump Augeas to 1.1.13

- configs/projects/agent-runtime-7.x.rb
This copies agent-runtime-main over to agent-runtime-7.x. This new project will be what we promote into PE 2021.7.x. Long term as agent-runtime-main switches to Ruby 3 the agent-runtime-7.x will remain on Ruby 2.7.
> (PA-4685) Add agent-runtime-7.x project

- configs/projects/pdk-runtime.rb
We recently made changes to the Augeas component and this looks to have broken pdk-runtime for MacOS platforms. If we bump the version of Augeas from 1.8.1 to the latest of 1.13.0 then pdk-runtime will build on MacOS.
> (maint) Update to latest Augeas for pdk-runtime

- configs/components/_base-ruby.rb
- configs/components/libffi.rb
- configs/components/libyaml.rb
- configs/components/ruby-3.2.0.rb
- configs/components/ruby-shadow.rb
- configs/projects/_shared-agent-components.rb
- configs/projects/agent-runtime-main_ruby_32.rb
- resources/patches/ruby_32/ruby-shadow-2.5.0-cflags.patch
This PR adds ruby 3.2 as a component to puppet runtime. It also copies the agent-runtime-main into a new project that has ruby 3.2. Until we have a branch of puppet-agent to promote ruby 2.7.6 to we'll need to seperate out this.
There are three changes that are needed to get Ruby 3.2 to build:
* Package libffi
* Package libyaml
* Patch ruby-shadow Starting with Ruby 3.2 libffi and libyaml are no longer packaged with Ruby, so we need to take care of that. Ruby-shadow is a gem dependcy that is way out of date and wont build with Ruby 3, there is a simple patch we apply that allow us to build it.
The scope of this PR is just to build against EL-7 and EL-8, there is further work to do to get all other supported platforms to build.
> (PA-4715) Add Ruby 3.2 to puppet-runtime, validated with EL-7 & EL-8

- configs/components/rubygem-nokogiri.rb
Nokogiri includes libxml2, older versions of which are vulnerable to CVE-2022-2309 NULL pointer derefence.
This commit updates Nokogiri to 1.13.9, which includes a patched version of libxml2.
> (PA-4767) Update Nokogiri for CVE-2022-2309

- configs/projects/_shared-pe-bolt-server.rb
Previously we were using the `systemssl` flag when building shared bolt/ace server runtime artifacts. This should no longer be necessary as the vendored openssl versions should be compatible.
> (PE-34844) Stop compiling bolt/ace-server gems against system openssl

- configs/components/ruby-2.7.6.rb
- configs/platforms/solaris-11-i386.rb
- resources/patches/ruby_27/solaris-do-not-use-qsort_s.patch
A companion to https://github.com/puppetlabs/puppet-runtime/pull/595, add some hackery to get ruby-2.7.6 to build on solaris-11
> (maint) Convince ruby 2.7.6 to build on Solaris 11

- configs/platforms/solaris-10-i386.rb
- configs/platforms/solaris-10-sparc.rb
- configs/platforms/solaris-11-sparc.rb
Autoconf is required.
SPARC is currently broken, I'm removing the autoconf from them for now while I decide if it is required.
> (maint) Fix solaris-10-i386 agent-runtime-main

- configs/components/ruby-2.7.6.rb
When building ruby 2.7, `RbConfig::CONFIG['CPP']` contains the interpolated value of `$(CC) -E`. When building for Solaris (10 & 11, x86_64 and SPARC), the interpolated value is of the form:
/opt/pl-build-tools/bin/<arch>-pc-solaris2.1x-gcc -E
However, pl-build-tools doesn't exist on the end target. So reset the `CPP` option to `gcc -E`, similar to what is done for `CC`
This only affects Solaris for now, but should probably be done for all hosts that are cross-compiled and/or use pl-build-tools.
> (PA-4737) Reset CPP rbconfig

- configs/components/ruby-2.7-augeas.rb
- configs/components/ruby-2.7-selinux.rb
- configs/components/ruby-2.7-stomp.rb
- configs/components/ruby-2.7.7.rb
- configs/projects/agent-runtime-7.x.rb
- configs/projects/agent-runtime-main.rb
- configs/projects/bolt-runtime.rb
- configs/projects/pdk-runtime.rb
- configs/projects/pe-installer-runtime-2021.7.x.rb
- configs/projects/pe-installer-runtime-main.rb
- resources/patches/ruby_27/transform_mjit_header.patch
Add a patch for Solaris to get a `-std=c99` flag added
> (PA-4805) Bump Ruby to 2.7.7 for runtime-main

- configs/components/rubygem-nokogiri.rb
This commit updates the Nokogiri component used in puppet-agent- runtime on macOS from 1.13.9 to 1.13.10, which addresses CVE-2022-23476.
> (PA-4817) Updates Nokogiri to 1.13.10

- configs/components/rubygem-fast_gettext.rb
- configs/components/rubygem-gettext-setup.rb
- configs/components/rubygem-gettext.rb
- configs/components/rubygem-prime.rb
- configs/components/rubygem-r10k.rb
- configs/projects/_shared-pe-bolt-server.rb
- configs/projects/agent-runtime-6.x.rb
- configs/projects/agent-runtime-7.x.rb
- configs/projects/agent-runtime-main_ruby_32.rb
- configs/projects/bolt-runtime.rb
- configs/projects/pdk-runtime.rb
Puppet projects will soon be using Ruby 3.2, which is not compatible with versions of fast_gettext earlier than 2.1 because of the deprecated taint checking features.
This commit also removes the conditional for multiple versions of fast_gettext, which was originally added in 29db591e55448931dabcc4803385c10b999ee1b7 for puppet-agent 1.10.x, which has long been deprecated.
> (PA-4815) Updates fast_gettext gem to 2.2.0

- configs/projects/agent-runtime-main.rb
gettext and related components have been updated by default in preparation for Ruby 3.2, but agent-runtime-main is still running Ruby 2.7. This commit pins gettext, fast_gettex, and gettext-setup to older versions in the runtime.
> (PA-4815) Pins gettext versions for runtime-main

- configs/components/boost.rb
- configs/platforms/aix-7.1-ppc.rb
Recently, the GCC package for AIX changed from linking to GCC 8 to GCC 10, breaking compilation for things like Ruby native extensions and C++ components like Boost.
This commit specifies GCC 8 to restore working behavior for building runtimes on AIX.
> (maint) Fix AIX GCC options

- configs/projects/_shared-pe-bolt-server.rb
- configs/projects/pe-bolt-server-runtime-2021.7.x.rb
- configs/projects/pe-bolt-server-runtime-main.rb
Similar to previous commit, inclusion of the prime gem was failing to find forwardable in the pe-bolt-server 2019.8.x pipeline, so this removes it from _shared-pe-bolt-server.rb and includes it specifically for 2021.7.x and main that use the later gettext defaults.
> (PE-4815) Remove prime gem from pe-bolt-server 2019.8.x

- configs/projects/pe-bolt-server-runtime-2021.7.x.rb
- configs/projects/pe-bolt-server-runtime-main.rb
The component needs to be added after the eval of
_shared-pe-bolt-server.rb which adds settings the component method relies on.
> (PA-4815) Fix order of rubygem-prime include for pe-bolt-server

- configs/platforms/el-7-x86_64.rb
- configs/platforms/el-8-ppc64le.rb
- configs/platforms/redhatfips-7-x86_64.rb
el-8-ppc64le and redhatfips-7-x86_64 fail to build agent-runtime-main (Ruby 3.2) because they're missing autoconf. This pushes the platform definitions into vanagon. The autoconf, etc dependencies were added to vanagon.
~This is blocked until this commit is released: https://github.com/puppetlabs/vanagon/commit/768969f6bf7a02580e09c6dd99a64e3800bb1745~
Successfully built this PR with vanagon 0.33.0 in https://jenkins-platform.delivery.puppetlabs.net/view/vanagon-generic-builder/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/1882/
> (PA-4838) Update platform defaults for RHEL 8 ppc64le, RHEL 7 & 8 (x86-64)

- configs/platforms/ubuntu-18.04-aarch64.rb
This commit merges the packages from the platform definition for Ubuntu 18.04 aarch64/ARM64 with the packages from the upstream Vanagon default.
> (PA-4841) Move Ubuntu packages to Vanagon

- configs/components/_base-ruby-selinux.rb
- resources/patches/ruby-selinux/selinuxswig_ruby_wrap.patch
Calling into selinux from Ruby 3.2 generates a warning:
selinux.so: warning: undefining the allocator of T_DATA class swig_runtime_data
This is because ruby 3.2 requires C extensions to "either use rb_define_alloc_func() to overwrite it or rb_undef_alloc_func() to delete it."[1] The selinux C extension selinuxswig_ruby_wrap.c is autogenerated by swig from the selinuxswig_i template.
swig 4.1.1 contains the fix for this[2] but we are using an older version on RHEL7. So patch the autogenerated C extension, which needs to happen after the code is generated and before it's compiled.
[1] https://github.com/ruby/ruby/blob/6963f8f743b42f9004a0879cd66c550f18987352/doc/extension.rdoc#label-Write+the+C+Code
[2] https://github.com/swig/swig/commit/962f0900018ecb10287b327d261e424fa5ccb755
> (PA-4844) Patch the autogenerated selinux C extension

- configs/components/rubygem-gettext.rb
The file breaks debian packaging and isn't part of the repo.
```
touch rubygem-gettext-configure
touch rubygem-gettext-build
touch rubygem-gettext-check
export GEM_HOME="/opt/puppetlabs/puppet/lib/ruby/vendor_gems" && \
export RUBYLIB="/opt/puppetlabs/puppet/lib/ruby/vendor_ruby:" && \
cd ./ && \
/opt/puppetlabs/puppet/bin/gem install --no-document --local gettext-3.4.3.gem && \
rm -f /opt/puppetlabs/puppet/lib/ruby/vendor_gems/gems/gettext-3.4.3/test/fixtures/gtk_builder_ui_definitions.ui~
Successfully installed gettext-3.4.3
1 gem installed
```
> (PA-4845) Delete extra file

- configs/components/_base-rubygem.rb
We set the Windows PATH and exclude the /usr/bin directory, that is where the rm command is found and caused failures in builds.
> (PA-4845) Update the Windows PATH

- configs/projects/pe-installer-runtime-2019.8.x.rb
- configs/projects/pe-installer-runtime-2021.7.x.rb
- configs/projects/pe-installer-runtime-main.rb
The 2019.8.x stream is pinned back to an older version of gettext and its dependencies to support the version of ruby shipped in the puppet 6 stream. Newer PE streams support running with the unpinned version. In order to support the newer configuration the `prime` rubygem is required. This commit adds the prime gem to installer runtime artifacts to support the new gettext version.
> (PA-4815) Update installer runtime to support gettext versions

- configs/components/pl-ruby-patch.rb
- configs/components/ruby-3.2.0.rb
- configs/platforms/osx-11-arm64.rb
- configs/platforms/osx-11-x86_64.rb
- configs/platforms/osx-12-arm64.rb
- configs/platforms/osx-12-x86_64.rb
- resources/patches/ruby_32/ruby-shadow-rbconfig.patch
Building in https://jenkins-platform.delivery.puppetlabs.net/view/vanagon-generic-builder/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/1894/
> (PA-4769) Enable Ruby 3.2.0 on macOS on ARM

- configs/components/openssl-3.0.rb
- configs/projects/agent-runtime-main.rb
Adds OpenSSL 3.0.7 component
Switches agent-runtime-main on redhat, fedora, debian, ubuntu and sles to use
that version. redhatfips is unchanged as are other agent runtime projects.
I verified agent-runtime-66.x and agent-runtime-7.x are unaffected:
```
❯ bx rake vanagon:component_diff -- -P agent-runtime-7.x -f upstream/master -t HEAD
...
Here is what your code changes would affect:
Project agent-runtime-7.x
Nothing is affected 😊
❯ bx rake vanagon:component_diff -- -P agent-runtime-6.x -f upstream/master -t HEAD
...
Here is what your code changes would affect:
Project agent-runtime-6.x
Nothing is affected 😊
```
While `agent-runtime-main` is:
```
❯ bx rake vanagon:component_diff -- -P agent-runtime-main -f upstream/master -t HEAD
...
Here is what your code changes would affect:
Project …
```
> (PA-4869) Move to OpenSSL 3.0 on base linux platforms

- configs/projects/agent-runtime-main.rb
openssl 3 changed their versioning scheme, so pxp-agent-vanagon builds on systems with older cmake weren't finding openssl correctly, see
https://github.com/Kitware/CMake/commit/4a6caef9d57f823cf0cfa9087ebe072d263d1b18
For now revert the openssl bump and revisit in PA-4870.
> (PA-4869) Revert openssl 3 bump for OSes with older cmake

- configs/components/pl-ruby-patch.rb
Commit 0ee61dced fixed cross compiling for macOS 12 ARM, but broke Solaris 10 & 11 SPARC, because `base_ruby` is a file path, not a version string. Since "/opt/pl-build-tools/lib/ruby/2.1.0" doesn't start with "2.1.0" we applied the wrong sed command on Solaris cross compiling.
Since the last component of `base_ruby` defines the ruby API as x.y.0, then match that string directly.
Built `agent-runtime-7.x` on macOS ARM and Solaris SPARC in https://jenkins-platform.delivery.puppetlabs.net/view/vanagon-generic-builder/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/1902/
The `vanagon component_diff` output below is misleading, because we don't support many of those platforms in `agent-runtime-main`, but we do in `agent-runtime-6.x`. So I rebuilt the latter on the …
> (PA-4769) Redo pl-ruby-patch for Solaris

- configs/components/openssl-3.0.rb
- configs/projects/agent-runtime-main.rb
https://jenkins-platform.delivery.puppetlabs.net/view/vanagon-generic-builder/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/1906/
`osx-11-arm` and `osx-10.15-x86_64` are not supported in `agent-runtime-main` and can be ignored below.
> (PA-4875) Build OpenSSL 3 for macOS Intel & ARM

- configs/components/openssl-3.0.rb
c_rehash binary has been replaced by an openssl subcommand 'rehash'. The binary is still packaged and that can lead to some confusion since we add that to puppet-agent, so this will just remove the c_rehash binary.
> (PA-4265) Remove c_rehash binary

- configs/components/libffi.rb
- configs/components/libyaml.rb
- configs/components/ruby-3.2.0.rb
- configs/components/rubygem-ffi.rb
- resources/patches/libffi/revert_clang_32bit.patch
- resources/patches/ruby_32/windows_mingw32_mkmf.patch
- resources/patches/ruby_32/windows_nocodepage_utf8_fallback_r2.5.patch
* Adds gcc bin directory to PATH for libffi and libyaml
* Drops unneeded patches: `configure.ac`, `win32_long_paths_support`, `windows_ruby_2.5_fixup_generated_batch_files`
* Patch mkmf.rb to build native extensions using [mingw-w64](https://www.mingw-w64.org/) (instead of mingw)
* Fix how ffi gem was pinned on < 2.7
* Use latest ffi gem (1.15.5) and compile native extension `ffi_c`
* Install libssp-0.dll needed for gcc's stack protection
* Patch libffi 3.4.3 on Windows x86
Built x64 and x86 packages in https://jenkins-platform.delivery.puppetlabs.net/view/vanagon-generic-builder/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/1922/
I created a separate ticket (PA-4913) to add this CI (along with pxp-agent-vanagon, etc)
> (PA-4717) Ruby 3.2 for Windows x64 and x86

- configs/components/openssl-3.0.rb
This commit updates the OpenSSL 3.0 component from 3.0.7 to 3.0.8. This release includes several security fixes.
See the OpenSSL site for more details on the CVEs addressed in this release: https://www.openssl.org/news/openssl-3.0-notes.html
> (PA-4912) Updates OpenSSL 3.0 to 3.0.8

- configs/projects/pdk-runtime.rb
This commit switches the PDKs default ruby to 2.7.7. 2.5.9 has been moved in to the additional rubies hash.
> (CONT-660) Switch default ruby

- configs/components/pl-ruby-patch.rb
Ruby 3 on macOS ARM expects native extensions to be in a directory named `arm64-darwin` instead of `aarch64-darwin`.
> (PA-4945) Use arm64 instead of aarch64

- configs/components/ruby-3.2.0.rb
- resources/patches/ruby_32/revert-ruby-double-load-symlink.patch
- resources/patches/ruby_32/ruby-faster-load_32.patch
Applies the faster-load patch on Windows that we're using with Ruby 2.7
Revert an upstream commit (Windows only). The commit prevented a double load when a file is loaded through a symlink, but that situation is extremely rare for us, so revert until the upstream issue is resolved, see https://bugs.ruby-lang.org/issues/19378.
With both patches, `puppet apply -e 'notice($puppetversion)'` generates 36x fewer file IO calls than ruby 3.2.0 built via rubyinstaller.
Built agent-runtime-main and all tests passed for windows-2019 (64-bit) and windows 10 (32-bit) except for unrelated forge cert issue https://jenkins-platform.delivery.puppetlabs.net/view/puppet-agent/view/ad-hoc/job/platform_puppet-agent-extra_puppet-agent-integration-suite_adhoc-ad_hoc/1081/
I confirmed the forge failures are …
> (PA-4911) Ruby 3.2 performance patches for Windows

- configs/components/git.rb
- configs/platforms/el-9-x86_64.rb
Prior to this change, puppet-runtime would fail to build due package installation failures.
Specifically, the expat-devel package failed to install because it did not exist on our mirror. 
This change makes use of a newly created repo with all of the packages needed to build puppet-runtime.
Additionally dh-autoreconf is also removed as a dependency as per RHEL8
> (CONT-550) Prep PDK for RHEL9

- configs/components/rubygem-CFPropertyList.rb
`CFPropertyList` versions < 3.0.6 have a `File.exists?` [call](https://github.com/ckruse/CFPropertyList/commit/6afb06fbc11b225477846197e5bfd3d582e204b0) but `File.exists?` was deprecated and removed in Ruby 3.2. Since Ruby 3.2 is used for Puppet 8, this causes issues for macOS 11 and 12 which use the CFPropertyList gem. This commit bumps `CFPropertyList` to 3.0.6 for the agent-runtime-main project which uses Ruby 3.2.
> (PA-5016) Bump CFPropertyList to 3.0.6 for Ruby 3.2

- configs/components/ruby-3.2.0.rb
- resources/patches/ruby_32/rbinstall_gem_path.patch
`CFPropertyList` failed to load because `nokogiri` depended on `racc`, but the default `racc` gem was copied to the wrong gem dir when cross-compiling. With this change, on macOS 12 ARM:
```
true
*** LOCAL GEMS ***
abbrev (default: 0.1.1)
base64 (default: 0.1.1)
benchmark (default: 0.2.1)
bigdecimal (default: 3.1.3)
bundler (default: 2.4.1)
CFPropertyList (2.3.6)
cgi (default: 0.3.6)
concurrent-ruby (1.1.9)
csv (default: 3.2.6)
date (default: 3.3.3)
debug (1.7.1)
deep_merge (1.2.2)
delegate (default: 0.3.0)
did_you_mean (default: 1.6.3)
digest (default: 3.1.1)
drb (default: 2.1.1)
english (default: 0.7.2)
erb (default: 4.0.2)
error_highlight (default: 0.5.1)
erubi (1.11.0)
etc (default: 1.4.2)
fast_gettext (2.2.0)
fcntl (default: 1.0.2)
ffi (1.15.5)
fiddle (default: 1.1.1)
fileutils …
```
> (PA-4945) Install default and bundled gems for macOS 12 ARM cross compiles

- configs/components/openssl-1.1.1.rb
- configs/components/openssl-3.0.rb
man and html docs accounted for 13MB uncompressed and a surprising amount of
build time because the build runs pod2man and perl twice for each doc. OpenSSL
doesn't have a `--no-docs` option, so follow what other projects do to avoid
building/installing docs, like ruby-setup.
This change affects all runtime projects and platforms except those using
openssl-1.1-fips, because the fips version doesn't have the `install_ssldir`
Makefile target.
I built agent-runtime-main in https://jenkins-platform.delivery.puppetlabs.net/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/1961/ except for redhatfips-* so I removed them from this PR.
RHEL9 build times dropped from 26 to 19 mins.
> (PA-4908) Drop openssl man and html docs

- configs/components/openssl-3.0.rb
- configs/projects/agent-runtime-main.rb
Currently, there are runtime builds for Windows x86 and x64. This commit enables openssl 3 for Windows.
> (PA-4874) Build OpenSSL 3 for Windows x64 & x86

- configs/projects/agent-runtime-main.rb
Previously, OpenSSL 3 broke on pxp-agent for Windows because cmake could not resolve OpenSSL correctly (see PA-4970). However, this has been resolved. This commit re-enables OpenSSL 3 for Windows in agent-runtime-main.
> (PA-4874) Re-enable OpenSSL 3 for Windows

- configs/components/ruby-3.2.1.rb
- configs/projects/agent-runtime-main.rb
Ruby 3.2.1 was released on Feb 8, 2023. This commit bumps agent-runtime-main to use Ruby 3.2.1.
> (PA-5018) Bump to Ruby 3.2.1

- configs/projects/agent-runtime-main.rb
We use pl-cmake on older linux which patch CMake for OpenSSL 3 support.
Only AIX, Solaris and FIPS remain.
Built [puppet-runtime#6da945a1803cd648b76e72475fda80e44efb625f](https://jenkins-platform.delivery.puppetlabs.net/view/vanagon-generic-builder/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/1985/)
Built [pxp-agent-vanagon#main with agent-runtime-main from above](https://jenkins-platform.delivery.puppetlabs.net/view/vanagon-generic-builder/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/1986/)
[adhoc puppet-agent el-7, sles-12, ubuntu 18.04 passed](https://jenkins-platform.delivery.puppetlabs.net/view/puppet-agent/view/ad-hoc/job/platform_puppet-agent-extra_puppet-agent-integration-suite_adhoc-ad_hoc/1096/)
```
20:14:13 -- Found OpenSSL: …
```
> (PA-4870) Build OpenSSL 3 on older linux

- configs/components/rubygem-nokogiri.rb
When building nokogiri native extensions on macOS 12 ARM, there is a 94M directory called tmp in the agent tarball that's not needed. This commit deletes the tmp directory for macOS 12 ARM.
> (PA-5017) Remove tmp nokogiri directory from agent tarball

- configs/components/rubygem-nokogiri.rb
Built 11 and 12 ARM in https://jenkins-platform.delivery.puppetlabs.net/view/vanagon-generic-builder/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/1988/
Note technically we don't support macOS 11 ARM, but we build packages and ship them https://downloads.puppet.com/mac/puppet7/11/arm64 as "best effort"
> (PA-5017) Delete tmp nokogiri dir on macOS 11 ARM too

- configs/components/rubygem-hocon.rb
- configs/projects/agent-runtime-main.rb
The latest version uses require_relative, so only doing this in the Puppet 8 stream.
Passed adhoc with these runtime changes: https://jenkins-platform.delivery.puppetlabs.net/job/platform_puppet-agent-extra_puppet-agent-integration-suite_adhoc-ad_hoc/1097/
> (PA-5023) Bump hocon to 1.4.0 in agent-runtime-main only

- configs/components/ruby-3.2.1.rb
- resources/patches/ruby_32/revert_ruby_utf8_default_encoding.patch
When ruby changed the `Encoding.default_external` with this PR at https://github.com/ruby/ruby/pull/2877, it broke puppet testing for Japanese Windows. With the default encoding set to UTF-8, both facter and puppet would error. This commit to puppet-runtime will modify the way puppet builds ruby and revert that commit, allowing powershell to use the locale instead of defaulting to utf-8.
> (PA-5367) Revert ruby's 3.2 default to local encoding

- configs/components/rubygem-nokogiri.rb
The previous version of 1.13.10 only supported < 3.2.dev. The older 1.13.10 version also had a restriction of > 3.1, but the newer 1.14.2 supports ruby 2.7 through 3.2.
> (maint) update nokogiri for ruby 3.2 support

- configs/components/ruby-3.2.2.rb
- configs/projects/agent-runtime-main.rb
Ruby 3.2.2 was released on March 30, 2023 with fixes for two CVEs: CVE-2023-28755 and CVE-2023-28756.
This commit updates the Ruby 3.2 component from Ruby 3.2.1 to 3.2.2.
> (PA-5369) Bump Ruby 3.2 to 3.2.2

- configs/components/curl.rb
agent-runtime-7.x passed in https://jenkins-platform.delivery.puppetlabs.net/view/vanagon-generic-builder/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/2007/
agent-runtime-main passed (excluding platforms we don't support yet) in
https://jenkins-platform.delivery.puppetlabs.net/view/vanagon-generic-builder/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/2008/
> (PA-5393) Bump curl 7.88.1

- Gemfile
- configs/components/ruby-2.7-augeas.rb
- configs/components/ruby-2.7-selinux.rb
- configs/components/ruby-2.7-stomp.rb
- configs/components/ruby-2.7.8.rb
- configs/projects/agent-runtime-7.x.rb
- configs/projects/bolt-runtime.rb
- configs/projects/pdk-runtime.rb
- configs/projects/pe-installer-runtime-2021.7.x.rb
- configs/projects/pe-installer-runtime-main.rb
Ruby 2.7.8 was released on March 30, 2023 to address two CVEs: CVE-2023-28755 and CVE-2023-28756.
This commit bumps the Ruby component from 2.7.7 to 2.7.8 and increments the ruby_version setting used by components and projects that use Ruby 2.7.
> (PA-5368) Bump Ruby 2.7 component to 2.7.8

- configs/components/rubygem-concurrent-ruby.rb
- configs/projects/agent-runtime-7.x.rb
Puppet agent 7 is compatable with 1.1.10 but some platforms (rhel7 aarch/arm) have a build step with a ruby version that is incompatable with concurrent-ruby 1.1.10. Given this will be deprecated soon and that concurrent ruby 1.1.9 is suitable on all platforms, pin it back for agent 7 series.
> (maint) Pin back concurrent ruby for agent 7 packages

- configs/projects/_shared-agent-settings.rb
The resulting Makefile contains:
```
openssl-3.0-configure: openssl-3.0-patch runtime-agent
[ -d openssl-3.0.8 ] || mkdir -p openssl-3.0.8
export PATH="$(shell cygpath -u C:/tools/mingw64/bin):$(PATH)" && \
cd openssl-3.0.8 && \
./Configure --prefix=C:/ProgramFiles64Folder/PuppetLabs/Puppet/puppet --libdir=lib --openssldir=C:/ProgramFiles64Folder/PuppetLabs/Puppet/puppet/ssl shared no-asm mingw64 no-camellia no-ec2m no-md2 no-ssl3 no-dtls no-dtls1 no-idea no-seed no-weak-ssl-ciphers -DOPENSSL_NO_HEARTBEATS 
touch openssl-3.0-configure
openssl-3.0-build: openssl-3.0-configure
export PATH="$(shell cygpath -u C:/tools/mingw64/bin):$(PATH)" && \
cd openssl-3.0.8 && \
/usr/bin/make depend && \
/usr/bin/make
touch openssl-3.0-build
openssl-3.0-check: openssl-3.0-build
touch openssl-3.0-check …
```
> (PA-4877) Use Ruby 3 with Puppet 8 on Windows FIPS

- configs/components/runtime-agent.rb
We used to copy some gcc dlls into ruby and native facter's bin directory, see PA-2067. But we no longer define `facter_root` so we were copying the dlls into cygwin's `/lib` directory on the build host. If you tried to rebuild on the same host, it would fail because the destination file existed.
> (maint) Don't copy facter dll dependencies

- configs/components/_base-ruby-augeas.rb
- resources/patches/augeas/ruby-augeas-0.5.0-patch_c_extension.patch
This issue is very similar to PA-4844 (#620) except it affects augeas instead of selinux
When puppet is run with Ruby 3.2, this warning is generated:
`/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/augeas.rb:48: warning: undefining the allocator of T_DATA class Augeas`
This commit patches the autogenerated augeas C extension so there is no warning for augeas
> (PA-5430) Patch augeas C extension

- configs/components/openssl-3.0.rb
The flags were just appended to the end of the configure options, where they were then just passed down to the compiler or linker. This change now uses the environment variable support that openssl has in versions 3+.
> (PA-5409) Use CFLAGS and LDFLAGS during ssl configuration

- configs/components/openssl-3.0.rb
- configs/projects/_shared-agent-settings.rb
- resources/patches/windows/FORCEINLINE-i686-w64-mingw32-winnt.h
FIPS builds of openssl 2.x on Windows required libeay32.dll to be loaded at a fixed address 0x63000000. If it wasn't then FIPS_check_incore_fingerprint would generate an error. The openssl 3 fips provider doesn't have that issue so reenable dynamic base (ASLR).
> (PA-5427) Enable dynamicbase on OpenSSL3 and Windows FIPS

- configs/components/openssl-3.0.rb
The 'puppet infra' command uses the agent's runtime when executing bolt tasks & plans. When a task uses the WinRM transport, it will authenticate to the Windows host using NTLM. The NTLMv1 protocol relies on MD4 to compute the NT-Hash[1] so we need to re-enable it here.
[1] https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-nlmp/464551a8-9fc4-428e-b3d3-bc5bfb2e73a5
> (PA-5409) Keep md4 for NTLM

- configs/components/openssl-3.0.rb
The openssl built for puppet-runtime is used to build postgres for puppetdb; when openssl is built with the `no-bf` and `no-cast` flags, the pgcrypto module for postgres errors out during the build process. This change puts the ciphers back in so postgres can build for puppetdb.
> (maint) Reenable bf and cast ciphers for pgcrypto

- configs/platforms/windows-2012r2-x64.rb
- configs/platforms/windows-2012r2-x86.rb
- configs/platforms/windowsfips-2012r2-x64.rb
Chocolatey 2.0 dropped the deprecated Get-BinRoot script which mingw-w64 relies on, so pin back to 1.4.0 for now. We also have to disable upgrades so we don't upgrade to 2.0.
I added published a new https://artifactory.delivery.puppetlabs.net/artifactory/generic/buildsources/windows/chocolatey/install-chocolatey-1.4.0.ps1 which configures chocolatey to install packages from our artifactory instance and not upstream.
Building https://jenkins-platform.delivery.puppetlabs.net/view/vanagon-generic-builder/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/2067/
> (PA-5593) Pin to chocolatey 1.4.0

- configs/components/rubygem-addressable.rb
- configs/components/rubygem-bundler.rb
- configs/components/rubygem-childprocess.rb
- configs/components/rubygem-cri.rb
- configs/components/rubygem-diff-lcs.rb
- configs/components/rubygem-hitimes.rb
- configs/components/rubygem-json-schema.rb
- configs/components/rubygem-json_pure.rb
- configs/components/rubygem-pastel.rb
- configs/components/rubygem-pathspec.rb
- configs/components/rubygem-public_suffix.rb
- configs/components/rubygem-tty-color.rb
- configs/components/rubygem-tty-cursor.rb
- configs/components/rubygem-tty-prompt.rb
- configs/components/rubygem-tty-reader.rb
- configs/components/rubygem-tty-screen.rb
- configs/components/rubygem-tty-spinner.rb
- configs/components/rubygem-tty-which.rb
- configs/components/rubygem-wisper.rb
- configs/components/runtime-pdk.rb
- configs/platforms/windows-2019-x64.rb
- configs/projects/_pdk-components.rb
- configs/projects/pdk-runtime.rb
This change updates the default Ruby to 3.2.2 and latest puppet to v8.
The secondary Ruby is now 2.7.8.
> (CONT-934) Prep for Puppet 8 and Ruby 3

- configs/projects/pe-installer-runtime-main.rb
While we figure out what we want to do for PE-36078, ship the gem build from the fork of ntlm that implements an md4 algorithm in ruby.
> (PE-36078) Use fork of ntlm with md4 ruby algo

- configs/components/rubygem-hiera-eyaml.rb
This commit update the hiera-eyaml component from 3.3.0 to 3.4.0, which enables compatibility with Ruby 3.2.
> (PA-5633) Update hiera-eyaml

- configs/components/openssl-3.0.rb
macOS x86 builds of agent-runtime-main recently started failing due to a combination of Homebrew updating all of its core Formulae from OpenSSL 1.1.1 to 3.0 and our build was configuring OpenSSL to use the `EC_GROUP_new` and `EVP_rc2_40_cbc` functions that were deprecated in OpenSSL 3[1]
This commit removes the configuration flags for OpenSSL 3 that invoke these deprecated functions.
[1] https://www.openssl.org/docs/man3.0/man7/migration_guide.html
> (maint) Remove deprecated OpenSSL functions

- configs/platforms/aix-7.2-ppc.rb
While a custom `mktemp` command can be specified in vanagon, we expect the command to be available in PATH, such as in CI. Just link it.
Passed in https://jenkins-platform.delivery.puppetlabs.net/view/vanagon-generic-builder/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/2109/BUILD_TARGET=aix-7.2-ppc,SLAVE_LABEL=k8s-worker
This should resolve the issue we ran into in CI, forcing us to disable [AIX 7.2](https://github.com/puppetlabs/ci-job-configs/pull/8988). When this is merged, please also merge https://github.com/puppetlabs/ci-job-configs/pull/8994
> (PA-5637) Ensure mktemp is available without modifying PATH

- configs/components/openssl-3.0.rb
When the runtime linker loads executables, it uses a search path in the
executable to find library dependencies. On most platforms this is done
via -rpath, but on AIX it's -R. The search path is embedded in the
executable and can be seen using:
...
***Import File Strings***
INDEX  PATH                          BASE                MEMBER
0      /opt/puppetlabs/puppet/lib:/usr/lib:/lib
Built in https://jenkins-platform.delivery.puppetlabs.net/view/vanagon-generic-builder/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/2110/BUILD_TARGET=aix-7.2-ppc,SLAVE_LABEL=k8s-worker/
<details>
<summary>Component 'openssl-3.0'</summary>
**&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Field:** `environment`
```diff
- CC=/opt/freeware/bin/gcc CFLAGS=-I/opt/puppetlabs/puppet/include …
```
> (PA-4871) Add our libdir to the runtime linker search path

- configs/components/curl.rb
- configs/projects/_shared-agent-components.rb
Hide and restore /opt/freeware/lib/libcurl.a while building curl
PR https://github.com/puppetlabs/puppet-runtime/pull/690 should be merged first
&nbsp;&nbsp;&nbsp;&nbsp;Component 'curl' was newly added, not showing diff for it :white_check_mark:
&nbsp;&nbsp;&nbsp;&nbsp;Component 'curl' was newly added, not showing diff for it :white_check_mark:
> (PA-5618) Build curl on AIX 7.2

- configs/platforms/aix-7.1-ppc.rb
- configs/platforms/aix-7.2-ppc.rb
This is slightly complicated by the fact that AIX sed doesn't support in-place upgrades and we need to make this change after installing yum, but before running yum to install build dependencies.
> (PA-5621) Point AIX 7.1 & 7.2 to artifactory

- configs/components/_base-ruby.rb
- configs/components/libffi.rb
- configs/components/ruby-3.2.2.rb
- configs/components/rubygem-ffi.rb
- configs/platforms/solaris-11-i386.rb
This PR updates Solaris on agent-runtime-main to:
* Build libffi, with gmake
* Build Ruby 3.2.2 with OpenCSW gcc
* Configure rubygem-ffi, but still expected to fail. rubygem-ffi will be fixed at a later point
* Also installs a new GCC and autotools as part of the image.
> (PA-4718) Updates for Solaris and agent-runtime-main

- configs/components/curl.rb
- configs/components/yaml-cpp.rb
- configs/platforms/aix-7.2-ppc.rb
- configs/projects/agent-runtime-main.rb
Previous attempts to build yaml-cpp failed when trying to run
/opt/freeware/bin/cmake, because it linked to libcurl.a and generated:
0509-150 Dependent module /opt/freeware/lib/libcurl.a(libcurl.so.4) could not be loaded.
0509-103 The module has an invalid magic number.
That library is preinstalled on our AIX 7.2 hosts and is version 7.52.1. The
library is also used by yum/python in order to download AIX toolbox packages.
As mentioned in https://github.com/eclipse-openj9/openj9/issues/4245 upgrading
the curl version resolves the issue. And in order to do that we need to bootstrap
a newer openssl 1.1.x version.
Installing newer curl also means we can remove the hack that was added when
building curl.
Note the typo `$PATH` vs `$(PATH)`. The latter is necessary so that PATH is
resolved at …
> (PA-5617) Build yaml-cpp on AIX 7.2

- configs/components/openssl-1.1.1.rb
- configs/components/ruby-2.7.8.rb
- configs/components/yaml-cpp.rb
- configs/platforms/osx-13-arm64.rb
Hello,
The result of component diff :
`
Platform name: osx-13-arm64
Component 'openssl-1.1.1'
Field: configure[0]
--------------------
- [" ./Configure --prefix=/opt/puppetlabs/puppet --libdir=lib --openssldir=/opt/puppetlabs/puppet/ssl shared no-asm darwin64-x86_64-cc  no-camellia no-ec2m no-md2 no-ssl3 no-dtls no-dtls1 no-idea no-seed no-weak-ssl-ciphers -DOPENSSL_NO_HEARTBEATS -I/opt/puppetlabs/puppet/include "]
+ [" ./Configure --prefix=/opt/puppetlabs/puppet --libdir=lib --openssldir=/opt/puppetlabs/puppet/ssl shared no-asm darwin64-arm64-cc  no-camellia no-ec2m no-md2 no-ssl3 no-dtls no-dtls1 no-idea no-seed no-weak-ssl-ciphers -DOPENSSL_NO_HEARTBEATS -I/opt/puppetlabs/puppet/include "]
Field: environment
--------------------
- PATH=/opt/pl-build-tools/bin:$(PATH):/usr/local/bin
+ …
> (PA-5594) Enable macOS 13 (ARM) puppet-runtime builds for agent-runtime-7.x

- configs/components/rubygem-ffi.rb
Our logic is incorrect, previously we were looking at `settings[:runtime_project]`. In agent-runtime context that will always just return 'agent', not the full project name we were looking for.
This lead to having the PL build tools path added earlier then we want and an older GCC being used that breaks rubygem-ffi from building.
> (PA-5640) Fix ruybgem-ffi runtime logic

- configs/components/curl.rb
- configs/components/ruby-3.2.2.rb
- configs/components/runtime-agent.rb
- configs/platforms/aix-7.2-ppc.rb
- resources/patches/ruby_32/reline_disable_terminfo.patch
Whenver a fileset is installed via installp, e.g. openssl.base, IBM recommends
running updtvpkg so that RPM packages which depend on it, build correctly.
And after installing rpm.rte, yum prints that an update is required. This seems
to resolve package dependencies issues between yum/python/libcurl and cmake.
For reasons not entirely clear, if we provision an AIX host, install yum,
install build dependencies and then build curl within the same ssh session, then
the resulting curl executable will fail to run:
exec(): 0509-036 Cannot load program /opt/puppetlabs/puppet/bin/curl because of the following errors:
0509-150   Dependent module libcurl.a(libcurl.so.4) could not be loaded.
0509-022 Cannot load module libcurl.a(libcurl.so.4).
0509-026 System error: A file or directory in the path …
> (PA-5645) Install additional runtime dependencies

- configs/components/openssl-3.0.rb
- configs/projects/pe-installer-runtime-main.rb
- resources/patches/openssl/openssl-3-activate-legacy-algos.patch
Implements the solution described in https://tickets.puppetlabs.com/browse/PE-36078
Still needs building & testing but putting this up so I can verify I understand the basics correctly.
> (PE-36348) Enable legacy openssl algos in PE Installer runtime to support Bolt's WinRM transport

- configs/components/curl.rb
OpenSSL 3.0 by default disables some legacy algorithms that are required for ntlm. We previously kept them enabled for Bolt's WinRM transport but in b85bf0fda made the inclusion of these legacy algorithms optional so that the agent and company no longer have to include insecure crypto on account of Bolt.
However, removing the NTLM algorithms from OpenSSL caused downstream failures in the compilation of curl, which this patch addresses by disabling curl's support for NTLM.
> (PE-36344) Disable curl's ntlm if OpenSSL excludes it

- configs/components/openssl-3.0.rb
We ship pgcrypto in PE and it uses the agent runtime's openssl. pgcrypto hardcodes DES support into it and will fail to start if the DES algorithm isn't available.
In the future either postgresql should ship its own openssl or we should patch pgcrypto to not hardcode DES into itself.
> (maint) Add DES back to OpenSSL 3

- configs/components/runtime-pe-bolt-server.rb
- configs/projects/_shared-pe-bolt-server_with_ruby.rb
- configs/projects/pe-bolt-server-runtime-main.rb
Includes a ruby and openssl build inside the bolt-server main package. This change paves the way for us to enable legacy chiphers in bolt-server's openssl to ensure ntlm (and by extension the WinRM transport) can still function.
> (PE-36345) Add ruby/openssl to bolt-server main

- configs/components/_base-ruby.rb
Homebrew recently updated its Ruby 2.7 formula to use OpenSSL 3.0 instead of 1.1:
https://github.com/Homebrew/homebrew-core/pull/134420/commits/fb4bb7656476000716e7d45bb595561789b2d18c
Ruby 2.7 does not support OpenSSL 3.0, so using Homebrew's updated formula causes test failures for puppet-agent.
This commit switches our Vanagon projects to use the last version of Homebrew's Ruby 2.7 formula prior to the switch over to OpenSSL 3.0.
> (PA-5646) Pin to OpenSSL 1.1 Ruby 2.7

- configs/components/_base-ruby-augeas.rb
- configs/components/_base-ruby.rb
- configs/components/augeas.rb
- configs/components/curl.rb
- configs/components/libffi.rb
- configs/components/openssl-3.0.rb
- configs/components/ruby-3.2.2.rb
- configs/components/ruby-shadow.rb
- configs/components/rubygem-ffi.rb
- configs/platforms/solaris-113-sparc.rb
- configs/projects/_shared-agent-settings.rb
- configs/projects/agent-runtime-main.rb
I couldn't find a way to to make solaris-11-sparc platform definition take into
account the project, because of the way vanagon creates the Platform and then
later the Project. So create a new solaris-113-sparc platform definition for
native Solaris compiles.
Since the name of the file contains 113, vanagon assumes that's the
`os_version`. Setting the os_version from within the platform definition doesn't
seem to work, so I had to special case some logic to check for the
platform.name.
Although we're native compiling on SPARC, we have to explicitly set
`--with-baseruby=no` so that ruby's configure script does not attempt to use the
ancient ruby already installed. Instead build miniruby and have the build use
that. We should probably be setting `--with-baseruby=no` always, except in cases …
> (PA-4867) Build ruby on Solaris 11 SPARC

- configs/components/_base-ruby-augeas.rb
- configs/components/_base-ruby.rb
- configs/components/augeas.rb
- configs/components/curl.rb
- configs/components/libffi.rb
- configs/components/openssl-3.0.rb
- configs/components/ruby-3.2.2.rb
- configs/components/ruby-shadow.rb
- configs/components/rubygem-ffi.rb
- configs/components/yaml-cpp.rb
- configs/platforms/solaris-113-sparc.rb
- configs/projects/_shared-agent-settings.rb
- configs/projects/agent-runtime-main.rb
boost: no changes are required to build, so add the component.
yaml-cpp: default to /usr/bin/gmake except for Solaris 10 and use /usr/bin/cmake
instead of pl-cmake.
Successfully built in https://jenkins-platform.delivery.puppetlabs.net/view/vanagon-generic-builder/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/2229/BUILD_TARGET=solaris-113-sparc,SLAVE_LABEL=k8s-worker/ and shipped to https://builds.delivery.puppetlabs.net/puppet-runtime/cd2f8ed54cff954306835f71942e2fe1dd10d6f6/artifacts/
> (PA-5692) Build yaml-cpp and boost on Solaris 11 SPARC

- configs/components/runtime-agent.rb
AIX runtime-agent hard codes the ncurses library, looks like there was a recent update that we need to get.
> (maint) Bump libncurses

- Gemfile
- configs/components/curl.rb
- configs/components/rubygem-ffi.rb
- configs/platforms/solaris-11-native-sparc.rb
- configs/projects/_shared-agent-settings.rb
Since the puppet-runtime repo contains multiple projects and we need to build solaris 11 sparc differently for 7.x vs main, I was using solaris-113-sparc to fake out vanagon. However, the generated tarballs still had 113 in the name, which meant pxp-agent-vanagon couldn't find it when building solaris-11-sparc.
This leverages new functionality in vanagon that allows the platform name to be overridden based on the string passed to the `platform` DSL method instead of relying on the platform's filename.
It also undoes some hacks that were in place to differentiate between solaris 11 and 113.
This is blocked on:
Please merge https://github.com/puppetlabs/puppet-runtime/pull/712 after this.
> (PA-5701) Generate tarballs with solaris-11-sparc in the name

- configs/projects/pe-bolt-server-runtime-main.rb
- configs/projects/pe-installer-runtime-main.rb
This commit enables legacy openssl algorithms to support the winrm transport in bolt-server. Winrm does not work on FIPS currently so we continue to leave that unsupported.
> (PE-36344) Enable md4 for winrm transport in bolt server for non fips

- configs/components/pl-ruby-patch.rb
The rubygems version installed is the same for 2.7 and 3.2 for macos,
so patch the same file in both streams of ruby.
> (PA-5666) Patch builder.rb if macos and using ruby 2.x

- configs/components/ruby-2.7.8.rb
- configs/components/ruby-3.2.2.rb
- resources/patches/ruby_27/uri-redos-cve-2023-36617.patch
- resources/patches/ruby_32/uri-redos-cve-2023-36617.patch
This commit patches the Ruby URI gem to handle vulnerability CVE-2023-36617. This vulnerability is addressed in URI 0.12.2, which can be updated in the Ruby 3.2 stream.
We will likely not need this patch in Ruby > 3.2.2, as future releases will presumably include URI >= 0.12.2.
We also apply this patch to Ruby 2.7 but because it is end-of-life, there is no corresponding URI release.
ruby/uri#master commits: https://github.com/ruby/uri/commit/9010ee2536adda10a0555ae1ed6fe2f5808e6bf1 https://github.com/ruby/uri/commit/9d7bcef1e6ad23c9c6e4932f297fb737888144c8 ruby/ruby commit: https://github.com/ruby/ruby/commit/dd73fe077cae077808e820f4765a12b1f4660521 GitHub Advisory DB: https://github.com/advisories/GHSA-hww2-5g85-429m
> (PA-5638) Update Ruby URI gem

- configs/projects/_shared-client-tools-runtime.rb
- configs/projects/client-tools-runtime-main.rb
Client-tools-runtime-main: https://jenkins-platform.delivery.puppetlabs.net/view/vanagon-generic-builder/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/2261/
> (PE-36622) Build client-tools-runtime-main for macOS 13 (ARM)

- configs/components/puppet-ca-bundle.json
- configs/components/puppet-ca-bundle.rb
Refreshes CA bundles
Copies the `puppet-cacerts-fips` keystore when building on FIPS hosts. Otherwise uses the regular `puppet-cacerts` keystore.
Drops TrustCor CA
Example of [RHEL8 install](https://jenkins-platform.delivery.puppetlabs.net/view/vanagon-generic-builder/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/2325/BUILD_TARGET=redhatfips-8-x86_64,SLAVE_LABEL=k8s-worker):
```
cp -f puppet-cacerts-fips /opt/puppetlabs/puppet/ssl/puppet-cacerts
chown 0:0 /opt/puppetlabs/puppet/ssl/puppet-cacerts
chmod 0644 /opt/puppetlabs/puppet/ssl/puppet-cacerts
```
And [Windows FIPS install](https://jenkins-platform.delivery.puppetlabs.net/view/vanagon-generic-builder/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/2325/BUILD_TARGET=windowsfips-2012r2-x64 …
> (PA-4813) Refresh CA bundle and include FIPS version of puppet-cacerts

- configs/platforms/el-9-aarch64.rb
Added platform definition of redhat9 to enable puppet-runtime build.
> (PA-5733) Enable puppet-runtime builds for rhel9

- configs/components/openssl-3.0.rb
EOpenSSL released version 3.0.11 in order to fix a low risk security issue [CVE-2023](https://www.cve.org/CVERecord?id=CVE-2023-4807)
> (PA-5783) Bump OpenSSL to 3.0.11

- configs/projects/bolt-runtime.rb
The puppet 8 puppet packages contain the 1.1.10 version of concurrent ruby. Bolt 3.x is still puppet 7 based. In the case where an apply is used over the local transport where the bundled-ruby options is not set it is important that the concurrent ruby versions match. This commit ensures bolt-packages have the same version as puppet 7 packages. As we figure out the bolt 4 / puppet 8 story we can update accordingly.
> (PE-36907) Ensure the version of concurrent-ruby matches puppet-agent 7.y

- configs/components/rubygem-puppet-strings.rb
- configs/projects/pe-bolt-server-runtime-2021.7.x.rb
The puppet-strings 4 series requires ruby 2.7. While the agent version ships with 2.7 the Jruby in the LTS is more akin to the ruby 2.6 spec. This makes the puppet-strings version break when run under Jruby. For the LTS we pin back to the 3 series.
> (PE-36966) Use puppet-strings 3.x sereies for LTS bolt-server

- configs/components/curl.rb
- resources/patches/curl/CVE-2023-38545.patch
apply patch for curl CVE-2023-38545
ref: https://github.com/curl/curl/discussions/12026
https://curl.se/docs/CVE-2023-38545.html
> (PA-5852) Apply CVE-2023-38545 patch for curl vulnerablity

- configs/components/libyaml.rb
The github path was incorrect and the 0.2.5 was being included twice resulting in:
```
Attempting to fetch from canonical URL "https://github.com/yaml/libyaml/releases/download/libyaml/yaml-0.2.5-0.2.5.tar.gz"
An error was encountered evaluating block. Retrying..
```
Will only be seen with - `VANAGON_USE_MIRRORS=false`
> Fix libyaml github URL and name for libyaml file

- configs/components/ruby-3.2.2.rb
Jenkins builds failing for Mac OSX with current version: https://jenkins-platform.delivery.puppetlabs.net/job/platform_pdk-runtime_runtime-vanagon-packaging_main/BUILD_TARGET=osx-12-x86_64,SLAVE_LABEL=k8s-worker/314/console
Set special flag `--with-openssl-dir=` to run against Mac OS on Ruby 3.2.2.
This flag works to force the use of the openssl version included within the runtime itself rather than the one that is installed by homebrew as default.
> (CAT-270) Set special flag to run against Mac OS on ruby 3.2.2

- CODEOWNERS
The PDK and all it's parts are now under the Tooling/DevX team
> Change PDK ownership to Tooling

- configs/platforms/amazon-2023-aarch64.rb
- configs/platforms/amazon-2023-x86_64.rb
Removed the rubocop lines from amazon-linux-2023 platform files as rubocop is not used for puppet-runtime repo
> (maint) Removed Rubocop lines from the platform files

- configs/platforms/debian-10-amd64.rb
- configs/platforms/debian-10-armhf.rb
- configs/platforms/debian-11-aarch64.rb
- configs/platforms/debian-11-amd64.rb
- configs/platforms/debian-11-armhf.rb
- configs/platforms/el-6-i386.rb
- configs/platforms/el-6-x86_64.rb
- configs/platforms/el-7-ppc64le.rb
- configs/platforms/el-7-x86_64.rb
- configs/platforms/el-8-aarch64.rb
- configs/platforms/el-8-x86_64.rb
- configs/platforms/el-9-aarch64.rb
- configs/platforms/el-9-x86_64.rb
- configs/platforms/sles-12-ppc64le.rb
- configs/platforms/sles-12-x86_64.rb
- configs/platforms/sles-15-x86_64.rb
- configs/platforms/ubuntu-18.04-amd64.rb
- configs/platforms/ubuntu-20.04-aarch64.rb
- configs/platforms/ubuntu-20.04-amd64.rb
- configs/platforms/ubuntu-22.04-aarch64.rb
- configs/platforms/ubuntu-22.04-amd64.rb
Native facter 3.x relied on JNI to bridge between Java and native code so that facter could be required in JRuby/puppetserver[1]. We also relied on javac and javah when building facter.jar. As a result, the puppet-agent project required openjdk in order to build native facter[2]. Note this was before the existence of the puppet-runtime project.
In 2015, we added the ca-cert component to puppet-agent[3]. It was later renamed to puppet-ca-bundle.
In 2017, we extracted ruby, curl, puppet-ca-bundle, etc into a separate puppet-runtime project, and the openjdk dependency was copied[4].
In 2020, we dropped support for facter 3 due to puppet 6 going EOL.
In 2022, we no longer run keytool when building the runtime[5]. Instead we update the puppet-cacerts keystore whenever the puppet-ca-bundle …
> Drop openjdk build dependency

- configs/components/_base-ruby-selinux.rb
Prior to this commit, when building runtimes the SELinux component created a symlink for a shared library on Red Hat 9 in order to successfully build SELinux 3.3.
This worked for the agent runtimes but because the PDK runtime builds multiple Rubies, builds would fail because it would attempt to create a symlink when one already existed.
This commit checks for a symlink for the SELinux shared library before creating one.
> (PA-5632) Check for SELinux symlink

- .github/workflows/component_diff_check.yaml
- .github/workflows/jira.yml
- .github/workflows/mend.yaml
- .github/workflows/runtime_tests.yaml
This PR:
- Adds a friendly name to the GitHub Actions workflow that exports GitHub Issues to Jira.
- Updates the Checkout action.
> (PA-5932) Add name to Jira workflow

- configs/components/post-additional-rubies.rb
- configs/components/pre-additional-rubies.rb
- configs/projects/_pdk-components.rb
- configs/projects/pdk-runtime.rb
The order that components are listed in pdk-components matters, so build openssl 3 first followed by other components that rely on it (curl, git, etc). Then build openssl 1.1.1 before building the extra ruby 2.7.8.
Note the openssl 1.1.1 headers still overwrite the 3.0.x, which is bad and needs to be resolved somehow as it may confuse any rubygem with native extension that we install in ruby 2.7.
```
ashen-control:~ root# otool -L /opt/puppetlabs/pdk/lib/libcurl.4.dylib
/opt/puppetlabs/pdk/lib/libcurl.4.dylib:
/opt/puppetlabs/pdk/lib/libcurl.4.dylib (compatibility version 13.0.0, current version 13.0.0)
/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1856.105.0) …
```
> Build pdk runtime components against openssl 3

- configs/components/runtime-pdk.rb
Explicit components have been added for both `libffi` and `libyaml` so these lines are no longer needed when setting up Ruby 3.2 and above and so can be removed.
> (CAT-1505) Remove unneeded lines from Ruby 3.2 setup

- configs/components/_base-ruby.rb
- configs/components/runtime-pdk.rb
- configs/projects/_pdk-components.rb
Previously, the pdk-vanagon's gem prune command[1] failed on Windows with Ruby 3.2:
$ GEM_PATH="C:/ProgramFiles64Folder/PuppetLabs/DevelopmentKit/private/puppet/ruby/3.2.0;C:/ProgramFiles64Folder/PuppetLabs/DevelopmentKit/share/cache/ruby/3.2.0" RUBYOPT="-Irubygems-prune" C:/ProgramFiles64Folder/PuppetLabs/DevelopmentKit/private/ruby/3.2.2/bin/gem.bat prune
.. The specified module could not be found.   - C:/ProgramFiles64Folder/PuppetLabs/DevelopmentKit/private/ruby/3.2.2/lib/ruby/3.2.0/x64-mingw32/psych.so (LoadError)
This commit:
* Installs libffi-8.dll, libyaml-0-2.dll and libssp-0.dll into the pdk's primary ruby 3.2 bin directory
* Removes libffi-6.dll from ruby 3.2 bin directory
See individual commits for gory details
[1] https://github.com/puppetlabs/pdk-vanagon/blob/c7d35b03fa014f95 …
> Install missing dependencies for Ruby 3.2

- configs/platforms/osx-14-arm64.rb
Enable puppet-runtime builds for macOS 14(ARM)
> (PA-5902) Enable puppet-runtime builds for macOS 14(ARM)

- configs/projects/agent-runtime-7.x.rb
This commit bumps the Augeas component in agent-runtime-7.x from 1.13.0 to 1.14.1.
> (PA-5944) Bump Augeas in agent-runtime-7.x

- configs/components/libicu.rb
appears only the latest minor releases are available from download, so use the github tagged source
> (maint) fix icu4c download

- .github/workflows/component_diff_check.yaml
- .github/workflows/mend.yaml
- .github/workflows/runtime_tests.yaml
The `gem install bundler` step started failing because the latest bundler is not compatible with Ruby 2.7:
The last version of bundler (>= 0) to support your Ruby & RubyGems was 2.4.22.
Try installing it with `gem install bundler -v 2.4.22`
Just move everything to 3.2. Note this doesn't affect the ruby we build or ship, just the version that's used to run GH actions.
> Switch to Ruby 3.2 for GH actions

- configs/components/rubygem-concurrent-ruby.rb
- configs/projects/agent-runtime-7.x.rb
- configs/projects/bolt-runtime.rb
- configs/projects/pdk-runtime.rb
Versions prior to 1.2.x have a memory leak in JRuby when storing thread local state. Move everything to 1.2.2 and drop the old versions.
This also switches to SHA256 for this gem and raises if a project requests an unknown version.
Here is what your code changes would affect:
<details>
<summary>Component 'rubygem-concurrent-ruby'</summary>
**&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Field:** `install[0]`
```diff
- /opt/puppetlabs/installer/bin/gem install --no-document --local --bindir=/opt/puppetlabs/installer/bin concurrent-ruby-1.1.10.gem
+ /opt/puppetlabs/installer/bin/gem install --no-document --local --bindir=/opt/puppetlabs/installer/bin concurrent-ruby-1.2.2.gem
```
**&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Field:** `mirrors[0]`
```diff
- …
```
> (PA-5960) Use concurrent-ruby 1.2.2 for all runtimes

- configs/components/rubygem-puppet.rb
- configs/projects/bolt-runtime.rb
- configs/projects/pe-bolt-server-runtime-2021.7.x.rb
- configs/projects/pe-bolt-server-runtime-main.rb
Commit f201ef9 bumped all runtime projects to use concurrent-ruby 1.2.2, but some runtime projects vendor an older version of puppet that requires concurrent-ruby less than 1.2. So bump those runtime projects to use the latest released puppet version.
Technically, puppet versions 7.25.0 and 8.1.0 were the first gems to support concurrent-ruby 1.2 and up, but there are some other bug fixes with binary Strings and monkey patching `File,Dir.exists?` back, so bump to latest.
> (PA-5960) Bump vendored puppet gems for concurrent-ruby 1.2.2 compat

- configs/components/ruby-3.2.3.rb
- resources/patches/ruby_32/revert_speed_up_rebuilding_loaded_feature_index.patch
Ruby 3.2.3 included commit 5baf94f9131fb45d50c8c408e007a138ced46606 which
improves the performance of rebuilding the loaded feature index. This was
needed to fix the perf slowdown introduced in 79a4484a072e9769b603e7b4fbdb15b1d7eccb15.
Performance is improved on systems with the `realpath` system call. On RHEL8,
the number of file syscalls needed to run `puppet apply -e ""` from puppet-agent
packages dropped nearly an order of magnitude: 455,006 to 55,149.
However, ruby emulates `realpath` on some systems like Windows. So the
performance benefit from commit 5baf94f9 doesn't overcome the perf hit
introduced by 79a4484a0. So revert 5baf94f9 in this commit. The existing
`revert-ruby-double-load-symlink.patch` will then apply cleanly to revert
79a4484a0.
With this change, the total number of …
> (PA-6051) Revert patch for ruby 3.2.3 on Windows

- configs/components/ruby-2.7.8.rb
- configs/platforms/sles-11-x86_64.rb
Added sles11 to ruby-2.7.8 and removed java-1.7.1
Vanagon generic builder : https://jenkins-platform.delivery.puppetlabs.net/view/vanagon-generic-builder/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/2639/console
artifacts : https://builds.delivery.puppetlabs.net/puppet-runtime/9885a2f903730910232330a40320487574f27da7/artifacts/
> (PA-5999) Add sles11 intel platform support

- configs/platforms/sles-11-x86_64.rb
- For Puppet8, we use ruby3 which requires autoconf to be >= 2.67, but SLES-11 supports only upto 2.63. So, we use pl-autotools for both puppet7 and puppet8 for consistency.
> (PA-5999) Use pl-autotools instead of autoconf and automake for SLES-11

- configs/projects/pe-installer-runtime-2021.7.x.rb
2.7.0 requires Ruby 3, so include this at 2.6 so Bolt doesn't try pulling in 2.7.
> (maint) Use Nori 2.6.0 for pe-installer-runtime-2021.7.x

- configs/components/ruby-3.2.3.rb
- resources/patches/ruby_32/openssl3_fips.patch
Prior to this commit, attempting to enable fips_mode in Ruby 3.2.3's OpenSSL gem would cause the error "This version of OpenSSL does not support FIPS mode (OpenSSL::OpenSSLError)". This was due to OpenSSL removing the FIPS_mode() function in OpenSSL 3, which Ruby previously relied on to detect if FIPS was enabled.
Upstream has fixed this incompatibility with OpenSSL 3 in Ruby 3.3. The contributor has indicated that the fix should be backported to Rubies 3.0-3.2 in the future.
This commit applies Ruby's fix as a patch.
See also:
- ruby/ruby@678d41bc51fe31834eec0b653ba0e47de5420aa0
- https://bugs.ruby-lang.org/issues/20000
> Apply Ruby patch to enable FIPS with OpenSSL 3

- configs/components/curl.rb
- resources/patches/curl/CVE-2023-46218.patch
Applied Curl Patch CVE-2023-46218 [cookie: lowercase the domain names before PSL checks]
> [PA-6145]: Applied Curl Patch CVE-2023-46218

- configs/components/curl.rb
- resources/patches/curl/CVE-2024-2004.patch
- resources/patches/curl/CVE-2024-2398.patch
Applied following curl patches to curl 7.88.1:
1. [CVE-2024-2004](https://curl.se/docs/CVE-2024-2004.html)
2. [CVE-2024-2398](https://curl.se/docs/CVE-2024-2398.html)
> (PA-6291): Applied curl patches to curl 7.88.1

- configs/components/openssl-3.0.rb
- resources/patches/openssl/openssl-3.0.13-crypto-providers.patch
Patch is needed to resolve this error:
$ ./Configure shared mingw64
Configuring OpenSSL version 3.0.13 for target mingw64
Using os-specific seed configuration
Failure!  Makefile wasn't produced.
Please read INSTALL.md and associated NOTES-* files.  You may also have to
look over your available compiler tool chain or change your configuration.
/var/tmp/openssl-3.0.13/crypto/sha/../providers: No such file or directory at ./Configure line 3413.
Building https://jenkins-platform.delivery.puppetlabs.net/view/vanagon-generic-builder/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/2780/
> (PA-6131) Bump openssl version

- configs/components/dmidecode.rb
- configs/components/openssl-3.0.rb
- configs/components/rubygem-ffi.rb
- configs/components/rubygem-gettext.rb
- configs/components/rubygem-prime.rb
- configs/components/rubygem-public_suffix.rb
- configs/components/rubygem-rgen.rb
- configs/components/rubygem-win32-dir.rb
- configs/components/rubygem-win32-process.rb
- configs/components/rubygem-win32-security.rb
- configs/components/rubygem-win32-service.rb
- configs/components/runtime-pe-installer.rb
- configs/components/virt-what.rb
- configs/projects/bolt-runtime.rb
Puppet 6 was the last stream to depend on win32-* gems, see https://github.com/puppetlabs/puppet-runtime/commit/513c5583bb6449187eb7ef6306997398917a5c10. In
Puppet 7, all of the required functionality was implemented in puppet itself.
Since bolt-runtime has moved to puppet 7.27, we can drop these gems.
> Drop unused win32 gems from bolt-runtime and other cleanup

- configs/components/openssl-3.0.rb
I should have left a review on https://github.com/puppetlabs/puppet-runtime/pull/822 but I was too fast merging. This just leaves a comment to remember to remove the patch for CVE-2024-2511 after the next OpenSSL 3.0.x release.
> Leave comment to remove patch

- configs/components/openssl-1.1.1.rb
- resources/patches/openssl/openssl-1.1.1-CVE-2024-2511.patch
Applied following patch to openssl-1.1.1
1. [CVE-2024-2511](https://www.openssl.org/news/secadv/20240408.txt)
> (PA-6379): Applied patch to openssl 1.1.1

- configs/components/libxml2.rb
- configs/components/libxslt.rb
- configs/platforms/aix-7.1-ppc.rb
- configs/platforms/aix-7.2-ppc.rb
- configs/platforms/solaris-10-i386.rb
- configs/platforms/solaris-10-sparc.rb
- configs/platforms/solaris-11-i386.rb
- configs/platforms/solaris-11-native-sparc.rb
- configs/platforms/solaris-11-sparc.rb
These changes make it possible for anyone to build the `agent-runtime-*` projects for modern linux outside of our network. This is done by installing the release tarballs from libxml2 and libxslt and installing the necessary packages to decompress the tarballs. And this will make it possible to easily bump to newer versions of libxml2 and libxslt in the future.
> (PA-5715) Download release tarballs for libxml2 and libxslt

- configs/components/curl.rb
After commit 9a62dd5, curl 8 on AIX was adding a runtime dependency on libnghttp2 because the library happened to be present in /opt/freeware/lib:
/opt/puppetlabs/puppet/bin/curl needs:
/usr/lib/libc.a(shr.o)
/usr/lib/libpthreads.a(shr_xpg5.o)
/opt/puppetlabs/puppet/lib/libcurl.a(libcurl.so.4)
/opt/puppetlabs/puppet/lib/libz.a(libz.so.1)
Cannot find libnghttp2.a(libnghttp2.so.14)
However, libnghttp2 is not a runtime component nor is it redistributed with the agent, so curl would fail to load:
exec(): 0509-036 Cannot load program curl because of the following errors:
0509-150   Dependent module libnghttp2.a(libnghttp2.so.14) could not be loaded.
0509-022 Cannot load module libnghttp2.a(libnghttp2.so.14).
0509-026 System error: A file or directory in the path name does not exist.
Since we …
> Disable nghttp2 explicitly

- configs/projects/_pdk-components.rb
- configs/projects/_shared-agent-components.rb
- configs/projects/bolt-runtime.rb
bolt, pdk, and agent runtimes have different support for selinux depending on the Linux platform
> ensure ruby-selinux component is included consistently across runtimes

- configs/components/_base-ruby-augeas.rb
- configs/components/_base-ruby-selinux.rb
- configs/platforms/fedora-40-x86_64.rb
- resources/patches/augeas/ruby-augeas-0.5.0-patch_remove_unused_parameter.patch
- Add Fedora 40 (Intel) platform definition file
- Patch swig generated interface patch for Fedora 40
- Apply ruby-augeas patch to remove unused sibling parameter for all platform building ruby-augeas. It breaks Fedora 40 and generates a warning for other platforms.
> (PA-6350) Enable agent-runtime main builds for fedora 40 Intel

- configs/platforms/amazon-7-aarch64.rb
Enabled AL2 arm for puppet-runtime
> (PA-6260) Add Amazon Linux2 ARM in puppet-runtime build 7.x

- configs/platforms/amazon-7-aarch64.rb
While constructing agent-runtime-main for Amazon-7-aarch, I encountered an obstacle during the OpenSSL 3.0.1 build process. Through online research, I discovered that adding perl-IPC-Cmd resolves this issue.
[vanagon build main](https://jenkins-platform.delivery.puppetlabs.net/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/BUILD_TARGET=amazon-7-aarch64,SLAVE_LABEL=k8s-worker/2900/consoleFull)
> (PA-6259) openssl error Can't locate IPC/Cmd.pm

- configs/components/_base-rubygem.rb
- configs/components/rubygem-nokogiri.rb
This PR changes the gem install command for the Nokogiri gem. Currently when building nokogiri it uses the system libxml2 and libxslt. We now will pass in an option in the `gem install` command to use the expected libraries.
> (maint) Use packaged libxml to build nokogiri on MacOS

- configs/components/ruby-2.7.8.rb
- configs/projects/bolt-runtime.rb
Fixes building gems on windows x86
Blocking https://github.com/puppetlabs/bolt/pull/3248
> Bolt windows ed25519 support

- configs/components/yaml-cpp.rb
Upstream in Vanagon in puppetlabs/vanagon@055c817, we changed Amazon Linux 2 to use the cmake3 package instead of cmake.
This commit adds a case to the yaml-cpp component to refer to cmake3 when building on AL2 instead of cmake.
> Use cmake3 for Amazon Linux 2

- .github/workflows/mend.yaml
Previously, the Mend action referenced 7.x and main branches. These branches do not exist in this repository and were likely copied over from the puppet or puppet-agent repositories.
This commit updates Mend to reference the master branch, which is the default branch for puppet-runtime.
> Set Mend branch to master

- configs/components/_base-rubygem.rb
- configs/components/pl-ruby-patch.rb
- configs/components/rubygem-ffi.rb
- configs/components/rubygem-nokogiri.rb
- resources/files/ruby/patch-hostruby.rb
* Our pl-ruby-patch wasn't being applied correctly after homebrew updated ruby@3.2 to 3.2.3
* Fail the build if host rubygems is newer than 3.5.10 so we don't silently continue
* Correct --enable-system-libffi option when installing the ffi gem
* Only install ffi gem once
* Remove nokogiri work around for macOS 12 ARM
* Namespace gem_install_options
```
/opt/puppetlabs/puppet/lib/ruby//gems/3.2.0/extensions/arm64-darwin/3.2.0/nokogiri-1.14.2/nokogiri/nokogiri.bundle:
/opt/puppetlabs/puppet/lib/libruby.3.2.dylib (compatibility version 3.2.0, current version 3.2.3)
/opt/puppetlabs/puppet/lib/libexslt.0.dylib (compatibility version 9.0.0, current version 9.21.0)
/opt/puppetlabs/puppet/lib/libxslt.1.dylib (compatibility version 3.0.0, current version 3.39.0) …
```
> Correctly patch host ruby 3.2.3 and 3.2.4 when cross compiling

- configs/components/rubygem-ffi.rb
Previously, we had pinned the FFI gem to 1.15.5 because 1.16.0 had a bug that affected Windows. That bug was resolved in 1.16.3[1] and we updated Facter (puppetlabs/facter@9ef20e5) and Puppet
(puppetlabs/puppet@aa51340) to be compatible with this version of FFI.
This commit updates all instances of FFI 1.15.5 (generic gem and Windows 32- and 64-bit gems) to 1.16.3.
[1] https://github.com/ffi/ffi/issues/1056
> Bump FFI gem from 1.15.5 to 1.16.3

- configs/components/yaml-cpp.rb
- configs/platforms/amazon-2-aarch64.rb
Amazon 7 is an implementation detail, the actual OS is named Amazon 2
~Blocked on https://github.com/puppetlabs/vanagon/pull/855~
Generic Builder with packaging 0.120.0 and vanagon 0.52.0: https://jenkins-platform.delivery.puppetlabs.net/view/vanagon-generic-builder/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/3003/BUILD_TARGET=amazon-2-aarch64,SLAVE_LABEL=k8s-worker/
> Rename amazon 7 to 2

- configs/components/ruby-2.7.8.rb
- configs/components/ruby-3.2.4.rb
- configs/projects/agent-runtime-main.rb
- configs/projects/pdk-runtime.rb
- configs/projects/pe-bolt-server-runtime-main.rb
- configs/projects/pe-installer-runtime-main.rb
- resources/patches/ruby_27/regexp_use_after_free.patch
- resources/patches/ruby_32/revert-ruby-double-load-symlink.patch
- resources/patches/ruby_32/revert_speed_up_rebuilding_loaded_feature_index.patch
- Patches the ruby 'Use-After-Free' issue for regexp for 7.x (ruby 2.7.8).
- Upstream fix commit: https://github.com/ruby/ruby/commit/90b194b5e3fe793c1ed895a4522675845181e6fd
- Bump projects using ruby 3.2.3 to ruby 3.2.4 since 3.2.4 has addressed the CVE.
- Remove windows patches not needed in upgraded ruby version.
> (PA-6386) Patch/Upgrade Ruby for CVE-2024-27282

- configs/components/_base-ruby-selinux.rb
- resources/patches/ruby-selinux/selinuxswig_ruby_undefining_allocator.patch
After puppetlabs/puppet#9349 was merged the
`warning: undefining the allocator of T_DATA class SWIG::TYPE_p_selabel_handle`
error popped up again on RHEL-8 x86_64.
We ran into this previously and thought puppetlabs/puppet-runtime#620 fixed it completely. This issue was completely fixed in swig 4.2.0+.
This commit patches selinuxswig_ruby_wrap.c with swig/swig@aa21014 and is applied after the patch from puppetlabs/puppet-runtime#620 since the fix in swig/swig@aa21014 came after.
> (PA-6549) Fix warning:undefining the allocator of T_DATA class

- configs/platforms/aix-7.1-ppc.rb
Libxml2 requires XZ, previously we were installing libxml2 version 2.10.4 which allowed older versions of XZ.
Now agent-runtime-7.x for AIX 7.1 attempts to install LibXML2 version 2.12.6 which requires a newer xz version of then the 2.5.4 we install on AIX 7.1. This commit updates the xz we install for agent-runtime-7.x for AIX from 5.2.4 to 5.4.3.
> (maint) Bump Aix-7.1's xz to 5.4.3

- configs/components/_base-ruby-selinux.rb
- resources/patches/ruby-selinux/selinuxswig_ruby_undefining_allocator.patch
- resources/patches/ruby-selinux/undefining_allocator_el_7.patch
This PR reverts #861 and adds additional steps to patch selinux_ruby_wrap.c for RHEL 7 and RHEL FIPS 7.
> (PA-6549) Patch selinux_ruby_wrap.c to fix warning: undefining the allocator of T_DATA class # SWIG::TYPE_p_selabel_handle

- configs/components/_base-ruby-selinux.rb
We only need to patch older Debian/Fedora/Ubuntu, but shouldn't need to for future additions.
Vanagon doesn't render the `agent-runtime-main` project any differently (since we haven't added hosts beyond Debian 12, etc):
```
$ bundle exec rake vanagon:component_diff -- -m -P agent-runtime-main -p all --from upstream/master --to HEAD 
...
Nothing is affected 😊
```
I also built https://jenkins-platform.delivery.puppetlabs.net/view/vanagon-generic-builder/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/3017/
> Future proof ruby-selinux

- configs/components/openssl-1.1.1.rb
- resources/patches/openssl/openssl-1.1.1-CVE-2024-4741.patch
Applied CVE-2024-4741 to openssl 1.1.1v
> (PA-6625): Applied following CVE-2024-4741 to openssl

- configs/projects/_shared-agent-components.rb
- configs/projects/agent-runtime-7.x.rb
- configs/projects/agent-runtime-main.rb
The puppet module install command assumes tar is GNUtar, which doesn't
work on AIX. Install minitar on AIX like we do for Windows and Solaris.
This relates to https://github.com/puppetlabs/puppet/pull/9387#discussion_r1643631563
Built https://jenkins-platform.delivery.puppetlabs.net/view/vanagon-generic-builder/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/3018/BUILD_TARGET=aix-7.2-ppc,SLAVE_LABEL=k8s-worker/
```
14:19:04 export GEM_HOME="/opt/puppetlabs/puppet/lib/ruby/gems/3.2.0" && \
14:19:04 export GEM_PATH="/opt/puppetlabs/puppet/lib/ruby/gems/3.2.0" && \
14:19:04 export RUBYLIB="/opt/puppetlabs/puppet/lib/ruby/vendor_ruby:" && \
14:19:04 cd ./ && \
14:19:04 /opt/puppetlabs/puppet/bin/gem install --no-document --local minitar-0.9.gem
14:19:05 The `minitar` …
```
> Add minitar rubygem on AIX

- .github/workflows/component_diff_check.yaml
- .github/workflows/mend.yaml
- .github/workflows/runtime_tests.yaml
This commit updates Ruby from 3.2 to 3.3 in our GitHub Actions. The latest Ubuntu 22.04 runner image from GitHub has started causing errors in our builds, possibly due to the new inclusion of Ruby 3.2 in the base image.
> Switch to Ruby 3.3 for GitHub Actions

- configs/components/rubygem-puppet-modulebuilder.rb
- configs/projects/_pdk-components.rb
This PR adds the puppet-modulebuilder gem to the gems bundled with the pdk. This gem is now required for the module build functionality.
> (CAT-1869) - Add puppet-modulebuilder to pdk bundled gems

- configs/components/ruby-2.7.8.rb
- resources/patches/ruby_27/stringio_cve-2024-27280.patch
- Upstream fix commit: https://github.com/ruby/stringio/commit/a35268a3ac -
> (PA-6283) Patch stringio in Ruby 2.7 for CVE-2024-27280

- configs/components/rubygem-rexml.rb
- configs/projects/_shared-agent-components.rb
- The CVE was fixed from rexml version 3.2.7.
- Patching for the CVE wasn't getting applied cleanly and had a lot of conflicts. So updated the gem version to 3.2.9 in the rexml component file.
- rexml 3.2.7 requires strscan >= 3.0.9 which contains native extensions. We would need a compiler to build the extensions and there are jruby incompatibilities. This requirement has been relaxed starting from rexml 3.2.9. Therefore we update to rexml 3.2.9 here.
- Added the change to _shared-agent-components since the CVE impacts both agent-runtime-main (ruby 3.2.4 using rexml 3.2.6) and agent-runtime-7.x (ruby 2.7.8 using rexml 3.2.3)
- For solaris-10-sparc and solaris-11-sparc, we ignore dependency when installing rexml since the ruby in these platforms tries to install strscan (rexml's …
> (PA-6507) Update gem rexml from default to 3.2.9 for CVE-2024-35176

- configs/components/rubygem-rexml.rb
- configs/projects/_shared-agent-components.rb
Reverts puppetlabs/puppet-runtime#873 as this wont be going in the current release because of issue identified while validating package
`Unresolved or ambiguous specs during Gem::Specification.reset`
> Revert "(PA-6507) Update gem rexml from default to 3.2.9 for CVE-2024-35176"

- configs/components/git.rb
- Update the git component so that a line rejecting `dh-autoreconf` as a dependency when building for RedHat 8 and 9 will do the same when building against their AARCH architecture versions.
> (CAT-1903) Add support for RedHat 8 and 9 AARCH architecture to the PDK

- configs/components/rubygem-addressable.rb
- configs/components/rubygem-aws-partitions.rb
- configs/components/rubygem-aws-sdk-core.rb
- configs/components/rubygem-aws-sdk-ec2.rb
- configs/components/rubygem-aws-sigv4.rb
- configs/components/rubygem-builder.rb
- configs/components/rubygem-cri.rb
- configs/components/rubygem-erubi.rb
- configs/components/rubygem-facter.rb
- configs/components/rubygem-faraday-net_http.rb
- configs/components/rubygem-fast_gettext.rb
- configs/components/rubygem-ffi.rb
- configs/components/rubygem-json-schema.rb
- configs/components/rubygem-logging.rb
- configs/components/rubygem-multipart-post.rb
- configs/components/rubygem-public_suffix.rb
- configs/components/rubygem-puppet.rb
- configs/components/rubygem-r10k.rb
- configs/components/rubygem-rexml.rb
- configs/components/rubygem-rubyntlm.rb
- configs/projects/bolt-runtime.rb
- configs/projects/pe-bolt-server-runtime-2021.7.x.rb
- configs/projects/pe-bolt-server-runtime-main.rb
- configs/projects/pe-installer-runtime-2021.7.x.rb
- configs/projects/pe-installer-runtime-main.rb
This commit updates the shared gems for ruby runtimes (bolt, installer, bolt-server, orch, etc) ahead of the impending PE releases.
> (PE-38998) Update shared ruby runtime for PE release

- configs/components/rubygem-ffi.rb
The puppet gem constrians ffi to < 1.17 for now. This commit reverts the 1.17 bump.
> (PE-38998) Revert ffi bump

- configs/components/rubygem-getoptlong.rb
- configs/projects/pe-bolt-server-runtime-main.rb
Puppet 8 now has an explict dep on getoptlong https://github.com/puppetlabs/puppet/pull/9398/commits/5bce3bb270785faac0cd5a9a3bdfe4c1ae38b341 This is a "default" gem for ruby 3. When orchestrator's jruby tries to load bolt it cant find the default gems. This commit explictly packages the getoptlong gem outside of the default gems.
> (PE-38998) Include getoptlong for bolt-server main

- configs/components/openssl-3.0.rb
- resources/patches/openssl/CVE-2024-5535.patch
Puppet-runtime build
https://jenkins-platform.delivery.puppetlabs.net/view/vanagon-generic-builder/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/3161/console
Puppet -agent build
https://jenkins-platform.delivery.puppetlabs.net/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/3162/
> (PA-6699) Bump puppet-agent's bundled openssl 3.0 to address CVE-2024-5535

- configs/components/_base-ruby.rb
- configs/components/augeas.rb
- configs/components/ruby-2.7.8.rb
- configs/components/ruby-3.2.5.rb
- configs/components/runtime-bolt.rb
- configs/projects/_shared-agent-settings.rb
- configs/projects/_shared-compiler-settings.rb
Enable PIE for Ubuntu 22, Debian 10 and up
agent-runtime-main: https://jenkins-platform.delivery.puppetlabs.net/view/vanagon-generic-builder/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/3168/
agent-runtime-7.x: https://jenkins-platform.delivery.puppetlabs.net/view/vanagon-generic-builder/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/3167/
pdk-runtime: https://jenkins-platform.delivery.puppetlabs.net/view/vanagon-generic-builder/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/3170/
bolt-runtime: https://jenkins-platform.delivery.puppetlabs.net/view/vanagon-generic-builder/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/3171/
pe-installer-runtime-2021.7.x: …
> (PA-6383) Enable PIE for Ubuntu and Debian

- configs/components/curl.rb
- configs/projects/agent-runtime-main.rb
[vanagon-generic-builder (generic) Generic Builder Step 03 -- Vanagon Project Packaging #3175 [Jenkins]](https://jenkins-platform.delivery.puppetlabs.net/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/3175/
)
[Index of /puppet-runtime/bb946dd72aae72481e2bd71f6a1f4bb527f08770/artifacts/
](http://builds.delivery.puppetlabs.net/puppet-runtime/bb946dd72aae72481e2bd71f6a1f4bb527f08770/artifacts/)
[vanagon-generic-builder (generic) Generic Builder Step 03 -- Vanagon Project Packaging #3176 Console [Jenkins]](https://jenkins-platform.delivery.puppetlabs.net/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/3176/console)
[Index of /puppet-agent/f9836323568d51146c11173a156ec0dcf472f687/artifacts/el/7/puppet8/x86_64/ …
> (PA-6872) Upgrade Curl to address CVE-2024-6874 and CVE-2024-6197

- configs/components/openssl-1.1.1.rb
* [vanagon-generic-builder (generic) Generic Builder Step 03 -- Vanagon Project Packaging #3178 Console [Jenkins]](
https://jenkins-platform.delivery.puppetlabs.net/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/3178/console)
* [Index of /puppet-runtime/a20ef9232a3ed9b732e5e2c3d12df12015d68864/artifacts/](
http://builds.delivery.puppetlabs.net/puppet-runtime/a20ef9232a3ed9b732e5e2c3d12df12015d68864/artifacts/)
* [vanagon-generic-builder (generic) Generic Builder Step 03 -- Vanagon Project Packaging #3179 Console [Jenkins]](
https://jenkins-platform.delivery.puppetlabs.net/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/3179/console)
* [Index of /puppet-agent/11a3d34e5d4e723bce59daca166a4d6aab1add3e/artifacts/deb/bionic/puppet7/]( …
> (PA-6889) Bump puppet-agent's bundled openssl 1.1.1v to 1.1.1w and addressed CVE-2024-5535

- configs/components/curl.rb
- configs/components/openssl-1.0.2.rb
- configs/components/ruby-2.7.8.rb
- configs/components/ruby-3.2.5.rb
- configs/platforms/windowsfips-2016-x64.rb
- configs/projects/_shared-agent-components.rb
- configs/projects/_shared-agent-settings.rb
- resources/patches/ruby_27/rbconfig_win.patch
- resources/patches/ruby_32/rbconfig_win.patch
- Add the platform file for windowsfips-2016-x64.
- Add windowsfips-2016 to ruby dtrace for both 7.x and main.
- Set fips version and fips flags properly.
- Set NM to the system nm (version 2.42) since mingw nm (version 2.25) conflicts with sed during curl-build.
- Patch rbconfig.rb to remove the '\r' character appended to CONFIG["ruby_version"] during ruby-build.
> (PA-6324) Add windowsfips-2016-x64 to agent-runtime-main and agent-runtime-7.x

- configs/components/_base-rubygem.rb
- configs/components/rubygem-rexml.rb
- configs/projects/_shared-agent-components.rb
- configs/projects/_shared-agent-settings.rb
- configs/projects/agent-runtime-7.x.rb
[vanagon-generic-builder (generic) Generic Builder Step 03 -- Vanagon Project Packaging #3181 Console [Jenkins]](
https://jenkins-platform.delivery.puppetlabs.net/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/3181/console)
[Index of /puppet-runtime/63d6a583a1e69661d6795bd48f92074d119ef7e1/artifacts/](
http://builds.delivery.puppetlabs.net/puppet-runtime/63d6a583a1e69661d6795bd48f92074d119ef7e1/artifacts/)
[vanagon-generic-builder (generic) Generic Builder Step 03 -- Vanagon Project Packaging #3182 Console [Jenkins]](
https://jenkins-platform.delivery.puppetlabs.net/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/3182/console)
[Index of /puppet-agent/eb37c609e51f1b8c94d7634d71ac206867eedbd7/artifacts/deb/bionic/puppet8/]( …
> (PA-6881) Adding rexml gem to agent-runtime-main for CVE-2024-41123 and CVE-2024-41946

- configs/components/ruby-2.7.8.rb
- resources/patches/ruby_27/0001-Filter-marshaled-objects-ruby30.patch
- resources/patches/ruby_27/0001-Use-safe_load-and-safe_load_file-for-rdoc_options.patch
[Ruby disclosed on HackerOne: RCE by parsing `.rdoc_options` in RDoc](https://hackerone.com/reports/1187477#activity-26252039) Specifically:
[0001-Filter-marshaled-objects-ruby30.patch (F3085308)](https://hackerone-us-west-2-production-attachments.s3.us-west-2.amazonaws.com/z7gowk9ovy6p1mqp5nc0hv40vldj?response-content-disposition=attachment%3B%20filename%3D%220001-Filter-marshaled-objects-ruby30.patch%22%3B%20filename%2A%3DUTF-8%27%270001-Filter-marshaled-objects-ruby30.patch&response-content-type=application%2Fmbox&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=ASIAQGK6FURQ7LQ3AJDD%2F20240805%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20240805T173544Z&X-Amz-Expires=3600&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEPD%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCXVzLXdlc3QtMiJIMEYCIQDlQO%2Bol3n6imF%2B0Vm …
> (PA-6282) RDoc vulnerability in Puppet7/Ruby 2.7.8 (CVE-2024-27281)

- configs/components/curl.rb
- resources/patches/curl/CVE-2024-7264.patch
Patch to fix curl CVE-2024-7264
7.x curl version - 7.88.1
For 7.x patch was inspired from : [http://archive.ubuntu.com/ubuntu/pool/main/c/curl/](http://archive.ubuntu.com/ubuntu/pool/main/c/curl/curl_7.68.0-1ubuntu2.23.debian.tar.xz)
For main - we have the curl 8.9.1 version for which the fix is already present as per  https://curl.se/docs/CVE-2024-7264.html
vanagon-generic-main : https://jenkins-platform.delivery.puppetlabs.net/view/vanagon-generic-builder/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/3215/
vanagon-generic-7.x : https://jenkins-platform.delivery.puppetlabs.net/view/vanagon-generic-builder/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/3214/
> (PA-6878) Patch agent-runtime-7.x and main Curl for CVE-2024-7264

- configs/components/_base-rubygem.rb
With the addition logic in https://github.com/puppetlabs/puppet-runtime/pull/901 for deduplicating rexml gems an inadvertant requirement was imposed on projects to define a `gem_uninstall` command. This command should be ubiquitous (especially with impending ruby 3 only streams)  so instead of requiring all projects to configure it a default is added. This setting is still configurable at a project level, but is not required.
> (PA-6881) Configure a default gem_uninstall command

- configs/components/openssl-3.0.rb
* Agent Runtime Build
[vanagon-generic-builder (generic) Generic Builder Step 03 -- Vanagon Project Packaging #3233 Console [Jenkins]
](https://jenkins-platform.delivery.puppetlabs.net/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/3233/console)
* Agent Runtime Artifacts
[Index of /puppet-runtime/3b33d1a6b0d2c1535a25ef77c9ac3fcbd8e60946/artifacts/](
http://builds.delivery.puppetlabs.net/puppet-runtime/3b33d1a6b0d2c1535a25ef77c9ac3fcbd8e60946/artifacts/)
* Puppet Agent Build
[vanagon-generic-builder (generic) Generic Builder Step 03 -- Vanagon Project Packaging #3234 Console [Jenkins]
](https://jenkins-platform.delivery.puppetlabs.net/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/3234/console)
* Puppet Agent Artifacts
[Index of …
> (PA-6959) Update OpenSSL to 3.0.15 for puppet-agent main

- resources/patches/ruby_27/0001-Filter-marshaled-objects-ruby30.patch
Installing r10k was failing on ruby 2.7 due to our faulty rdoc patch
/opt/puppetlabs/puppet/bin/gem install r10k
ERROR:  While executing gem ... (NoMethodError)
undefined method `start_with' for "RDoc::Markup::Document":String
Apply the upstream fix from ruby/rdoc@e21dfccb4a
> (PA-7089) Apply upstream rdoc fix for start_with?

- configs/components/curl.rb
- resources/patches/curl/CVE-2024-8096.patch
Upstream commit: https://github.com/curl/curl/commit/aeb1a281cab13c7ba
> (PA-6961) Patch for CVE-2024-8096 (Curl)

- configs/components/curl.rb
- configs/projects/agent-runtime-main.rb
Upgrade Curl to 8.10.1 to mitigate CVE-2024-8096
vanagon generic builder : https://jenkins-platform.delivery.puppetlabs.net/view/vanagon-generic-builder/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/3296/
> (PA-6962) update curl to address CVE-2024-8096

- configs/components/rubygem-faraday-follow_redirects.rb
- configs/components/rubygem-faraday-net_http.rb
- configs/components/rubygem-faraday.rb
- configs/components/rubygem-puppet_forge.rb
- configs/projects/_pdk-components.rb
- configs/projects/pdk-runtime.rb
This PR adds 5.0.4 puppet forge gem as a component and a dependency to the PDK project
dependencies of puppet-forge gem: 
faraday ~> 2.0 -> v2.12.0 added as component
faraday-follow_redirects ~> 0.3.0 -> added as component
minitar < 1.0.0 -> v0.9.0 already present in runtime
semantic_puppet ~> 1.0 -> semantic puppet version 1.1.0 already present in runtime (default version)
https://jenkins-platform.delivery.puppetlabs.net/view/vanagon-generic-builder/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/3293/
> (CAT-643) - Add puppet_forge to pdk-runtime

- configs/projects/_pdk-components.rb
Prior to this PR, pathspec (which is a runtime dependency of puppet-modubuilder) was added as a component after the puppet-modulebuilder gem, which I don't believe is correct.
This PR updates the puppet-modulebuilder gem to be pulled in after its dependencies.
https://jenkins-platform.delivery.puppetlabs.net/view/vanagon-generic-builder/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/3304/
> (CAT-2111) - Add puppet-modulebuilder deps first to pdk

- configs/projects/bolt-runtime.rb
With these changes I was able to successfully build bolt-runtime for el-9-x86_64
> Updates for Ruby, Openssl, net-ssh, Puppet for Bolt runtime

- configs/components/rubygem-pathspec.rb
Change had broken the pdk-runtime as it is reliant on a pathspec version of less than 2
> (CAT-2136) Revert cange to `rubygem-pathspec.rb`

- configs/components/rubygem-json_pure.rb
- configs/projects/_pdk-components.rb
This was originally added to ensure JSON would be available in all environments but should no longer necessary as JSON has been added as a default ruby gem.
> (CAT-2128) Remove json_pure dependency from the PDK runtime

- configs/components/rubygem-r10k.rb
Updated rubygem-r10k  from 3.16.2 to 4.1.0.
> Update rubygem-r10k to 4.1.0

- configs/components/rubygem-puppet.rb
- configs/projects/bolt-runtime.rb
- configs/projects/pe-bolt-server-runtime-2023.8.x.rb
- configs/projects/pe-bolt-server-runtime-main.rb
- configs/projects/pe-installer-runtime-2023.8.x.rb
- configs/projects/pe-installer-runtime-main.rb
Updated rubygem-puppet's Puppet 8 version from 8.8.1 to 8.10.0. I have also updated all relevant runtimes
> Update rubygem-puppet to 8.10.0

- configs/components/rubygem-r10k.rb
Reverts https://github.com/puppetlabs/puppet-runtime/pull/927
Seems to be breaking projects that use r10k
> Revert "Update rubygem-r10k to 4.1.0"

- configs/components/rubygem-faraday-net_http_persistent.rb
- configs/components/rubygem-orchestrator_client.rb
- configs/components/rubygem-r10k.rb
- configs/projects/bolt-runtime.rb
Updating to r10k 4 also required the following changes:
- Removed faraday_middleware in bolt-runtime and added faraday-net_http_persistent 2.3.0 as faraday_middleware does not support faraday 2. Further, It is not necessary to use faraday_middleware when using net_http_persistent on Ruby 2.0+ (see - https://github.com/lostisland/faraday_middleware/issues/279#issuecomment-1021023287)
- Updated orchestrator client version from 0.7.0 to 0.7.1 as 0.7.0 had a conflicting faraday version with puppet forge
- Specified puppet forge and faraday/faraday dependency versions in bolt-runtime
Testing:
- Was able to run a passing build for el-9-x86_64 in puppet-runtime and bolt-vanagon
- Bolt acceptance tests passing
> Updated rubygem-r10k from 3.16.2 to 4.1.0

- configs/components/git.rb
Previous version chosen to update to, `2.47.0`, caused issues on el-7, el8 and sles-12
> (CAT-2123) Set version of `git` within the pdk-runtime to `2.39.4`
